// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: webcast.proto

package co.casterlabs.sdk.tiktok.unsupported.webcast.proto.webcast;

public interface RoomMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TikTok.RoomMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.TikTok.Common common = 1;</code>
   * @return Whether the common field is set.
   */
  boolean hasCommon();
  /**
   * <code>.TikTok.Common common = 1;</code>
   * @return The common.
   */
  co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.Common getCommon();
  /**
   * <code>.TikTok.Common common = 1;</code>
   */
  co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.CommonOrBuilder getCommonOrBuilder();

  /**
   * <code>string content = 2;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <code>string content = 2;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <code>bool supprotLandscape = 3;</code>
   * @return The supprotLandscape.
   */
  boolean getSupprotLandscape();

  /**
   * <code>int64 source = 4;</code>
   * @return The source.
   */
  long getSource();

  /**
   * <code>.TikTok.Image icon = 5;</code>
   * @return Whether the icon field is set.
   */
  boolean hasIcon();
  /**
   * <code>.TikTok.Image icon = 5;</code>
   * @return The icon.
   */
  co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.Image getIcon();
  /**
   * <code>.TikTok.Image icon = 5;</code>
   */
  co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.ImageOrBuilder getIconOrBuilder();

  /**
   * <code>string scene = 6;</code>
   * @return The scene.
   */
  java.lang.String getScene();
  /**
   * <code>string scene = 6;</code>
   * @return The bytes for scene.
   */
  com.google.protobuf.ByteString
      getSceneBytes();

  /**
   * <code>bool isWelcome = 7;</code>
   * @return The isWelcome.
   */
  boolean getIsWelcome();
}
