// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: webcast.proto

package co.casterlabs.sdk.tiktok.unsupported.webcast.proto.webcast;

public interface WebcastMsgDetectMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TikTok.WebcastMsgDetectMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.TikTok.Common common = 1;</code>
   * @return Whether the common field is set.
   */
  boolean hasCommon();
  /**
   * <code>.TikTok.Common common = 1;</code>
   * @return The common.
   */
  co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.Common getCommon();
  /**
   * <code>.TikTok.Common common = 1;</code>
   */
  co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.CommonOrBuilder getCommonOrBuilder();

  /**
   * <pre>
   * Possibly an Enum?
   * </pre>
   *
   * <code>int32 detectType = 2;</code>
   * @return The detectType.
   */
  int getDetectType();

  /**
   * <code>.TikTok.WebcastMsgDetectMessage.TriggerCondition triggerCondition = 3;</code>
   * @return Whether the triggerCondition field is set.
   */
  boolean hasTriggerCondition();
  /**
   * <code>.TikTok.WebcastMsgDetectMessage.TriggerCondition triggerCondition = 3;</code>
   * @return The triggerCondition.
   */
  co.casterlabs.sdk.tiktok.unsupported.webcast.proto.webcast.WebcastMsgDetectMessage.TriggerCondition getTriggerCondition();
  /**
   * <code>.TikTok.WebcastMsgDetectMessage.TriggerCondition triggerCondition = 3;</code>
   */
  co.casterlabs.sdk.tiktok.unsupported.webcast.proto.webcast.WebcastMsgDetectMessage.TriggerConditionOrBuilder getTriggerConditionOrBuilder();

  /**
   * <code>.TikTok.WebcastMsgDetectMessage.TimeInfo timeInfo = 4;</code>
   * @return Whether the timeInfo field is set.
   */
  boolean hasTimeInfo();
  /**
   * <code>.TikTok.WebcastMsgDetectMessage.TimeInfo timeInfo = 4;</code>
   * @return The timeInfo.
   */
  co.casterlabs.sdk.tiktok.unsupported.webcast.proto.webcast.WebcastMsgDetectMessage.TimeInfo getTimeInfo();
  /**
   * <code>.TikTok.WebcastMsgDetectMessage.TimeInfo timeInfo = 4;</code>
   */
  co.casterlabs.sdk.tiktok.unsupported.webcast.proto.webcast.WebcastMsgDetectMessage.TimeInfoOrBuilder getTimeInfoOrBuilder();

  /**
   * <pre>
   * Possible an Enum?
   * </pre>
   *
   * <code>int32 triggerBy = 5;</code>
   * @return The triggerBy.
   */
  int getTriggerBy();

  /**
   * <code>string fromRegion = 6;</code>
   * @return The fromRegion.
   */
  java.lang.String getFromRegion();
  /**
   * <code>string fromRegion = 6;</code>
   * @return The bytes for fromRegion.
   */
  com.google.protobuf.ByteString
      getFromRegionBytes();
}
