// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: enums.proto
// Protobuf Java Version: 4.32.0

package co.casterlabs.sdk.tiktok.unsupported.types.protobuf.enums;

/**
 * Protobuf enum {@code TikTok.GoalMessageSource}
 */
@com.google.protobuf.Generated
public enum GoalMessageSource
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>GOAL_MESSAGE_SOURCE_UNKNOWN = 0;</code>
   */
  GOAL_MESSAGE_SOURCE_UNKNOWN(0),
  /**
   * <code>GOAL_MESSAGE_SOURCE_COMMIT = 1;</code>
   */
  GOAL_MESSAGE_SOURCE_COMMIT(1),
  /**
   * <code>GOAL_MESSAGE_SOURCE_PROGRESS_UPDATE = 2;</code>
   */
  GOAL_MESSAGE_SOURCE_PROGRESS_UPDATE(2),
  /**
   * <code>GOAL_MESSAGE_SOURCE_PIN = 3;</code>
   */
  GOAL_MESSAGE_SOURCE_PIN(3),
  /**
   * <code>GOAL_MESSAGE_SOURCE_UNPIN = 4;</code>
   */
  GOAL_MESSAGE_SOURCE_UNPIN(4),
  /**
   * <code>GOAL_MESSAGE_SOURCE_REVIEW_CALLBACK = 5;</code>
   */
  GOAL_MESSAGE_SOURCE_REVIEW_CALLBACK(5),
  /**
   * <code>GOAL_MESSAGE_SOURCE_SUSPEND = 6;</code>
   */
  GOAL_MESSAGE_SOURCE_SUSPEND(6),
  /**
   * <code>GOAL_MESSAGE_SOURCE_CHALLENGE_PROMPT = 7;</code>
   */
  GOAL_MESSAGE_SOURCE_CHALLENGE_PROMPT(7),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      GoalMessageSource.class.getName());
  }
  /**
   * <code>GOAL_MESSAGE_SOURCE_UNKNOWN = 0;</code>
   */
  public static final int GOAL_MESSAGE_SOURCE_UNKNOWN_VALUE = 0;
  /**
   * <code>GOAL_MESSAGE_SOURCE_COMMIT = 1;</code>
   */
  public static final int GOAL_MESSAGE_SOURCE_COMMIT_VALUE = 1;
  /**
   * <code>GOAL_MESSAGE_SOURCE_PROGRESS_UPDATE = 2;</code>
   */
  public static final int GOAL_MESSAGE_SOURCE_PROGRESS_UPDATE_VALUE = 2;
  /**
   * <code>GOAL_MESSAGE_SOURCE_PIN = 3;</code>
   */
  public static final int GOAL_MESSAGE_SOURCE_PIN_VALUE = 3;
  /**
   * <code>GOAL_MESSAGE_SOURCE_UNPIN = 4;</code>
   */
  public static final int GOAL_MESSAGE_SOURCE_UNPIN_VALUE = 4;
  /**
   * <code>GOAL_MESSAGE_SOURCE_REVIEW_CALLBACK = 5;</code>
   */
  public static final int GOAL_MESSAGE_SOURCE_REVIEW_CALLBACK_VALUE = 5;
  /**
   * <code>GOAL_MESSAGE_SOURCE_SUSPEND = 6;</code>
   */
  public static final int GOAL_MESSAGE_SOURCE_SUSPEND_VALUE = 6;
  /**
   * <code>GOAL_MESSAGE_SOURCE_CHALLENGE_PROMPT = 7;</code>
   */
  public static final int GOAL_MESSAGE_SOURCE_CHALLENGE_PROMPT_VALUE = 7;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static GoalMessageSource valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static GoalMessageSource forNumber(int value) {
    switch (value) {
      case 0: return GOAL_MESSAGE_SOURCE_UNKNOWN;
      case 1: return GOAL_MESSAGE_SOURCE_COMMIT;
      case 2: return GOAL_MESSAGE_SOURCE_PROGRESS_UPDATE;
      case 3: return GOAL_MESSAGE_SOURCE_PIN;
      case 4: return GOAL_MESSAGE_SOURCE_UNPIN;
      case 5: return GOAL_MESSAGE_SOURCE_REVIEW_CALLBACK;
      case 6: return GOAL_MESSAGE_SOURCE_SUSPEND;
      case 7: return GOAL_MESSAGE_SOURCE_CHALLENGE_PROMPT;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<GoalMessageSource>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      GoalMessageSource> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<GoalMessageSource>() {
          public GoalMessageSource findValueByNumber(int number) {
            return GoalMessageSource.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return co.casterlabs.sdk.tiktok.unsupported.types.protobuf.enums.Enums.getDescriptor().getEnumTypes().get(44);
  }

  private static final GoalMessageSource[] VALUES = values();

  public static GoalMessageSource valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private GoalMessageSource(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:TikTok.GoalMessageSource)
}

