// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: enums.proto
// Protobuf Java Version: 4.32.0

package co.casterlabs.sdk.tiktok.unsupported.types.protobuf.enums;

/**
 * Protobuf enum {@code TikTok.PerceptionDialogIconType}
 */
@com.google.protobuf.Generated
public enum PerceptionDialogIconType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_NONE = 0;</code>
   */
  PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_NONE(0),
  /**
   * <code>PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_WARNING = 1;</code>
   */
  PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_WARNING(1),
  /**
   * <code>PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_LINK_MIC = 2;</code>
   */
  PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_LINK_MIC(2),
  /**
   * <code>PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_GUEST_LINK_MIC = 3;</code>
   */
  PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_GUEST_LINK_MIC(3),
  /**
   * <code>PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_LIVE = 4;</code>
   */
  PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_LIVE(4),
  /**
   * <code>PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_TREASURE_BOX = 5;</code>
   */
  PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_TREASURE_BOX(5),
  /**
   * <code>PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_MUTE = 6;</code>
   */
  PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_MUTE(6),
  /**
   * <code>PERCEPTION_DIALOG_ICON_TYPE_ICON_GAMEPAD_ACCESS_REVOKED = 7;</code>
   */
  PERCEPTION_DIALOG_ICON_TYPE_ICON_GAMEPAD_ACCESS_REVOKED(7),
  /**
   * <code>PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_BAN_REPORT_LIVE_SINGLE_ROOM = 8;</code>
   */
  PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_BAN_REPORT_LIVE_SINGLE_ROOM(8),
  /**
   * <code>PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_BAN_REPORT_LIVE_ALL_ROOM = 9;</code>
   */
  PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_BAN_REPORT_LIVE_ALL_ROOM(9),
  /**
   * <code>PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_BAN_REPORT_LIVE_GREEN_SCREEN = 10;</code>
   */
  PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_BAN_REPORT_LIVE_GREEN_SCREEN(10),
  /**
   * <code>PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_GIFT = 11;</code>
   */
  PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_GIFT(11),
  /**
   * <code>PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_APPEAL_SUCCESS = 12;</code>
   */
  PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_APPEAL_SUCCESS(12),
  /**
   * <code>PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_MATCH = 13;</code>
   */
  PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_MATCH(13),
  /**
   * <code>PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_LIVE_GOAL = 14;</code>
   */
  PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_LIVE_GOAL(14),
  /**
   * <code>PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_SUBSCRIPTION = 15;</code>
   */
  PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_SUBSCRIPTION(15),
  /**
   * <code>PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_STAR_COMMENT = 16;</code>
   */
  PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_STAR_COMMENT(16),
  /**
   * <code>PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_RANKING = 17;</code>
   */
  PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_RANKING(17),
  /**
   * <code>PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_COMMON = 18;</code>
   */
  PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_COMMON(18),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      PerceptionDialogIconType.class.getName());
  }
  /**
   * <code>PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_NONE = 0;</code>
   */
  public static final int PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_NONE_VALUE = 0;
  /**
   * <code>PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_WARNING = 1;</code>
   */
  public static final int PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_WARNING_VALUE = 1;
  /**
   * <code>PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_LINK_MIC = 2;</code>
   */
  public static final int PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_LINK_MIC_VALUE = 2;
  /**
   * <code>PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_GUEST_LINK_MIC = 3;</code>
   */
  public static final int PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_GUEST_LINK_MIC_VALUE = 3;
  /**
   * <code>PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_LIVE = 4;</code>
   */
  public static final int PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_LIVE_VALUE = 4;
  /**
   * <code>PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_TREASURE_BOX = 5;</code>
   */
  public static final int PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_TREASURE_BOX_VALUE = 5;
  /**
   * <code>PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_MUTE = 6;</code>
   */
  public static final int PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_MUTE_VALUE = 6;
  /**
   * <code>PERCEPTION_DIALOG_ICON_TYPE_ICON_GAMEPAD_ACCESS_REVOKED = 7;</code>
   */
  public static final int PERCEPTION_DIALOG_ICON_TYPE_ICON_GAMEPAD_ACCESS_REVOKED_VALUE = 7;
  /**
   * <code>PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_BAN_REPORT_LIVE_SINGLE_ROOM = 8;</code>
   */
  public static final int PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_BAN_REPORT_LIVE_SINGLE_ROOM_VALUE = 8;
  /**
   * <code>PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_BAN_REPORT_LIVE_ALL_ROOM = 9;</code>
   */
  public static final int PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_BAN_REPORT_LIVE_ALL_ROOM_VALUE = 9;
  /**
   * <code>PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_BAN_REPORT_LIVE_GREEN_SCREEN = 10;</code>
   */
  public static final int PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_BAN_REPORT_LIVE_GREEN_SCREEN_VALUE = 10;
  /**
   * <code>PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_GIFT = 11;</code>
   */
  public static final int PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_GIFT_VALUE = 11;
  /**
   * <code>PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_APPEAL_SUCCESS = 12;</code>
   */
  public static final int PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_APPEAL_SUCCESS_VALUE = 12;
  /**
   * <code>PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_MATCH = 13;</code>
   */
  public static final int PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_MATCH_VALUE = 13;
  /**
   * <code>PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_LIVE_GOAL = 14;</code>
   */
  public static final int PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_LIVE_GOAL_VALUE = 14;
  /**
   * <code>PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_SUBSCRIPTION = 15;</code>
   */
  public static final int PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_SUBSCRIPTION_VALUE = 15;
  /**
   * <code>PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_STAR_COMMENT = 16;</code>
   */
  public static final int PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_STAR_COMMENT_VALUE = 16;
  /**
   * <code>PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_RANKING = 17;</code>
   */
  public static final int PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_RANKING_VALUE = 17;
  /**
   * <code>PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_COMMON = 18;</code>
   */
  public static final int PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_COMMON_VALUE = 18;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static PerceptionDialogIconType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static PerceptionDialogIconType forNumber(int value) {
    switch (value) {
      case 0: return PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_NONE;
      case 1: return PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_WARNING;
      case 2: return PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_LINK_MIC;
      case 3: return PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_GUEST_LINK_MIC;
      case 4: return PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_LIVE;
      case 5: return PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_TREASURE_BOX;
      case 6: return PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_MUTE;
      case 7: return PERCEPTION_DIALOG_ICON_TYPE_ICON_GAMEPAD_ACCESS_REVOKED;
      case 8: return PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_BAN_REPORT_LIVE_SINGLE_ROOM;
      case 9: return PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_BAN_REPORT_LIVE_ALL_ROOM;
      case 10: return PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_BAN_REPORT_LIVE_GREEN_SCREEN;
      case 11: return PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_GIFT;
      case 12: return PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_APPEAL_SUCCESS;
      case 13: return PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_MATCH;
      case 14: return PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_LIVE_GOAL;
      case 15: return PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_SUBSCRIPTION;
      case 16: return PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_STAR_COMMENT;
      case 17: return PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_RANKING;
      case 18: return PERCEPTION_DIALOG_ICON_TYPE_ICON_TYPE_COMMON;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<PerceptionDialogIconType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      PerceptionDialogIconType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<PerceptionDialogIconType>() {
          public PerceptionDialogIconType findValueByNumber(int number) {
            return PerceptionDialogIconType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return co.casterlabs.sdk.tiktok.unsupported.types.protobuf.enums.Enums.getDescriptor().getEnumTypes().get(43);
  }

  private static final PerceptionDialogIconType[] VALUES = values();

  public static PerceptionDialogIconType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private PerceptionDialogIconType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:TikTok.PerceptionDialogIconType)
}

