// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: enums.proto
// Protobuf Java Version: 4.32.0

package co.casterlabs.sdk.tiktok.unsupported.types.protobuf.enums;

/**
 * Protobuf enum {@code TikTok.Scene}
 */
@com.google.protobuf.Generated
public enum Scene
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>SCENE_UNKNOWN = 0;</code>
   */
  SCENE_UNKNOWN(0),
  /**
   * <code>SCENE_CO_HOST = 2;</code>
   */
  SCENE_CO_HOST(2),
  /**
   * <code>SCENE_MULTI_LIVE = 4;</code>
   */
  SCENE_MULTI_LIVE(4),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      Scene.class.getName());
  }
  /**
   * <code>SCENE_UNKNOWN = 0;</code>
   */
  public static final int SCENE_UNKNOWN_VALUE = 0;
  /**
   * <code>SCENE_CO_HOST = 2;</code>
   */
  public static final int SCENE_CO_HOST_VALUE = 2;
  /**
   * <code>SCENE_MULTI_LIVE = 4;</code>
   */
  public static final int SCENE_MULTI_LIVE_VALUE = 4;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static Scene valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static Scene forNumber(int value) {
    switch (value) {
      case 0: return SCENE_UNKNOWN;
      case 2: return SCENE_CO_HOST;
      case 4: return SCENE_MULTI_LIVE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Scene>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      Scene> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<Scene>() {
          public Scene findValueByNumber(int number) {
            return Scene.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return co.casterlabs.sdk.tiktok.unsupported.types.protobuf.enums.Enums.getDescriptor().getEnumTypes().get(26);
  }

  private static final Scene[] VALUES = values();

  public static Scene valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private Scene(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:TikTok.Scene)
}

