// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: enums.proto
// Protobuf Java Version: 4.32.0

package co.casterlabs.sdk.tiktok.unsupported.types.protobuf.enums;

/**
 * Protobuf enum {@code TikTok.SubscribeType}
 */
@com.google.protobuf.Generated
public enum SubscribeType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>SUBSCRIBETYPE_ONCE = 0;</code>
   */
  SUBSCRIBETYPE_ONCE(0),
  /**
   * <code>SUBSCRIBETYPE_AUTO = 1;</code>
   */
  SUBSCRIBETYPE_AUTO(1),
  /**
   * <code>SUBSCRIBETYPE_DEFAULT = 100;</code>
   */
  SUBSCRIBETYPE_DEFAULT(100),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      SubscribeType.class.getName());
  }
  /**
   * <code>SUBSCRIBETYPE_ONCE = 0;</code>
   */
  public static final int SUBSCRIBETYPE_ONCE_VALUE = 0;
  /**
   * <code>SUBSCRIBETYPE_AUTO = 1;</code>
   */
  public static final int SUBSCRIBETYPE_AUTO_VALUE = 1;
  /**
   * <code>SUBSCRIBETYPE_DEFAULT = 100;</code>
   */
  public static final int SUBSCRIBETYPE_DEFAULT_VALUE = 100;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static SubscribeType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static SubscribeType forNumber(int value) {
    switch (value) {
      case 0: return SUBSCRIBETYPE_ONCE;
      case 1: return SUBSCRIBETYPE_AUTO;
      case 100: return SUBSCRIBETYPE_DEFAULT;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<SubscribeType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      SubscribeType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<SubscribeType>() {
          public SubscribeType findValueByNumber(int number) {
            return SubscribeType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return co.casterlabs.sdk.tiktok.unsupported.types.protobuf.enums.Enums.getDescriptor().getEnumTypes().get(12);
  }

  private static final SubscribeType[] VALUES = values();

  public static SubscribeType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private SubscribeType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:TikTok.SubscribeType)
}

