// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: webcast.proto
// Protobuf Java Version: 4.32.0

package co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast;

@com.google.protobuf.Generated
public interface BaseProtoMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TikTok.BaseProtoMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string type = 1;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>string type = 1;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>bytes payload = 2;</code>
   * @return The payload.
   */
  com.google.protobuf.ByteString getPayload();

  /**
   * <code>int64 msgId = 3;</code>
   * @return The msgId.
   */
  long getMsgId();

  /**
   * <code>int32 msgType = 4;</code>
   * @return The msgType.
   */
  int getMsgType();

  /**
   * <code>int64 offset = 5;</code>
   * @return The offset.
   */
  long getOffset();

  /**
   * <code>bool isHistory = 6;</code>
   * @return The isHistory.
   */
  boolean getIsHistory();
}
