// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: webcast.proto
// Protobuf Java Version: 4.32.0

package co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast;

/**
 * Protobuf type {@code TikTok.EmoteUploadInfo}
 */
@com.google.protobuf.Generated
public final class EmoteUploadInfo extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:TikTok.EmoteUploadInfo)
    EmoteUploadInfoOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      EmoteUploadInfo.class.getName());
  }
  // Use EmoteUploadInfo.newBuilder() to construct.
  private EmoteUploadInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private EmoteUploadInfo() {
    emoteUploadSource_ = 0;
    userIdStr_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.Webcast.internal_static_TikTok_EmoteUploadInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.Webcast.internal_static_TikTok_EmoteUploadInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.EmoteUploadInfo.class, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.EmoteUploadInfo.Builder.class);
  }

  /**
   * Protobuf enum {@code TikTok.EmoteUploadInfo.UserEmoteUploadSource}
   */
  public enum UserEmoteUploadSource
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>USER_EMOTE_UPLOAD_SOURCE_EMOTE_UPLOAD_SOURCE_ANCHOR = 0;</code>
     */
    USER_EMOTE_UPLOAD_SOURCE_EMOTE_UPLOAD_SOURCE_ANCHOR(0),
    /**
     * <code>USER_EMOTE_UPLOAD_SOURCE_EMOTE_UPLOAD_SOURCE_SUBSCRIBER = 1;</code>
     */
    USER_EMOTE_UPLOAD_SOURCE_EMOTE_UPLOAD_SOURCE_SUBSCRIBER(1),
    /**
     * <code>USER_EMOTE_UPLOAD_SOURCE_EMOTE_UPLOAD_SOURCE_MODERATOR = 2;</code>
     */
    USER_EMOTE_UPLOAD_SOURCE_EMOTE_UPLOAD_SOURCE_MODERATOR(2),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 32,
        /* patch= */ 0,
        /* suffix= */ "",
        UserEmoteUploadSource.class.getName());
    }
    /**
     * <code>USER_EMOTE_UPLOAD_SOURCE_EMOTE_UPLOAD_SOURCE_ANCHOR = 0;</code>
     */
    public static final int USER_EMOTE_UPLOAD_SOURCE_EMOTE_UPLOAD_SOURCE_ANCHOR_VALUE = 0;
    /**
     * <code>USER_EMOTE_UPLOAD_SOURCE_EMOTE_UPLOAD_SOURCE_SUBSCRIBER = 1;</code>
     */
    public static final int USER_EMOTE_UPLOAD_SOURCE_EMOTE_UPLOAD_SOURCE_SUBSCRIBER_VALUE = 1;
    /**
     * <code>USER_EMOTE_UPLOAD_SOURCE_EMOTE_UPLOAD_SOURCE_MODERATOR = 2;</code>
     */
    public static final int USER_EMOTE_UPLOAD_SOURCE_EMOTE_UPLOAD_SOURCE_MODERATOR_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static UserEmoteUploadSource valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static UserEmoteUploadSource forNumber(int value) {
      switch (value) {
        case 0: return USER_EMOTE_UPLOAD_SOURCE_EMOTE_UPLOAD_SOURCE_ANCHOR;
        case 1: return USER_EMOTE_UPLOAD_SOURCE_EMOTE_UPLOAD_SOURCE_SUBSCRIBER;
        case 2: return USER_EMOTE_UPLOAD_SOURCE_EMOTE_UPLOAD_SOURCE_MODERATOR;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<UserEmoteUploadSource>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        UserEmoteUploadSource> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<UserEmoteUploadSource>() {
            public UserEmoteUploadSource findValueByNumber(int number) {
              return UserEmoteUploadSource.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.EmoteUploadInfo.getDescriptor().getEnumTypes().get(0);
    }

    private static final UserEmoteUploadSource[] VALUES = values();

    public static UserEmoteUploadSource valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private UserEmoteUploadSource(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:TikTok.EmoteUploadInfo.UserEmoteUploadSource)
  }

  private int bitField0_;
  public static final int USER_ID_FIELD_NUMBER = 1;
  private long userId_ = 0L;
  /**
   * <code>int64 user_id = 1;</code>
   * @return The userId.
   */
  @java.lang.Override
  public long getUserId() {
    return userId_;
  }

  public static final int EMOTE_UPLOAD_SOURCE_FIELD_NUMBER = 2;
  private int emoteUploadSource_ = 0;
  /**
   * <code>optional .TikTok.EmoteUploadInfo.UserEmoteUploadSource emote_upload_source = 2;</code>
   * @return Whether the emoteUploadSource field is set.
   */
  @java.lang.Override public boolean hasEmoteUploadSource() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional .TikTok.EmoteUploadInfo.UserEmoteUploadSource emote_upload_source = 2;</code>
   * @return The enum numeric value on the wire for emoteUploadSource.
   */
  @java.lang.Override public int getEmoteUploadSourceValue() {
    return emoteUploadSource_;
  }
  /**
   * <code>optional .TikTok.EmoteUploadInfo.UserEmoteUploadSource emote_upload_source = 2;</code>
   * @return The emoteUploadSource.
   */
  @java.lang.Override public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.EmoteUploadInfo.UserEmoteUploadSource getEmoteUploadSource() {
    co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.EmoteUploadInfo.UserEmoteUploadSource result = co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.EmoteUploadInfo.UserEmoteUploadSource.forNumber(emoteUploadSource_);
    return result == null ? co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.EmoteUploadInfo.UserEmoteUploadSource.UNRECOGNIZED : result;
  }

  public static final int USER_INFO_FIELD_NUMBER = 3;
  private co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.User userInfo_;
  /**
   * <code>.TikTok.User user_info = 3;</code>
   * @return Whether the userInfo field is set.
   */
  @java.lang.Override
  public boolean hasUserInfo() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.TikTok.User user_info = 3;</code>
   * @return The userInfo.
   */
  @java.lang.Override
  public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.User getUserInfo() {
    return userInfo_ == null ? co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.User.getDefaultInstance() : userInfo_;
  }
  /**
   * <code>.TikTok.User user_info = 3;</code>
   */
  @java.lang.Override
  public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.UserOrBuilder getUserInfoOrBuilder() {
    return userInfo_ == null ? co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.User.getDefaultInstance() : userInfo_;
  }

  public static final int USER_ID_STR_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object userIdStr_ = "";
  /**
   * <code>string user_id_str = 4;</code>
   * @return The userIdStr.
   */
  @java.lang.Override
  public java.lang.String getUserIdStr() {
    java.lang.Object ref = userIdStr_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userIdStr_ = s;
      return s;
    }
  }
  /**
   * <code>string user_id_str = 4;</code>
   * @return The bytes for userIdStr.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUserIdStrBytes() {
    java.lang.Object ref = userIdStr_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userIdStr_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (userId_ != 0L) {
      output.writeInt64(1, userId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeEnum(2, emoteUploadSource_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(3, getUserInfo());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(userIdStr_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, userIdStr_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (userId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, userId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, emoteUploadSource_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getUserInfo());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(userIdStr_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, userIdStr_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.EmoteUploadInfo)) {
      return super.equals(obj);
    }
    co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.EmoteUploadInfo other = (co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.EmoteUploadInfo) obj;

    if (getUserId()
        != other.getUserId()) return false;
    if (hasEmoteUploadSource() != other.hasEmoteUploadSource()) return false;
    if (hasEmoteUploadSource()) {
      if (emoteUploadSource_ != other.emoteUploadSource_) return false;
    }
    if (hasUserInfo() != other.hasUserInfo()) return false;
    if (hasUserInfo()) {
      if (!getUserInfo()
          .equals(other.getUserInfo())) return false;
    }
    if (!getUserIdStr()
        .equals(other.getUserIdStr())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + USER_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUserId());
    if (hasEmoteUploadSource()) {
      hash = (37 * hash) + EMOTE_UPLOAD_SOURCE_FIELD_NUMBER;
      hash = (53 * hash) + emoteUploadSource_;
    }
    if (hasUserInfo()) {
      hash = (37 * hash) + USER_INFO_FIELD_NUMBER;
      hash = (53 * hash) + getUserInfo().hashCode();
    }
    hash = (37 * hash) + USER_ID_STR_FIELD_NUMBER;
    hash = (53 * hash) + getUserIdStr().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.EmoteUploadInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.EmoteUploadInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.EmoteUploadInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.EmoteUploadInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.EmoteUploadInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.EmoteUploadInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.EmoteUploadInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.EmoteUploadInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.EmoteUploadInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.EmoteUploadInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.EmoteUploadInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.EmoteUploadInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.EmoteUploadInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code TikTok.EmoteUploadInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:TikTok.EmoteUploadInfo)
      co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.EmoteUploadInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.Webcast.internal_static_TikTok_EmoteUploadInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.Webcast.internal_static_TikTok_EmoteUploadInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.EmoteUploadInfo.class, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.EmoteUploadInfo.Builder.class);
    }

    // Construct using co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.EmoteUploadInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetUserInfoFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      userId_ = 0L;
      emoteUploadSource_ = 0;
      userInfo_ = null;
      if (userInfoBuilder_ != null) {
        userInfoBuilder_.dispose();
        userInfoBuilder_ = null;
      }
      userIdStr_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.Webcast.internal_static_TikTok_EmoteUploadInfo_descriptor;
    }

    @java.lang.Override
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.EmoteUploadInfo getDefaultInstanceForType() {
      return co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.EmoteUploadInfo.getDefaultInstance();
    }

    @java.lang.Override
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.EmoteUploadInfo build() {
      co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.EmoteUploadInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.EmoteUploadInfo buildPartial() {
      co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.EmoteUploadInfo result = new co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.EmoteUploadInfo(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.EmoteUploadInfo result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.userId_ = userId_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.emoteUploadSource_ = emoteUploadSource_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.userInfo_ = userInfoBuilder_ == null
            ? userInfo_
            : userInfoBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.userIdStr_ = userIdStr_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.EmoteUploadInfo) {
        return mergeFrom((co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.EmoteUploadInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.EmoteUploadInfo other) {
      if (other == co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.EmoteUploadInfo.getDefaultInstance()) return this;
      if (other.getUserId() != 0L) {
        setUserId(other.getUserId());
      }
      if (other.hasEmoteUploadSource()) {
        setEmoteUploadSourceValue(other.getEmoteUploadSourceValue());
      }
      if (other.hasUserInfo()) {
        mergeUserInfo(other.getUserInfo());
      }
      if (!other.getUserIdStr().isEmpty()) {
        userIdStr_ = other.userIdStr_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              userId_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              emoteUploadSource_ = input.readEnum();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              input.readMessage(
                  internalGetUserInfoFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              userIdStr_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long userId_ ;
    /**
     * <code>int64 user_id = 1;</code>
     * @return The userId.
     */
    @java.lang.Override
    public long getUserId() {
      return userId_;
    }
    /**
     * <code>int64 user_id = 1;</code>
     * @param value The userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserId(long value) {

      userId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 user_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      userId_ = 0L;
      onChanged();
      return this;
    }

    private int emoteUploadSource_ = 0;
    /**
     * <code>optional .TikTok.EmoteUploadInfo.UserEmoteUploadSource emote_upload_source = 2;</code>
     * @return Whether the emoteUploadSource field is set.
     */
    @java.lang.Override public boolean hasEmoteUploadSource() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .TikTok.EmoteUploadInfo.UserEmoteUploadSource emote_upload_source = 2;</code>
     * @return The enum numeric value on the wire for emoteUploadSource.
     */
    @java.lang.Override public int getEmoteUploadSourceValue() {
      return emoteUploadSource_;
    }
    /**
     * <code>optional .TikTok.EmoteUploadInfo.UserEmoteUploadSource emote_upload_source = 2;</code>
     * @param value The enum numeric value on the wire for emoteUploadSource to set.
     * @return This builder for chaining.
     */
    public Builder setEmoteUploadSourceValue(int value) {
      emoteUploadSource_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional .TikTok.EmoteUploadInfo.UserEmoteUploadSource emote_upload_source = 2;</code>
     * @return The emoteUploadSource.
     */
    @java.lang.Override
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.EmoteUploadInfo.UserEmoteUploadSource getEmoteUploadSource() {
      co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.EmoteUploadInfo.UserEmoteUploadSource result = co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.EmoteUploadInfo.UserEmoteUploadSource.forNumber(emoteUploadSource_);
      return result == null ? co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.EmoteUploadInfo.UserEmoteUploadSource.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .TikTok.EmoteUploadInfo.UserEmoteUploadSource emote_upload_source = 2;</code>
     * @param value The emoteUploadSource to set.
     * @return This builder for chaining.
     */
    public Builder setEmoteUploadSource(co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.EmoteUploadInfo.UserEmoteUploadSource value) {
      if (value == null) { throw new NullPointerException(); }
      bitField0_ |= 0x00000002;
      emoteUploadSource_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .TikTok.EmoteUploadInfo.UserEmoteUploadSource emote_upload_source = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearEmoteUploadSource() {
      bitField0_ = (bitField0_ & ~0x00000002);
      emoteUploadSource_ = 0;
      onChanged();
      return this;
    }

    private co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.User userInfo_;
    private com.google.protobuf.SingleFieldBuilder<
        co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.User, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.User.Builder, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.UserOrBuilder> userInfoBuilder_;
    /**
     * <code>.TikTok.User user_info = 3;</code>
     * @return Whether the userInfo field is set.
     */
    public boolean hasUserInfo() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.TikTok.User user_info = 3;</code>
     * @return The userInfo.
     */
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.User getUserInfo() {
      if (userInfoBuilder_ == null) {
        return userInfo_ == null ? co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.User.getDefaultInstance() : userInfo_;
      } else {
        return userInfoBuilder_.getMessage();
      }
    }
    /**
     * <code>.TikTok.User user_info = 3;</code>
     */
    public Builder setUserInfo(co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.User value) {
      if (userInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        userInfo_ = value;
      } else {
        userInfoBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.TikTok.User user_info = 3;</code>
     */
    public Builder setUserInfo(
        co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.User.Builder builderForValue) {
      if (userInfoBuilder_ == null) {
        userInfo_ = builderForValue.build();
      } else {
        userInfoBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.TikTok.User user_info = 3;</code>
     */
    public Builder mergeUserInfo(co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.User value) {
      if (userInfoBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          userInfo_ != null &&
          userInfo_ != co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.User.getDefaultInstance()) {
          getUserInfoBuilder().mergeFrom(value);
        } else {
          userInfo_ = value;
        }
      } else {
        userInfoBuilder_.mergeFrom(value);
      }
      if (userInfo_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.TikTok.User user_info = 3;</code>
     */
    public Builder clearUserInfo() {
      bitField0_ = (bitField0_ & ~0x00000004);
      userInfo_ = null;
      if (userInfoBuilder_ != null) {
        userInfoBuilder_.dispose();
        userInfoBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.TikTok.User user_info = 3;</code>
     */
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.User.Builder getUserInfoBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return internalGetUserInfoFieldBuilder().getBuilder();
    }
    /**
     * <code>.TikTok.User user_info = 3;</code>
     */
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.UserOrBuilder getUserInfoOrBuilder() {
      if (userInfoBuilder_ != null) {
        return userInfoBuilder_.getMessageOrBuilder();
      } else {
        return userInfo_ == null ?
            co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.User.getDefaultInstance() : userInfo_;
      }
    }
    /**
     * <code>.TikTok.User user_info = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.User, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.User.Builder, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.UserOrBuilder> 
        internalGetUserInfoFieldBuilder() {
      if (userInfoBuilder_ == null) {
        userInfoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.User, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.User.Builder, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.UserOrBuilder>(
                getUserInfo(),
                getParentForChildren(),
                isClean());
        userInfo_ = null;
      }
      return userInfoBuilder_;
    }

    private java.lang.Object userIdStr_ = "";
    /**
     * <code>string user_id_str = 4;</code>
     * @return The userIdStr.
     */
    public java.lang.String getUserIdStr() {
      java.lang.Object ref = userIdStr_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userIdStr_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string user_id_str = 4;</code>
     * @return The bytes for userIdStr.
     */
    public com.google.protobuf.ByteString
        getUserIdStrBytes() {
      java.lang.Object ref = userIdStr_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userIdStr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string user_id_str = 4;</code>
     * @param value The userIdStr to set.
     * @return This builder for chaining.
     */
    public Builder setUserIdStr(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      userIdStr_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string user_id_str = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserIdStr() {
      userIdStr_ = getDefaultInstance().getUserIdStr();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string user_id_str = 4;</code>
     * @param value The bytes for userIdStr to set.
     * @return This builder for chaining.
     */
    public Builder setUserIdStrBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      userIdStr_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:TikTok.EmoteUploadInfo)
  }

  // @@protoc_insertion_point(class_scope:TikTok.EmoteUploadInfo)
  private static final co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.EmoteUploadInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.EmoteUploadInfo();
  }

  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.EmoteUploadInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EmoteUploadInfo>
      PARSER = new com.google.protobuf.AbstractParser<EmoteUploadInfo>() {
    @java.lang.Override
    public EmoteUploadInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<EmoteUploadInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EmoteUploadInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.EmoteUploadInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

