// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: webcast.proto
// Protobuf Java Version: 4.32.0

package co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast;

@com.google.protobuf.Generated
public interface WebcastLinkMicBattlePunishFinishOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TikTok.WebcastLinkMicBattlePunishFinish)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.TikTok.CommonMessageData common = 1;</code>
   * @return Whether the common field is set.
   */
  boolean hasCommon();
  /**
   * <code>.TikTok.CommonMessageData common = 1;</code>
   * @return The common.
   */
  co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.CommonMessageData getCommon();
  /**
   * <code>.TikTok.CommonMessageData common = 1;</code>
   */
  co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.CommonMessageDataOrBuilder getCommonOrBuilder();

  /**
   * <code>int64 channel_id = 2;</code>
   * @return The channelId.
   */
  long getChannelId();

  /**
   * <code>int64 op_uid = 3;</code>
   * @return The opUid.
   */
  long getOpUid();

  /**
   * <code>.TikTok.Reason reason = 4;</code>
   * @return The enum numeric value on the wire for reason.
   */
  int getReasonValue();
  /**
   * <code>.TikTok.Reason reason = 4;</code>
   * @return The reason.
   */
  co.casterlabs.sdk.tiktok.unsupported.types.protobuf.enums.Reason getReason();

  /**
   * <code>int64 battle_id = 5;</code>
   * @return The battleId.
   */
  long getBattleId();

  /**
   * <code>.TikTok.BattleSetting battle_settings = 6;</code>
   * @return Whether the battleSettings field is set.
   */
  boolean hasBattleSettings();
  /**
   * <code>.TikTok.BattleSetting battle_settings = 6;</code>
   * @return The battleSettings.
   */
  co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.BattleSetting getBattleSettings();
  /**
   * <code>.TikTok.BattleSetting battle_settings = 6;</code>
   */
  co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.BattleSettingOrBuilder getBattleSettingsOrBuilder();
}
