// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: webcast.proto
// Protobuf Java Version: 4.32.0

package co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast;

/**
 * Protobuf type {@code TikTok.WebcastUnauthorizedMemberMessage}
 */
@com.google.protobuf.Generated
public final class WebcastUnauthorizedMemberMessage extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:TikTok.WebcastUnauthorizedMemberMessage)
    WebcastUnauthorizedMemberMessageOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      WebcastUnauthorizedMemberMessage.class.getName());
  }
  // Use WebcastUnauthorizedMemberMessage.newBuilder() to construct.
  private WebcastUnauthorizedMemberMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private WebcastUnauthorizedMemberMessage() {
    nickName_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.Webcast.internal_static_TikTok_WebcastUnauthorizedMemberMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.Webcast.internal_static_TikTok_WebcastUnauthorizedMemberMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.WebcastUnauthorizedMemberMessage.class, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.WebcastUnauthorizedMemberMessage.Builder.class);
  }

  private int bitField0_;
  public static final int COMMON_FIELD_NUMBER = 1;
  private co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.CommonMessageData common_;
  /**
   * <code>.TikTok.CommonMessageData common = 1;</code>
   * @return Whether the common field is set.
   */
  @java.lang.Override
  public boolean hasCommon() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.TikTok.CommonMessageData common = 1;</code>
   * @return The common.
   */
  @java.lang.Override
  public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.CommonMessageData getCommon() {
    return common_ == null ? co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.CommonMessageData.getDefaultInstance() : common_;
  }
  /**
   * <code>.TikTok.CommonMessageData common = 1;</code>
   */
  @java.lang.Override
  public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.CommonMessageDataOrBuilder getCommonOrBuilder() {
    return common_ == null ? co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.CommonMessageData.getDefaultInstance() : common_;
  }

  public static final int ACTION_FIELD_NUMBER = 2;
  private int action_ = 0;
  /**
   * <code>int32 action = 2;</code>
   * @return The action.
   */
  @java.lang.Override
  public int getAction() {
    return action_;
  }

  public static final int NICKNAMEPREFIX_FIELD_NUMBER = 3;
  private co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Text nickNamePrefix_;
  /**
   * <code>.TikTok.Text nickNamePrefix = 3;</code>
   * @return Whether the nickNamePrefix field is set.
   */
  @java.lang.Override
  public boolean hasNickNamePrefix() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.TikTok.Text nickNamePrefix = 3;</code>
   * @return The nickNamePrefix.
   */
  @java.lang.Override
  public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Text getNickNamePrefix() {
    return nickNamePrefix_ == null ? co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Text.getDefaultInstance() : nickNamePrefix_;
  }
  /**
   * <code>.TikTok.Text nickNamePrefix = 3;</code>
   */
  @java.lang.Override
  public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.TextOrBuilder getNickNamePrefixOrBuilder() {
    return nickNamePrefix_ == null ? co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Text.getDefaultInstance() : nickNamePrefix_;
  }

  public static final int NICKNAME_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object nickName_ = "";
  /**
   * <code>string nickName = 4;</code>
   * @return The nickName.
   */
  @java.lang.Override
  public java.lang.String getNickName() {
    java.lang.Object ref = nickName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nickName_ = s;
      return s;
    }
  }
  /**
   * <code>string nickName = 4;</code>
   * @return The bytes for nickName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNickNameBytes() {
    java.lang.Object ref = nickName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nickName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ENTERTEXT_FIELD_NUMBER = 5;
  private co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Text enterText_;
  /**
   * <code>.TikTok.Text enterText = 5;</code>
   * @return Whether the enterText field is set.
   */
  @java.lang.Override
  public boolean hasEnterText() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>.TikTok.Text enterText = 5;</code>
   * @return The enterText.
   */
  @java.lang.Override
  public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Text getEnterText() {
    return enterText_ == null ? co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Text.getDefaultInstance() : enterText_;
  }
  /**
   * <code>.TikTok.Text enterText = 5;</code>
   */
  @java.lang.Override
  public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.TextOrBuilder getEnterTextOrBuilder() {
    return enterText_ == null ? co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Text.getDefaultInstance() : enterText_;
  }

  public static final int PUBLIC_AREA_COMMON_FIELD_NUMBER = 6;
  private co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PublicAreaMessageCommon publicAreaCommon_;
  /**
   * <code>.TikTok.PublicAreaMessageCommon public_area_common = 6;</code>
   * @return Whether the publicAreaCommon field is set.
   */
  @java.lang.Override
  public boolean hasPublicAreaCommon() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>.TikTok.PublicAreaMessageCommon public_area_common = 6;</code>
   * @return The publicAreaCommon.
   */
  @java.lang.Override
  public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PublicAreaMessageCommon getPublicAreaCommon() {
    return publicAreaCommon_ == null ? co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PublicAreaMessageCommon.getDefaultInstance() : publicAreaCommon_;
  }
  /**
   * <code>.TikTok.PublicAreaMessageCommon public_area_common = 6;</code>
   */
  @java.lang.Override
  public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PublicAreaMessageCommonOrBuilder getPublicAreaCommonOrBuilder() {
    return publicAreaCommon_ == null ? co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PublicAreaMessageCommon.getDefaultInstance() : publicAreaCommon_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getCommon());
    }
    if (action_ != 0) {
      output.writeInt32(2, action_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(3, getNickNamePrefix());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(nickName_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, nickName_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(5, getEnterText());
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeMessage(6, getPublicAreaCommon());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getCommon());
    }
    if (action_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, action_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getNickNamePrefix());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(nickName_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, nickName_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getEnterText());
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getPublicAreaCommon());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.WebcastUnauthorizedMemberMessage)) {
      return super.equals(obj);
    }
    co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.WebcastUnauthorizedMemberMessage other = (co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.WebcastUnauthorizedMemberMessage) obj;

    if (hasCommon() != other.hasCommon()) return false;
    if (hasCommon()) {
      if (!getCommon()
          .equals(other.getCommon())) return false;
    }
    if (getAction()
        != other.getAction()) return false;
    if (hasNickNamePrefix() != other.hasNickNamePrefix()) return false;
    if (hasNickNamePrefix()) {
      if (!getNickNamePrefix()
          .equals(other.getNickNamePrefix())) return false;
    }
    if (!getNickName()
        .equals(other.getNickName())) return false;
    if (hasEnterText() != other.hasEnterText()) return false;
    if (hasEnterText()) {
      if (!getEnterText()
          .equals(other.getEnterText())) return false;
    }
    if (hasPublicAreaCommon() != other.hasPublicAreaCommon()) return false;
    if (hasPublicAreaCommon()) {
      if (!getPublicAreaCommon()
          .equals(other.getPublicAreaCommon())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasCommon()) {
      hash = (37 * hash) + COMMON_FIELD_NUMBER;
      hash = (53 * hash) + getCommon().hashCode();
    }
    hash = (37 * hash) + ACTION_FIELD_NUMBER;
    hash = (53 * hash) + getAction();
    if (hasNickNamePrefix()) {
      hash = (37 * hash) + NICKNAMEPREFIX_FIELD_NUMBER;
      hash = (53 * hash) + getNickNamePrefix().hashCode();
    }
    hash = (37 * hash) + NICKNAME_FIELD_NUMBER;
    hash = (53 * hash) + getNickName().hashCode();
    if (hasEnterText()) {
      hash = (37 * hash) + ENTERTEXT_FIELD_NUMBER;
      hash = (53 * hash) + getEnterText().hashCode();
    }
    if (hasPublicAreaCommon()) {
      hash = (37 * hash) + PUBLIC_AREA_COMMON_FIELD_NUMBER;
      hash = (53 * hash) + getPublicAreaCommon().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.WebcastUnauthorizedMemberMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.WebcastUnauthorizedMemberMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.WebcastUnauthorizedMemberMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.WebcastUnauthorizedMemberMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.WebcastUnauthorizedMemberMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.WebcastUnauthorizedMemberMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.WebcastUnauthorizedMemberMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.WebcastUnauthorizedMemberMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.WebcastUnauthorizedMemberMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.WebcastUnauthorizedMemberMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.WebcastUnauthorizedMemberMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.WebcastUnauthorizedMemberMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.WebcastUnauthorizedMemberMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code TikTok.WebcastUnauthorizedMemberMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:TikTok.WebcastUnauthorizedMemberMessage)
      co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.WebcastUnauthorizedMemberMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.Webcast.internal_static_TikTok_WebcastUnauthorizedMemberMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.Webcast.internal_static_TikTok_WebcastUnauthorizedMemberMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.WebcastUnauthorizedMemberMessage.class, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.WebcastUnauthorizedMemberMessage.Builder.class);
    }

    // Construct using co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.WebcastUnauthorizedMemberMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetCommonFieldBuilder();
        internalGetNickNamePrefixFieldBuilder();
        internalGetEnterTextFieldBuilder();
        internalGetPublicAreaCommonFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      common_ = null;
      if (commonBuilder_ != null) {
        commonBuilder_.dispose();
        commonBuilder_ = null;
      }
      action_ = 0;
      nickNamePrefix_ = null;
      if (nickNamePrefixBuilder_ != null) {
        nickNamePrefixBuilder_.dispose();
        nickNamePrefixBuilder_ = null;
      }
      nickName_ = "";
      enterText_ = null;
      if (enterTextBuilder_ != null) {
        enterTextBuilder_.dispose();
        enterTextBuilder_ = null;
      }
      publicAreaCommon_ = null;
      if (publicAreaCommonBuilder_ != null) {
        publicAreaCommonBuilder_.dispose();
        publicAreaCommonBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.Webcast.internal_static_TikTok_WebcastUnauthorizedMemberMessage_descriptor;
    }

    @java.lang.Override
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.WebcastUnauthorizedMemberMessage getDefaultInstanceForType() {
      return co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.WebcastUnauthorizedMemberMessage.getDefaultInstance();
    }

    @java.lang.Override
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.WebcastUnauthorizedMemberMessage build() {
      co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.WebcastUnauthorizedMemberMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.WebcastUnauthorizedMemberMessage buildPartial() {
      co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.WebcastUnauthorizedMemberMessage result = new co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.WebcastUnauthorizedMemberMessage(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.WebcastUnauthorizedMemberMessage result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.common_ = commonBuilder_ == null
            ? common_
            : commonBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.action_ = action_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.nickNamePrefix_ = nickNamePrefixBuilder_ == null
            ? nickNamePrefix_
            : nickNamePrefixBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.nickName_ = nickName_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.enterText_ = enterTextBuilder_ == null
            ? enterText_
            : enterTextBuilder_.build();
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.publicAreaCommon_ = publicAreaCommonBuilder_ == null
            ? publicAreaCommon_
            : publicAreaCommonBuilder_.build();
        to_bitField0_ |= 0x00000008;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.WebcastUnauthorizedMemberMessage) {
        return mergeFrom((co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.WebcastUnauthorizedMemberMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.WebcastUnauthorizedMemberMessage other) {
      if (other == co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.WebcastUnauthorizedMemberMessage.getDefaultInstance()) return this;
      if (other.hasCommon()) {
        mergeCommon(other.getCommon());
      }
      if (other.getAction() != 0) {
        setAction(other.getAction());
      }
      if (other.hasNickNamePrefix()) {
        mergeNickNamePrefix(other.getNickNamePrefix());
      }
      if (!other.getNickName().isEmpty()) {
        nickName_ = other.nickName_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.hasEnterText()) {
        mergeEnterText(other.getEnterText());
      }
      if (other.hasPublicAreaCommon()) {
        mergePublicAreaCommon(other.getPublicAreaCommon());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetCommonFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              action_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              input.readMessage(
                  internalGetNickNamePrefixFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              nickName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  internalGetEnterTextFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              input.readMessage(
                  internalGetPublicAreaCommonFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.CommonMessageData common_;
    private com.google.protobuf.SingleFieldBuilder<
        co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.CommonMessageData, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.CommonMessageData.Builder, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.CommonMessageDataOrBuilder> commonBuilder_;
    /**
     * <code>.TikTok.CommonMessageData common = 1;</code>
     * @return Whether the common field is set.
     */
    public boolean hasCommon() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.TikTok.CommonMessageData common = 1;</code>
     * @return The common.
     */
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.CommonMessageData getCommon() {
      if (commonBuilder_ == null) {
        return common_ == null ? co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.CommonMessageData.getDefaultInstance() : common_;
      } else {
        return commonBuilder_.getMessage();
      }
    }
    /**
     * <code>.TikTok.CommonMessageData common = 1;</code>
     */
    public Builder setCommon(co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.CommonMessageData value) {
      if (commonBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        common_ = value;
      } else {
        commonBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.TikTok.CommonMessageData common = 1;</code>
     */
    public Builder setCommon(
        co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.CommonMessageData.Builder builderForValue) {
      if (commonBuilder_ == null) {
        common_ = builderForValue.build();
      } else {
        commonBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.TikTok.CommonMessageData common = 1;</code>
     */
    public Builder mergeCommon(co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.CommonMessageData value) {
      if (commonBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          common_ != null &&
          common_ != co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.CommonMessageData.getDefaultInstance()) {
          getCommonBuilder().mergeFrom(value);
        } else {
          common_ = value;
        }
      } else {
        commonBuilder_.mergeFrom(value);
      }
      if (common_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.TikTok.CommonMessageData common = 1;</code>
     */
    public Builder clearCommon() {
      bitField0_ = (bitField0_ & ~0x00000001);
      common_ = null;
      if (commonBuilder_ != null) {
        commonBuilder_.dispose();
        commonBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.TikTok.CommonMessageData common = 1;</code>
     */
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.CommonMessageData.Builder getCommonBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return internalGetCommonFieldBuilder().getBuilder();
    }
    /**
     * <code>.TikTok.CommonMessageData common = 1;</code>
     */
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.CommonMessageDataOrBuilder getCommonOrBuilder() {
      if (commonBuilder_ != null) {
        return commonBuilder_.getMessageOrBuilder();
      } else {
        return common_ == null ?
            co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.CommonMessageData.getDefaultInstance() : common_;
      }
    }
    /**
     * <code>.TikTok.CommonMessageData common = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.CommonMessageData, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.CommonMessageData.Builder, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.CommonMessageDataOrBuilder> 
        internalGetCommonFieldBuilder() {
      if (commonBuilder_ == null) {
        commonBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.CommonMessageData, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.CommonMessageData.Builder, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.CommonMessageDataOrBuilder>(
                getCommon(),
                getParentForChildren(),
                isClean());
        common_ = null;
      }
      return commonBuilder_;
    }

    private int action_ ;
    /**
     * <code>int32 action = 2;</code>
     * @return The action.
     */
    @java.lang.Override
    public int getAction() {
      return action_;
    }
    /**
     * <code>int32 action = 2;</code>
     * @param value The action to set.
     * @return This builder for chaining.
     */
    public Builder setAction(int value) {

      action_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 action = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAction() {
      bitField0_ = (bitField0_ & ~0x00000002);
      action_ = 0;
      onChanged();
      return this;
    }

    private co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Text nickNamePrefix_;
    private com.google.protobuf.SingleFieldBuilder<
        co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Text, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Text.Builder, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.TextOrBuilder> nickNamePrefixBuilder_;
    /**
     * <code>.TikTok.Text nickNamePrefix = 3;</code>
     * @return Whether the nickNamePrefix field is set.
     */
    public boolean hasNickNamePrefix() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.TikTok.Text nickNamePrefix = 3;</code>
     * @return The nickNamePrefix.
     */
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Text getNickNamePrefix() {
      if (nickNamePrefixBuilder_ == null) {
        return nickNamePrefix_ == null ? co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Text.getDefaultInstance() : nickNamePrefix_;
      } else {
        return nickNamePrefixBuilder_.getMessage();
      }
    }
    /**
     * <code>.TikTok.Text nickNamePrefix = 3;</code>
     */
    public Builder setNickNamePrefix(co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Text value) {
      if (nickNamePrefixBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        nickNamePrefix_ = value;
      } else {
        nickNamePrefixBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.TikTok.Text nickNamePrefix = 3;</code>
     */
    public Builder setNickNamePrefix(
        co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Text.Builder builderForValue) {
      if (nickNamePrefixBuilder_ == null) {
        nickNamePrefix_ = builderForValue.build();
      } else {
        nickNamePrefixBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.TikTok.Text nickNamePrefix = 3;</code>
     */
    public Builder mergeNickNamePrefix(co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Text value) {
      if (nickNamePrefixBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          nickNamePrefix_ != null &&
          nickNamePrefix_ != co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Text.getDefaultInstance()) {
          getNickNamePrefixBuilder().mergeFrom(value);
        } else {
          nickNamePrefix_ = value;
        }
      } else {
        nickNamePrefixBuilder_.mergeFrom(value);
      }
      if (nickNamePrefix_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.TikTok.Text nickNamePrefix = 3;</code>
     */
    public Builder clearNickNamePrefix() {
      bitField0_ = (bitField0_ & ~0x00000004);
      nickNamePrefix_ = null;
      if (nickNamePrefixBuilder_ != null) {
        nickNamePrefixBuilder_.dispose();
        nickNamePrefixBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.TikTok.Text nickNamePrefix = 3;</code>
     */
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Text.Builder getNickNamePrefixBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return internalGetNickNamePrefixFieldBuilder().getBuilder();
    }
    /**
     * <code>.TikTok.Text nickNamePrefix = 3;</code>
     */
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.TextOrBuilder getNickNamePrefixOrBuilder() {
      if (nickNamePrefixBuilder_ != null) {
        return nickNamePrefixBuilder_.getMessageOrBuilder();
      } else {
        return nickNamePrefix_ == null ?
            co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Text.getDefaultInstance() : nickNamePrefix_;
      }
    }
    /**
     * <code>.TikTok.Text nickNamePrefix = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Text, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Text.Builder, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.TextOrBuilder> 
        internalGetNickNamePrefixFieldBuilder() {
      if (nickNamePrefixBuilder_ == null) {
        nickNamePrefixBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Text, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Text.Builder, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.TextOrBuilder>(
                getNickNamePrefix(),
                getParentForChildren(),
                isClean());
        nickNamePrefix_ = null;
      }
      return nickNamePrefixBuilder_;
    }

    private java.lang.Object nickName_ = "";
    /**
     * <code>string nickName = 4;</code>
     * @return The nickName.
     */
    public java.lang.String getNickName() {
      java.lang.Object ref = nickName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nickName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string nickName = 4;</code>
     * @return The bytes for nickName.
     */
    public com.google.protobuf.ByteString
        getNickNameBytes() {
      java.lang.Object ref = nickName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nickName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string nickName = 4;</code>
     * @param value The nickName to set.
     * @return This builder for chaining.
     */
    public Builder setNickName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      nickName_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string nickName = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearNickName() {
      nickName_ = getDefaultInstance().getNickName();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string nickName = 4;</code>
     * @param value The bytes for nickName to set.
     * @return This builder for chaining.
     */
    public Builder setNickNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      nickName_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Text enterText_;
    private com.google.protobuf.SingleFieldBuilder<
        co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Text, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Text.Builder, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.TextOrBuilder> enterTextBuilder_;
    /**
     * <code>.TikTok.Text enterText = 5;</code>
     * @return Whether the enterText field is set.
     */
    public boolean hasEnterText() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>.TikTok.Text enterText = 5;</code>
     * @return The enterText.
     */
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Text getEnterText() {
      if (enterTextBuilder_ == null) {
        return enterText_ == null ? co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Text.getDefaultInstance() : enterText_;
      } else {
        return enterTextBuilder_.getMessage();
      }
    }
    /**
     * <code>.TikTok.Text enterText = 5;</code>
     */
    public Builder setEnterText(co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Text value) {
      if (enterTextBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        enterText_ = value;
      } else {
        enterTextBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.TikTok.Text enterText = 5;</code>
     */
    public Builder setEnterText(
        co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Text.Builder builderForValue) {
      if (enterTextBuilder_ == null) {
        enterText_ = builderForValue.build();
      } else {
        enterTextBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.TikTok.Text enterText = 5;</code>
     */
    public Builder mergeEnterText(co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Text value) {
      if (enterTextBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          enterText_ != null &&
          enterText_ != co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Text.getDefaultInstance()) {
          getEnterTextBuilder().mergeFrom(value);
        } else {
          enterText_ = value;
        }
      } else {
        enterTextBuilder_.mergeFrom(value);
      }
      if (enterText_ != null) {
        bitField0_ |= 0x00000010;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.TikTok.Text enterText = 5;</code>
     */
    public Builder clearEnterText() {
      bitField0_ = (bitField0_ & ~0x00000010);
      enterText_ = null;
      if (enterTextBuilder_ != null) {
        enterTextBuilder_.dispose();
        enterTextBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.TikTok.Text enterText = 5;</code>
     */
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Text.Builder getEnterTextBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return internalGetEnterTextFieldBuilder().getBuilder();
    }
    /**
     * <code>.TikTok.Text enterText = 5;</code>
     */
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.TextOrBuilder getEnterTextOrBuilder() {
      if (enterTextBuilder_ != null) {
        return enterTextBuilder_.getMessageOrBuilder();
      } else {
        return enterText_ == null ?
            co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Text.getDefaultInstance() : enterText_;
      }
    }
    /**
     * <code>.TikTok.Text enterText = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Text, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Text.Builder, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.TextOrBuilder> 
        internalGetEnterTextFieldBuilder() {
      if (enterTextBuilder_ == null) {
        enterTextBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Text, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Text.Builder, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.TextOrBuilder>(
                getEnterText(),
                getParentForChildren(),
                isClean());
        enterText_ = null;
      }
      return enterTextBuilder_;
    }

    private co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PublicAreaMessageCommon publicAreaCommon_;
    private com.google.protobuf.SingleFieldBuilder<
        co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PublicAreaMessageCommon, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PublicAreaMessageCommon.Builder, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PublicAreaMessageCommonOrBuilder> publicAreaCommonBuilder_;
    /**
     * <code>.TikTok.PublicAreaMessageCommon public_area_common = 6;</code>
     * @return Whether the publicAreaCommon field is set.
     */
    public boolean hasPublicAreaCommon() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>.TikTok.PublicAreaMessageCommon public_area_common = 6;</code>
     * @return The publicAreaCommon.
     */
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PublicAreaMessageCommon getPublicAreaCommon() {
      if (publicAreaCommonBuilder_ == null) {
        return publicAreaCommon_ == null ? co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PublicAreaMessageCommon.getDefaultInstance() : publicAreaCommon_;
      } else {
        return publicAreaCommonBuilder_.getMessage();
      }
    }
    /**
     * <code>.TikTok.PublicAreaMessageCommon public_area_common = 6;</code>
     */
    public Builder setPublicAreaCommon(co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PublicAreaMessageCommon value) {
      if (publicAreaCommonBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        publicAreaCommon_ = value;
      } else {
        publicAreaCommonBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.TikTok.PublicAreaMessageCommon public_area_common = 6;</code>
     */
    public Builder setPublicAreaCommon(
        co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PublicAreaMessageCommon.Builder builderForValue) {
      if (publicAreaCommonBuilder_ == null) {
        publicAreaCommon_ = builderForValue.build();
      } else {
        publicAreaCommonBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.TikTok.PublicAreaMessageCommon public_area_common = 6;</code>
     */
    public Builder mergePublicAreaCommon(co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PublicAreaMessageCommon value) {
      if (publicAreaCommonBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0) &&
          publicAreaCommon_ != null &&
          publicAreaCommon_ != co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PublicAreaMessageCommon.getDefaultInstance()) {
          getPublicAreaCommonBuilder().mergeFrom(value);
        } else {
          publicAreaCommon_ = value;
        }
      } else {
        publicAreaCommonBuilder_.mergeFrom(value);
      }
      if (publicAreaCommon_ != null) {
        bitField0_ |= 0x00000020;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.TikTok.PublicAreaMessageCommon public_area_common = 6;</code>
     */
    public Builder clearPublicAreaCommon() {
      bitField0_ = (bitField0_ & ~0x00000020);
      publicAreaCommon_ = null;
      if (publicAreaCommonBuilder_ != null) {
        publicAreaCommonBuilder_.dispose();
        publicAreaCommonBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.TikTok.PublicAreaMessageCommon public_area_common = 6;</code>
     */
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PublicAreaMessageCommon.Builder getPublicAreaCommonBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return internalGetPublicAreaCommonFieldBuilder().getBuilder();
    }
    /**
     * <code>.TikTok.PublicAreaMessageCommon public_area_common = 6;</code>
     */
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PublicAreaMessageCommonOrBuilder getPublicAreaCommonOrBuilder() {
      if (publicAreaCommonBuilder_ != null) {
        return publicAreaCommonBuilder_.getMessageOrBuilder();
      } else {
        return publicAreaCommon_ == null ?
            co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PublicAreaMessageCommon.getDefaultInstance() : publicAreaCommon_;
      }
    }
    /**
     * <code>.TikTok.PublicAreaMessageCommon public_area_common = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PublicAreaMessageCommon, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PublicAreaMessageCommon.Builder, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PublicAreaMessageCommonOrBuilder> 
        internalGetPublicAreaCommonFieldBuilder() {
      if (publicAreaCommonBuilder_ == null) {
        publicAreaCommonBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PublicAreaMessageCommon, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PublicAreaMessageCommon.Builder, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PublicAreaMessageCommonOrBuilder>(
                getPublicAreaCommon(),
                getParentForChildren(),
                isClean());
        publicAreaCommon_ = null;
      }
      return publicAreaCommonBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:TikTok.WebcastUnauthorizedMemberMessage)
  }

  // @@protoc_insertion_point(class_scope:TikTok.WebcastUnauthorizedMemberMessage)
  private static final co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.WebcastUnauthorizedMemberMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.WebcastUnauthorizedMemberMessage();
  }

  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.WebcastUnauthorizedMemberMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WebcastUnauthorizedMemberMessage>
      PARSER = new com.google.protobuf.AbstractParser<WebcastUnauthorizedMemberMessage>() {
    @java.lang.Override
    public WebcastUnauthorizedMemberMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<WebcastUnauthorizedMemberMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WebcastUnauthorizedMemberMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.WebcastUnauthorizedMemberMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

