// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: webcast.proto
// Protobuf Java Version: 4.32.0

package co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast;

@com.google.protobuf.Generated
public interface WebcastEnvelopeMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TikTok.WebcastEnvelopeMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.TikTok.CommonMessageData common = 1;</code>
   * @return Whether the common field is set.
   */
  boolean hasCommon();
  /**
   * <code>.TikTok.CommonMessageData common = 1;</code>
   * @return The common.
   */
  co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.CommonMessageData getCommon();
  /**
   * <code>.TikTok.CommonMessageData common = 1;</code>
   */
  co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.CommonMessageDataOrBuilder getCommonOrBuilder();

  /**
   * <code>.TikTok.WebcastEnvelopeMessage.EnvelopeInfo envelopeInfo = 2;</code>
   * @return Whether the envelopeInfo field is set.
   */
  boolean hasEnvelopeInfo();
  /**
   * <code>.TikTok.WebcastEnvelopeMessage.EnvelopeInfo envelopeInfo = 2;</code>
   * @return The envelopeInfo.
   */
  co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.WebcastEnvelopeMessage.EnvelopeInfo getEnvelopeInfo();
  /**
   * <code>.TikTok.WebcastEnvelopeMessage.EnvelopeInfo envelopeInfo = 2;</code>
   */
  co.casterlabs.sdk.tiktok.unsupported.types.protobuf.webcast.WebcastEnvelopeMessage.EnvelopeInfoOrBuilder getEnvelopeInfoOrBuilder();

  /**
   * <code>.TikTok.EnvelopeDisplay display = 3;</code>
   * @return The enum numeric value on the wire for display.
   */
  int getDisplayValue();
  /**
   * <code>.TikTok.EnvelopeDisplay display = 3;</code>
   * @return The display.
   */
  co.casterlabs.sdk.tiktok.unsupported.types.protobuf.enums.EnvelopeDisplay getDisplay();
}
