// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: data.proto
// Protobuf Java Version: 4.32.0

package co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data;

@com.google.protobuf.Generated
public interface GroupChannelUserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TikTok.GroupChannelUser)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 channelId = 1;</code>
   * @return The channelId.
   */
  long getChannelId();

  /**
   * <code>.TikTok.GroupStatus status = 2;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.TikTok.GroupStatus status = 2;</code>
   * @return The status.
   */
  co.casterlabs.sdk.tiktok.unsupported.types.protobuf.enums.GroupStatus getStatus();

  /**
   * <code>.TikTok.TextType type = 3;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.TikTok.TextType type = 3;</code>
   * @return The type.
   */
  co.casterlabs.sdk.tiktok.unsupported.types.protobuf.enums.TextType getType();

  /**
   * <code>.TikTok.AllListUser allUser = 4;</code>
   * @return Whether the allUser field is set.
   */
  boolean hasAllUser();
  /**
   * <code>.TikTok.AllListUser allUser = 4;</code>
   * @return The allUser.
   */
  co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.AllListUser getAllUser();
  /**
   * <code>.TikTok.AllListUser allUser = 4;</code>
   */
  co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.AllListUserOrBuilder getAllUserOrBuilder();

  /**
   * <code>int64 joinTime = 5;</code>
   * @return The joinTime.
   */
  long getJoinTime();

  /**
   * <code>int64 linkedTime = 6;</code>
   * @return The linkedTime.
   */
  long getLinkedTime();

  /**
   * <code>.TikTok.GroupPlayer ownerUser = 7;</code>
   * @return Whether the ownerUser field is set.
   */
  boolean hasOwnerUser();
  /**
   * <code>.TikTok.GroupPlayer ownerUser = 7;</code>
   * @return The ownerUser.
   */
  co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.GroupPlayer getOwnerUser();
  /**
   * <code>.TikTok.GroupPlayer ownerUser = 7;</code>
   */
  co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.GroupPlayerOrBuilder getOwnerUserOrBuilder();

  /**
   * <code>string group_linkmic_id = 8;</code>
   * @return The groupLinkmicId.
   */
  java.lang.String getGroupLinkmicId();
  /**
   * <code>string group_linkmic_id = 8;</code>
   * @return The bytes for groupLinkmicId.
   */
  com.google.protobuf.ByteString
      getGroupLinkmicIdBytes();
}
