// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: data.proto
// Protobuf Java Version: 4.32.0

package co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data;

/**
 * <pre>
 * &#64;KickOutContent
 * proto.webcast.im
 * C:&#92;Users&#92;ja&#92;RiderProjects&#92;TikTokProBufferGenerator&#92;Application&#92;output&#92;sources&#92;test.js
 * </pre>
 *
 * Protobuf type {@code TikTok.KickOutContent}
 */
@com.google.protobuf.Generated
public final class KickOutContent extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:TikTok.KickOutContent)
    KickOutContentOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      KickOutContent.class.getName());
  }
  // Use KickOutContent.newBuilder() to construct.
  private KickOutContent(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private KickOutContent() {
    kickoutReason_ = 0;
    linkedUserUiPositions_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    uiPos_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Data.internal_static_TikTok_KickOutContent_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Data.internal_static_TikTok_KickOutContent_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.KickOutContent.class, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.KickOutContent.Builder.class);
  }

  private int bitField0_;
  public static final int OFFLINER_FIELD_NUMBER = 1;
  private co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Player offliner_;
  /**
   * <code>.TikTok.Player offliner = 1;</code>
   * @return Whether the offliner field is set.
   */
  @java.lang.Override
  public boolean hasOffliner() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.TikTok.Player offliner = 1;</code>
   * @return The offliner.
   */
  @java.lang.Override
  public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Player getOffliner() {
    return offliner_ == null ? co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Player.getDefaultInstance() : offliner_;
  }
  /**
   * <code>.TikTok.Player offliner = 1;</code>
   */
  @java.lang.Override
  public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PlayerOrBuilder getOfflinerOrBuilder() {
    return offliner_ == null ? co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Player.getDefaultInstance() : offliner_;
  }

  public static final int KICKOUTREASON_FIELD_NUMBER = 2;
  private int kickoutReason_ = 0;
  /**
   * <code>.TikTok.KickoutReason kickoutReason = 2;</code>
   * @return The enum numeric value on the wire for kickoutReason.
   */
  @java.lang.Override public int getKickoutReasonValue() {
    return kickoutReason_;
  }
  /**
   * <code>.TikTok.KickoutReason kickoutReason = 2;</code>
   * @return The kickoutReason.
   */
  @java.lang.Override public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.enums.KickoutReason getKickoutReason() {
    co.casterlabs.sdk.tiktok.unsupported.types.protobuf.enums.KickoutReason result = co.casterlabs.sdk.tiktok.unsupported.types.protobuf.enums.KickoutReason.forNumber(kickoutReason_);
    return result == null ? co.casterlabs.sdk.tiktok.unsupported.types.protobuf.enums.KickoutReason.UNRECOGNIZED : result;
  }

  public static final int LINKED_USER_UI_POSITIONS_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList linkedUserUiPositions_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string linked_user_ui_positions = 3;</code>
   * @return A list containing the linkedUserUiPositions.
   */
  public com.google.protobuf.ProtocolStringList
      getLinkedUserUiPositionsList() {
    return linkedUserUiPositions_;
  }
  /**
   * <code>repeated string linked_user_ui_positions = 3;</code>
   * @return The count of linkedUserUiPositions.
   */
  public int getLinkedUserUiPositionsCount() {
    return linkedUserUiPositions_.size();
  }
  /**
   * <code>repeated string linked_user_ui_positions = 3;</code>
   * @param index The index of the element to return.
   * @return The linkedUserUiPositions at the given index.
   */
  public java.lang.String getLinkedUserUiPositions(int index) {
    return linkedUserUiPositions_.get(index);
  }
  /**
   * <code>repeated string linked_user_ui_positions = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the linkedUserUiPositions at the given index.
   */
  public com.google.protobuf.ByteString
      getLinkedUserUiPositionsBytes(int index) {
    return linkedUserUiPositions_.getByteString(index);
  }

  public static final int UI_POS_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private java.util.List<co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PosIdentity> uiPos_;
  /**
   * <code>repeated .TikTok.PosIdentity ui_pos = 4;</code>
   */
  @java.lang.Override
  public java.util.List<co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PosIdentity> getUiPosList() {
    return uiPos_;
  }
  /**
   * <code>repeated .TikTok.PosIdentity ui_pos = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PosIdentityOrBuilder> 
      getUiPosOrBuilderList() {
    return uiPos_;
  }
  /**
   * <code>repeated .TikTok.PosIdentity ui_pos = 4;</code>
   */
  @java.lang.Override
  public int getUiPosCount() {
    return uiPos_.size();
  }
  /**
   * <code>repeated .TikTok.PosIdentity ui_pos = 4;</code>
   */
  @java.lang.Override
  public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PosIdentity getUiPos(int index) {
    return uiPos_.get(index);
  }
  /**
   * <code>repeated .TikTok.PosIdentity ui_pos = 4;</code>
   */
  @java.lang.Override
  public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PosIdentityOrBuilder getUiPosOrBuilder(
      int index) {
    return uiPos_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getOffliner());
    }
    if (kickoutReason_ != co.casterlabs.sdk.tiktok.unsupported.types.protobuf.enums.KickoutReason.KICKOUT_REASON_UNKNOWN.getNumber()) {
      output.writeEnum(2, kickoutReason_);
    }
    for (int i = 0; i < linkedUserUiPositions_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, linkedUserUiPositions_.getRaw(i));
    }
    for (int i = 0; i < uiPos_.size(); i++) {
      output.writeMessage(4, uiPos_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getOffliner());
    }
    if (kickoutReason_ != co.casterlabs.sdk.tiktok.unsupported.types.protobuf.enums.KickoutReason.KICKOUT_REASON_UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, kickoutReason_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < linkedUserUiPositions_.size(); i++) {
        dataSize += computeStringSizeNoTag(linkedUserUiPositions_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getLinkedUserUiPositionsList().size();
    }
    for (int i = 0; i < uiPos_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, uiPos_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.KickOutContent)) {
      return super.equals(obj);
    }
    co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.KickOutContent other = (co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.KickOutContent) obj;

    if (hasOffliner() != other.hasOffliner()) return false;
    if (hasOffliner()) {
      if (!getOffliner()
          .equals(other.getOffliner())) return false;
    }
    if (kickoutReason_ != other.kickoutReason_) return false;
    if (!getLinkedUserUiPositionsList()
        .equals(other.getLinkedUserUiPositionsList())) return false;
    if (!getUiPosList()
        .equals(other.getUiPosList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasOffliner()) {
      hash = (37 * hash) + OFFLINER_FIELD_NUMBER;
      hash = (53 * hash) + getOffliner().hashCode();
    }
    hash = (37 * hash) + KICKOUTREASON_FIELD_NUMBER;
    hash = (53 * hash) + kickoutReason_;
    if (getLinkedUserUiPositionsCount() > 0) {
      hash = (37 * hash) + LINKED_USER_UI_POSITIONS_FIELD_NUMBER;
      hash = (53 * hash) + getLinkedUserUiPositionsList().hashCode();
    }
    if (getUiPosCount() > 0) {
      hash = (37 * hash) + UI_POS_FIELD_NUMBER;
      hash = (53 * hash) + getUiPosList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.KickOutContent parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.KickOutContent parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.KickOutContent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.KickOutContent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.KickOutContent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.KickOutContent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.KickOutContent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.KickOutContent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.KickOutContent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.KickOutContent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.KickOutContent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.KickOutContent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.KickOutContent prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * &#64;KickOutContent
   * proto.webcast.im
   * C:&#92;Users&#92;ja&#92;RiderProjects&#92;TikTokProBufferGenerator&#92;Application&#92;output&#92;sources&#92;test.js
   * </pre>
   *
   * Protobuf type {@code TikTok.KickOutContent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:TikTok.KickOutContent)
      co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.KickOutContentOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Data.internal_static_TikTok_KickOutContent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Data.internal_static_TikTok_KickOutContent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.KickOutContent.class, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.KickOutContent.Builder.class);
    }

    // Construct using co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.KickOutContent.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetOfflinerFieldBuilder();
        internalGetUiPosFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      offliner_ = null;
      if (offlinerBuilder_ != null) {
        offlinerBuilder_.dispose();
        offlinerBuilder_ = null;
      }
      kickoutReason_ = 0;
      linkedUserUiPositions_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      if (uiPosBuilder_ == null) {
        uiPos_ = java.util.Collections.emptyList();
      } else {
        uiPos_ = null;
        uiPosBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Data.internal_static_TikTok_KickOutContent_descriptor;
    }

    @java.lang.Override
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.KickOutContent getDefaultInstanceForType() {
      return co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.KickOutContent.getDefaultInstance();
    }

    @java.lang.Override
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.KickOutContent build() {
      co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.KickOutContent result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.KickOutContent buildPartial() {
      co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.KickOutContent result = new co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.KickOutContent(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.KickOutContent result) {
      if (uiPosBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          uiPos_ = java.util.Collections.unmodifiableList(uiPos_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.uiPos_ = uiPos_;
      } else {
        result.uiPos_ = uiPosBuilder_.build();
      }
    }

    private void buildPartial0(co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.KickOutContent result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.offliner_ = offlinerBuilder_ == null
            ? offliner_
            : offlinerBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.kickoutReason_ = kickoutReason_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        linkedUserUiPositions_.makeImmutable();
        result.linkedUserUiPositions_ = linkedUserUiPositions_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.KickOutContent) {
        return mergeFrom((co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.KickOutContent)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.KickOutContent other) {
      if (other == co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.KickOutContent.getDefaultInstance()) return this;
      if (other.hasOffliner()) {
        mergeOffliner(other.getOffliner());
      }
      if (other.kickoutReason_ != 0) {
        setKickoutReasonValue(other.getKickoutReasonValue());
      }
      if (!other.linkedUserUiPositions_.isEmpty()) {
        if (linkedUserUiPositions_.isEmpty()) {
          linkedUserUiPositions_ = other.linkedUserUiPositions_;
          bitField0_ |= 0x00000004;
        } else {
          ensureLinkedUserUiPositionsIsMutable();
          linkedUserUiPositions_.addAll(other.linkedUserUiPositions_);
        }
        onChanged();
      }
      if (uiPosBuilder_ == null) {
        if (!other.uiPos_.isEmpty()) {
          if (uiPos_.isEmpty()) {
            uiPos_ = other.uiPos_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureUiPosIsMutable();
            uiPos_.addAll(other.uiPos_);
          }
          onChanged();
        }
      } else {
        if (!other.uiPos_.isEmpty()) {
          if (uiPosBuilder_.isEmpty()) {
            uiPosBuilder_.dispose();
            uiPosBuilder_ = null;
            uiPos_ = other.uiPos_;
            bitField0_ = (bitField0_ & ~0x00000008);
            uiPosBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetUiPosFieldBuilder() : null;
          } else {
            uiPosBuilder_.addAllMessages(other.uiPos_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetOfflinerFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              kickoutReason_ = input.readEnum();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureLinkedUserUiPositionsIsMutable();
              linkedUserUiPositions_.add(s);
              break;
            } // case 26
            case 34: {
              co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PosIdentity m =
                  input.readMessage(
                      co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PosIdentity.parser(),
                      extensionRegistry);
              if (uiPosBuilder_ == null) {
                ensureUiPosIsMutable();
                uiPos_.add(m);
              } else {
                uiPosBuilder_.addMessage(m);
              }
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Player offliner_;
    private com.google.protobuf.SingleFieldBuilder<
        co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Player, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Player.Builder, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PlayerOrBuilder> offlinerBuilder_;
    /**
     * <code>.TikTok.Player offliner = 1;</code>
     * @return Whether the offliner field is set.
     */
    public boolean hasOffliner() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.TikTok.Player offliner = 1;</code>
     * @return The offliner.
     */
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Player getOffliner() {
      if (offlinerBuilder_ == null) {
        return offliner_ == null ? co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Player.getDefaultInstance() : offliner_;
      } else {
        return offlinerBuilder_.getMessage();
      }
    }
    /**
     * <code>.TikTok.Player offliner = 1;</code>
     */
    public Builder setOffliner(co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Player value) {
      if (offlinerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        offliner_ = value;
      } else {
        offlinerBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.TikTok.Player offliner = 1;</code>
     */
    public Builder setOffliner(
        co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Player.Builder builderForValue) {
      if (offlinerBuilder_ == null) {
        offliner_ = builderForValue.build();
      } else {
        offlinerBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.TikTok.Player offliner = 1;</code>
     */
    public Builder mergeOffliner(co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Player value) {
      if (offlinerBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          offliner_ != null &&
          offliner_ != co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Player.getDefaultInstance()) {
          getOfflinerBuilder().mergeFrom(value);
        } else {
          offliner_ = value;
        }
      } else {
        offlinerBuilder_.mergeFrom(value);
      }
      if (offliner_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.TikTok.Player offliner = 1;</code>
     */
    public Builder clearOffliner() {
      bitField0_ = (bitField0_ & ~0x00000001);
      offliner_ = null;
      if (offlinerBuilder_ != null) {
        offlinerBuilder_.dispose();
        offlinerBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.TikTok.Player offliner = 1;</code>
     */
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Player.Builder getOfflinerBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return internalGetOfflinerFieldBuilder().getBuilder();
    }
    /**
     * <code>.TikTok.Player offliner = 1;</code>
     */
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PlayerOrBuilder getOfflinerOrBuilder() {
      if (offlinerBuilder_ != null) {
        return offlinerBuilder_.getMessageOrBuilder();
      } else {
        return offliner_ == null ?
            co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Player.getDefaultInstance() : offliner_;
      }
    }
    /**
     * <code>.TikTok.Player offliner = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Player, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Player.Builder, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PlayerOrBuilder> 
        internalGetOfflinerFieldBuilder() {
      if (offlinerBuilder_ == null) {
        offlinerBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Player, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Player.Builder, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PlayerOrBuilder>(
                getOffliner(),
                getParentForChildren(),
                isClean());
        offliner_ = null;
      }
      return offlinerBuilder_;
    }

    private int kickoutReason_ = 0;
    /**
     * <code>.TikTok.KickoutReason kickoutReason = 2;</code>
     * @return The enum numeric value on the wire for kickoutReason.
     */
    @java.lang.Override public int getKickoutReasonValue() {
      return kickoutReason_;
    }
    /**
     * <code>.TikTok.KickoutReason kickoutReason = 2;</code>
     * @param value The enum numeric value on the wire for kickoutReason to set.
     * @return This builder for chaining.
     */
    public Builder setKickoutReasonValue(int value) {
      kickoutReason_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.TikTok.KickoutReason kickoutReason = 2;</code>
     * @return The kickoutReason.
     */
    @java.lang.Override
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.enums.KickoutReason getKickoutReason() {
      co.casterlabs.sdk.tiktok.unsupported.types.protobuf.enums.KickoutReason result = co.casterlabs.sdk.tiktok.unsupported.types.protobuf.enums.KickoutReason.forNumber(kickoutReason_);
      return result == null ? co.casterlabs.sdk.tiktok.unsupported.types.protobuf.enums.KickoutReason.UNRECOGNIZED : result;
    }
    /**
     * <code>.TikTok.KickoutReason kickoutReason = 2;</code>
     * @param value The kickoutReason to set.
     * @return This builder for chaining.
     */
    public Builder setKickoutReason(co.casterlabs.sdk.tiktok.unsupported.types.protobuf.enums.KickoutReason value) {
      if (value == null) { throw new NullPointerException(); }
      bitField0_ |= 0x00000002;
      kickoutReason_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.TikTok.KickoutReason kickoutReason = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearKickoutReason() {
      bitField0_ = (bitField0_ & ~0x00000002);
      kickoutReason_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList linkedUserUiPositions_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureLinkedUserUiPositionsIsMutable() {
      if (!linkedUserUiPositions_.isModifiable()) {
        linkedUserUiPositions_ = new com.google.protobuf.LazyStringArrayList(linkedUserUiPositions_);
      }
      bitField0_ |= 0x00000004;
    }
    /**
     * <code>repeated string linked_user_ui_positions = 3;</code>
     * @return A list containing the linkedUserUiPositions.
     */
    public com.google.protobuf.ProtocolStringList
        getLinkedUserUiPositionsList() {
      linkedUserUiPositions_.makeImmutable();
      return linkedUserUiPositions_;
    }
    /**
     * <code>repeated string linked_user_ui_positions = 3;</code>
     * @return The count of linkedUserUiPositions.
     */
    public int getLinkedUserUiPositionsCount() {
      return linkedUserUiPositions_.size();
    }
    /**
     * <code>repeated string linked_user_ui_positions = 3;</code>
     * @param index The index of the element to return.
     * @return The linkedUserUiPositions at the given index.
     */
    public java.lang.String getLinkedUserUiPositions(int index) {
      return linkedUserUiPositions_.get(index);
    }
    /**
     * <code>repeated string linked_user_ui_positions = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the linkedUserUiPositions at the given index.
     */
    public com.google.protobuf.ByteString
        getLinkedUserUiPositionsBytes(int index) {
      return linkedUserUiPositions_.getByteString(index);
    }
    /**
     * <code>repeated string linked_user_ui_positions = 3;</code>
     * @param index The index to set the value at.
     * @param value The linkedUserUiPositions to set.
     * @return This builder for chaining.
     */
    public Builder setLinkedUserUiPositions(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureLinkedUserUiPositionsIsMutable();
      linkedUserUiPositions_.set(index, value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string linked_user_ui_positions = 3;</code>
     * @param value The linkedUserUiPositions to add.
     * @return This builder for chaining.
     */
    public Builder addLinkedUserUiPositions(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureLinkedUserUiPositionsIsMutable();
      linkedUserUiPositions_.add(value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string linked_user_ui_positions = 3;</code>
     * @param values The linkedUserUiPositions to add.
     * @return This builder for chaining.
     */
    public Builder addAllLinkedUserUiPositions(
        java.lang.Iterable<java.lang.String> values) {
      ensureLinkedUserUiPositionsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, linkedUserUiPositions_);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string linked_user_ui_positions = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearLinkedUserUiPositions() {
      linkedUserUiPositions_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000004);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string linked_user_ui_positions = 3;</code>
     * @param value The bytes of the linkedUserUiPositions to add.
     * @return This builder for chaining.
     */
    public Builder addLinkedUserUiPositionsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureLinkedUserUiPositionsIsMutable();
      linkedUserUiPositions_.add(value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.util.List<co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PosIdentity> uiPos_ =
      java.util.Collections.emptyList();
    private void ensureUiPosIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        uiPos_ = new java.util.ArrayList<co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PosIdentity>(uiPos_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PosIdentity, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PosIdentity.Builder, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PosIdentityOrBuilder> uiPosBuilder_;

    /**
     * <code>repeated .TikTok.PosIdentity ui_pos = 4;</code>
     */
    public java.util.List<co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PosIdentity> getUiPosList() {
      if (uiPosBuilder_ == null) {
        return java.util.Collections.unmodifiableList(uiPos_);
      } else {
        return uiPosBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .TikTok.PosIdentity ui_pos = 4;</code>
     */
    public int getUiPosCount() {
      if (uiPosBuilder_ == null) {
        return uiPos_.size();
      } else {
        return uiPosBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .TikTok.PosIdentity ui_pos = 4;</code>
     */
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PosIdentity getUiPos(int index) {
      if (uiPosBuilder_ == null) {
        return uiPos_.get(index);
      } else {
        return uiPosBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .TikTok.PosIdentity ui_pos = 4;</code>
     */
    public Builder setUiPos(
        int index, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PosIdentity value) {
      if (uiPosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUiPosIsMutable();
        uiPos_.set(index, value);
        onChanged();
      } else {
        uiPosBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .TikTok.PosIdentity ui_pos = 4;</code>
     */
    public Builder setUiPos(
        int index, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PosIdentity.Builder builderForValue) {
      if (uiPosBuilder_ == null) {
        ensureUiPosIsMutable();
        uiPos_.set(index, builderForValue.build());
        onChanged();
      } else {
        uiPosBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .TikTok.PosIdentity ui_pos = 4;</code>
     */
    public Builder addUiPos(co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PosIdentity value) {
      if (uiPosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUiPosIsMutable();
        uiPos_.add(value);
        onChanged();
      } else {
        uiPosBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .TikTok.PosIdentity ui_pos = 4;</code>
     */
    public Builder addUiPos(
        int index, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PosIdentity value) {
      if (uiPosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUiPosIsMutable();
        uiPos_.add(index, value);
        onChanged();
      } else {
        uiPosBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .TikTok.PosIdentity ui_pos = 4;</code>
     */
    public Builder addUiPos(
        co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PosIdentity.Builder builderForValue) {
      if (uiPosBuilder_ == null) {
        ensureUiPosIsMutable();
        uiPos_.add(builderForValue.build());
        onChanged();
      } else {
        uiPosBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .TikTok.PosIdentity ui_pos = 4;</code>
     */
    public Builder addUiPos(
        int index, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PosIdentity.Builder builderForValue) {
      if (uiPosBuilder_ == null) {
        ensureUiPosIsMutable();
        uiPos_.add(index, builderForValue.build());
        onChanged();
      } else {
        uiPosBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .TikTok.PosIdentity ui_pos = 4;</code>
     */
    public Builder addAllUiPos(
        java.lang.Iterable<? extends co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PosIdentity> values) {
      if (uiPosBuilder_ == null) {
        ensureUiPosIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, uiPos_);
        onChanged();
      } else {
        uiPosBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .TikTok.PosIdentity ui_pos = 4;</code>
     */
    public Builder clearUiPos() {
      if (uiPosBuilder_ == null) {
        uiPos_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        uiPosBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .TikTok.PosIdentity ui_pos = 4;</code>
     */
    public Builder removeUiPos(int index) {
      if (uiPosBuilder_ == null) {
        ensureUiPosIsMutable();
        uiPos_.remove(index);
        onChanged();
      } else {
        uiPosBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .TikTok.PosIdentity ui_pos = 4;</code>
     */
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PosIdentity.Builder getUiPosBuilder(
        int index) {
      return internalGetUiPosFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .TikTok.PosIdentity ui_pos = 4;</code>
     */
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PosIdentityOrBuilder getUiPosOrBuilder(
        int index) {
      if (uiPosBuilder_ == null) {
        return uiPos_.get(index);  } else {
        return uiPosBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .TikTok.PosIdentity ui_pos = 4;</code>
     */
    public java.util.List<? extends co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PosIdentityOrBuilder> 
         getUiPosOrBuilderList() {
      if (uiPosBuilder_ != null) {
        return uiPosBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(uiPos_);
      }
    }
    /**
     * <code>repeated .TikTok.PosIdentity ui_pos = 4;</code>
     */
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PosIdentity.Builder addUiPosBuilder() {
      return internalGetUiPosFieldBuilder().addBuilder(
          co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PosIdentity.getDefaultInstance());
    }
    /**
     * <code>repeated .TikTok.PosIdentity ui_pos = 4;</code>
     */
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PosIdentity.Builder addUiPosBuilder(
        int index) {
      return internalGetUiPosFieldBuilder().addBuilder(
          index, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PosIdentity.getDefaultInstance());
    }
    /**
     * <code>repeated .TikTok.PosIdentity ui_pos = 4;</code>
     */
    public java.util.List<co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PosIdentity.Builder> 
         getUiPosBuilderList() {
      return internalGetUiPosFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PosIdentity, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PosIdentity.Builder, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PosIdentityOrBuilder> 
        internalGetUiPosFieldBuilder() {
      if (uiPosBuilder_ == null) {
        uiPosBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PosIdentity, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PosIdentity.Builder, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PosIdentityOrBuilder>(
                uiPos_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        uiPos_ = null;
      }
      return uiPosBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:TikTok.KickOutContent)
  }

  // @@protoc_insertion_point(class_scope:TikTok.KickOutContent)
  private static final co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.KickOutContent DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.KickOutContent();
  }

  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.KickOutContent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<KickOutContent>
      PARSER = new com.google.protobuf.AbstractParser<KickOutContent>() {
    @java.lang.Override
    public KickOutContent parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<KickOutContent> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<KickOutContent> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.KickOutContent getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

