// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: data.proto
// Protobuf Java Version: 4.32.0

package co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data;

@com.google.protobuf.Generated
public interface LinkerInviteContentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TikTok.LinkerInviteContent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 fromUserId = 1;</code>
   * @return The fromUserId.
   */
  long getFromUserId();

  /**
   * <code>int64 fromRoomId = 2;</code>
   * @return The fromRoomId.
   */
  long getFromRoomId();

  /**
   * <code>string toRtcExtInfo = 3;</code>
   * @return The toRtcExtInfo.
   */
  java.lang.String getToRtcExtInfo();
  /**
   * <code>string toRtcExtInfo = 3;</code>
   * @return The bytes for toRtcExtInfo.
   */
  com.google.protobuf.ByteString
      getToRtcExtInfoBytes();

  /**
   * <code>bool rtcJoinChannel = 4;</code>
   * @return The rtcJoinChannel.
   */
  boolean getRtcJoinChannel();

  /**
   * <code>int64 vendor = 5;</code>
   * @return The vendor.
   */
  long getVendor();

  /**
   * <code>string secFromUserId = 6;</code>
   * @return The secFromUserId.
   */
  java.lang.String getSecFromUserId();
  /**
   * <code>string secFromUserId = 6;</code>
   * @return The bytes for secFromUserId.
   */
  com.google.protobuf.ByteString
      getSecFromUserIdBytes();

  /**
   * <code>string toLinkmicIdStr = 7;</code>
   * @return The toLinkmicIdStr.
   */
  java.lang.String getToLinkmicIdStr();
  /**
   * <code>string toLinkmicIdStr = 7;</code>
   * @return The bytes for toLinkmicIdStr.
   */
  com.google.protobuf.ByteString
      getToLinkmicIdStrBytes();

  /**
   * <code>.TikTok.User fromUser = 8;</code>
   * @return Whether the fromUser field is set.
   */
  boolean hasFromUser();
  /**
   * <code>.TikTok.User fromUser = 8;</code>
   * @return The fromUser.
   */
  co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.User getFromUser();
  /**
   * <code>.TikTok.User fromUser = 8;</code>
   */
  co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.UserOrBuilder getFromUserOrBuilder();

  /**
   * <code>int64 requiredMicIdx = 9;</code>
   * @return The requiredMicIdx.
   */
  long getRequiredMicIdx();

  /**
   * <code>map&lt;int64, string&gt; rtc_ext_info_map = 10;</code>
   */
  int getRtcExtInfoMapCount();
  /**
   * <code>map&lt;int64, string&gt; rtc_ext_info_map = 10;</code>
   */
  boolean containsRtcExtInfoMap(
      long key);
  /**
   * Use {@link #getRtcExtInfoMapMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.Long, java.lang.String>
  getRtcExtInfoMap();
  /**
   * <code>map&lt;int64, string&gt; rtc_ext_info_map = 10;</code>
   */
  java.util.Map<java.lang.Long, java.lang.String>
  getRtcExtInfoMapMap();
  /**
   * <code>map&lt;int64, string&gt; rtc_ext_info_map = 10;</code>
   */
  /* nullable */
java.lang.String getRtcExtInfoMapOrDefault(
      long key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <code>map&lt;int64, string&gt; rtc_ext_info_map = 10;</code>
   */
  java.lang.String getRtcExtInfoMapOrThrow(
      long key);

  /**
   * <code>.TikTok.LinkmicMultiLiveEnum multi_live_layout_enable = 11;</code>
   * @return The enum numeric value on the wire for multiLiveLayoutEnable.
   */
  int getMultiLiveLayoutEnableValue();
  /**
   * <code>.TikTok.LinkmicMultiLiveEnum multi_live_layout_enable = 11;</code>
   * @return The multiLiveLayoutEnable.
   */
  co.casterlabs.sdk.tiktok.unsupported.types.protobuf.enums.LinkmicMultiLiveEnum getMultiLiveLayoutEnable();

  /**
   * <code>.TikTok.MultiLiveAnchorPanelSettings multi_live_setting = 12;</code>
   * @return Whether the multiLiveSetting field is set.
   */
  boolean hasMultiLiveSetting();
  /**
   * <code>.TikTok.MultiLiveAnchorPanelSettings multi_live_setting = 12;</code>
   * @return The multiLiveSetting.
   */
  co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.MultiLiveAnchorPanelSettings getMultiLiveSetting();
  /**
   * <code>.TikTok.MultiLiveAnchorPanelSettings multi_live_setting = 12;</code>
   */
  co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.MultiLiveAnchorPanelSettingsOrBuilder getMultiLiveSettingOrBuilder();

  /**
   * <code>string from_linkmic_id_str = 13;</code>
   * @return The fromLinkmicIdStr.
   */
  java.lang.String getFromLinkmicIdStr();
  /**
   * <code>string from_linkmic_id_str = 13;</code>
   * @return The bytes for fromLinkmicIdStr.
   */
  com.google.protobuf.ByteString
      getFromLinkmicIdStrBytes();

  /**
   * <code>.TikTok.LinkerInviteContent.InviteTopHostInfo from_top_host_info = 16;</code>
   * @return Whether the fromTopHostInfo field is set.
   */
  boolean hasFromTopHostInfo();
  /**
   * <code>.TikTok.LinkerInviteContent.InviteTopHostInfo from_top_host_info = 16;</code>
   * @return The fromTopHostInfo.
   */
  co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.LinkerInviteContent.InviteTopHostInfo getFromTopHostInfo();
  /**
   * <code>.TikTok.LinkerInviteContent.InviteTopHostInfo from_top_host_info = 16;</code>
   */
  co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.LinkerInviteContent.InviteTopHostInfoOrBuilder getFromTopHostInfoOrBuilder();

  /**
   * <code>int64 action_id = 17;</code>
   * @return The actionId.
   */
  long getActionId();

  /**
   * <code>repeated .TikTok.LinkerInviteContent.LinkmicUserInfo linked_users = 18;</code>
   */
  java.util.List<co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.LinkerInviteContent.LinkmicUserInfo> 
      getLinkedUsersList();
  /**
   * <code>repeated .TikTok.LinkerInviteContent.LinkmicUserInfo linked_users = 18;</code>
   */
  co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.LinkerInviteContent.LinkmicUserInfo getLinkedUsers(int index);
  /**
   * <code>repeated .TikTok.LinkerInviteContent.LinkmicUserInfo linked_users = 18;</code>
   */
  int getLinkedUsersCount();
  /**
   * <code>repeated .TikTok.LinkerInviteContent.LinkmicUserInfo linked_users = 18;</code>
   */
  java.util.List<? extends co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.LinkerInviteContent.LinkmicUserInfoOrBuilder> 
      getLinkedUsersOrBuilderList();
  /**
   * <code>repeated .TikTok.LinkerInviteContent.LinkmicUserInfo linked_users = 18;</code>
   */
  co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.LinkerInviteContent.LinkmicUserInfoOrBuilder getLinkedUsersOrBuilder(
      int index);

  /**
   * <code>.TikTok.LinkerInviteContent.PerceptionDialogInfo dialog_info = 19;</code>
   * @return Whether the dialogInfo field is set.
   */
  boolean hasDialogInfo();
  /**
   * <code>.TikTok.LinkerInviteContent.PerceptionDialogInfo dialog_info = 19;</code>
   * @return The dialogInfo.
   */
  co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.LinkerInviteContent.PerceptionDialogInfo getDialogInfo();
  /**
   * <code>.TikTok.LinkerInviteContent.PerceptionDialogInfo dialog_info = 19;</code>
   */
  co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.LinkerInviteContent.PerceptionDialogInfoOrBuilder getDialogInfoOrBuilder();

  /**
   * <code>.TikTok.PunishEventInfo punish_event_info = 20;</code>
   * @return Whether the punishEventInfo field is set.
   */
  boolean hasPunishEventInfo();
  /**
   * <code>.TikTok.PunishEventInfo punish_event_info = 20;</code>
   * @return The punishEventInfo.
   */
  co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PunishEventInfo getPunishEventInfo();
  /**
   * <code>.TikTok.PunishEventInfo punish_event_info = 20;</code>
   */
  co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PunishEventInfoOrBuilder getPunishEventInfoOrBuilder();

  /**
   * <code>int32 from_room_age_restricted = 21;</code>
   * @return The fromRoomAgeRestricted.
   */
  int getFromRoomAgeRestricted();

  /**
   * <code>repeated .TikTok.LinkerInviteContent.CohostABTestSetting ab_test_setting = 23;</code>
   */
  java.util.List<co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.LinkerInviteContent.CohostABTestSetting> 
      getAbTestSettingList();
  /**
   * <code>repeated .TikTok.LinkerInviteContent.CohostABTestSetting ab_test_setting = 23;</code>
   */
  co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.LinkerInviteContent.CohostABTestSetting getAbTestSetting(int index);
  /**
   * <code>repeated .TikTok.LinkerInviteContent.CohostABTestSetting ab_test_setting = 23;</code>
   */
  int getAbTestSettingCount();
  /**
   * <code>repeated .TikTok.LinkerInviteContent.CohostABTestSetting ab_test_setting = 23;</code>
   */
  java.util.List<? extends co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.LinkerInviteContent.CohostABTestSettingOrBuilder> 
      getAbTestSettingOrBuilderList();
  /**
   * <code>repeated .TikTok.LinkerInviteContent.CohostABTestSetting ab_test_setting = 23;</code>
   */
  co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.LinkerInviteContent.CohostABTestSettingOrBuilder getAbTestSettingOrBuilder(
      int index);

  /**
   * <code>.TikTok.LinkerInviteContent.LinkerInviteMessageExtra linker_invite_msg_extra = 101;</code>
   * @return Whether the linkerInviteMsgExtra field is set.
   */
  boolean hasLinkerInviteMsgExtra();
  /**
   * <code>.TikTok.LinkerInviteContent.LinkerInviteMessageExtra linker_invite_msg_extra = 101;</code>
   * @return The linkerInviteMsgExtra.
   */
  co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.LinkerInviteContent.LinkerInviteMessageExtra getLinkerInviteMsgExtra();
  /**
   * <code>.TikTok.LinkerInviteContent.LinkerInviteMessageExtra linker_invite_msg_extra = 101;</code>
   */
  co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.LinkerInviteContent.LinkerInviteMessageExtraOrBuilder getLinkerInviteMsgExtraOrBuilder();
}
