// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: data.proto
// Protobuf Java Version: 4.32.0

package co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data;

@com.google.protobuf.Generated
public interface LinkerUpdateUserSettingContentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TikTok.LinkerUpdateUserSettingContent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.TikTok.MultiLiveAnchorPanelSettings multi_live_anchor_panel_settings = 1;</code>
   * @return Whether the multiLiveAnchorPanelSettings field is set.
   */
  boolean hasMultiLiveAnchorPanelSettings();
  /**
   * <code>.TikTok.MultiLiveAnchorPanelSettings multi_live_anchor_panel_settings = 1;</code>
   * @return The multiLiveAnchorPanelSettings.
   */
  co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.MultiLiveAnchorPanelSettings getMultiLiveAnchorPanelSettings();
  /**
   * <code>.TikTok.MultiLiveAnchorPanelSettings multi_live_anchor_panel_settings = 1;</code>
   */
  co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.MultiLiveAnchorPanelSettingsOrBuilder getMultiLiveAnchorPanelSettingsOrBuilder();
}
