// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: data.proto
// Protobuf Java Version: 4.32.0

package co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data;

/**
 * Protobuf type {@code TikTok.ListChangeContent}
 */
@com.google.protobuf.Generated
public final class ListChangeContent extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:TikTok.ListChangeContent)
    ListChangeContentOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      ListChangeContent.class.getName());
  }
  // Use ListChangeContent.newBuilder() to construct.
  private ListChangeContent(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ListChangeContent() {
    linkedUserUiPositions_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    contentPos_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Data.internal_static_TikTok_ListChangeContent_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Data.internal_static_TikTok_ListChangeContent_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ListChangeContent.class, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ListChangeContent.Builder.class);
  }

  private int bitField0_;
  public static final int LIST_CHANGE_TYPE_FIELD_NUMBER = 1;
  private int listChangeType_ = 0;
  /**
   * <code>int32 list_change_type = 1;</code>
   * @return The listChangeType.
   */
  @java.lang.Override
  public int getListChangeType() {
    return listChangeType_;
  }

  public static final int USER_LIST_FIELD_NUMBER = 2;
  private co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.AllListUser userList_;
  /**
   * <code>.TikTok.AllListUser user_list = 2;</code>
   * @return Whether the userList field is set.
   */
  @java.lang.Override
  public boolean hasUserList() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.TikTok.AllListUser user_list = 2;</code>
   * @return The userList.
   */
  @java.lang.Override
  public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.AllListUser getUserList() {
    return userList_ == null ? co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.AllListUser.getDefaultInstance() : userList_;
  }
  /**
   * <code>.TikTok.AllListUser user_list = 2;</code>
   */
  @java.lang.Override
  public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.AllListUserOrBuilder getUserListOrBuilder() {
    return userList_ == null ? co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.AllListUser.getDefaultInstance() : userList_;
  }

  public static final int LINKED_USER_UI_POSITIONS_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList linkedUserUiPositions_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string linked_user_ui_positions = 3;</code>
   * @return A list containing the linkedUserUiPositions.
   */
  public com.google.protobuf.ProtocolStringList
      getLinkedUserUiPositionsList() {
    return linkedUserUiPositions_;
  }
  /**
   * <code>repeated string linked_user_ui_positions = 3;</code>
   * @return The count of linkedUserUiPositions.
   */
  public int getLinkedUserUiPositionsCount() {
    return linkedUserUiPositions_.size();
  }
  /**
   * <code>repeated string linked_user_ui_positions = 3;</code>
   * @param index The index of the element to return.
   * @return The linkedUserUiPositions at the given index.
   */
  public java.lang.String getLinkedUserUiPositions(int index) {
    return linkedUserUiPositions_.get(index);
  }
  /**
   * <code>repeated string linked_user_ui_positions = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the linkedUserUiPositions at the given index.
   */
  public com.google.protobuf.ByteString
      getLinkedUserUiPositionsBytes(int index) {
    return linkedUserUiPositions_.getByteString(index);
  }

  public static final int CONTENT_POS_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private java.util.List<co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ContentPosition> contentPos_;
  /**
   * <code>repeated .TikTok.ContentPosition content_pos = 4;</code>
   */
  @java.lang.Override
  public java.util.List<co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ContentPosition> getContentPosList() {
    return contentPos_;
  }
  /**
   * <code>repeated .TikTok.ContentPosition content_pos = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ContentPositionOrBuilder> 
      getContentPosOrBuilderList() {
    return contentPos_;
  }
  /**
   * <code>repeated .TikTok.ContentPosition content_pos = 4;</code>
   */
  @java.lang.Override
  public int getContentPosCount() {
    return contentPos_.size();
  }
  /**
   * <code>repeated .TikTok.ContentPosition content_pos = 4;</code>
   */
  @java.lang.Override
  public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ContentPosition getContentPos(int index) {
    return contentPos_.get(index);
  }
  /**
   * <code>repeated .TikTok.ContentPosition content_pos = 4;</code>
   */
  @java.lang.Override
  public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ContentPositionOrBuilder getContentPosOrBuilder(
      int index) {
    return contentPos_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (listChangeType_ != 0) {
      output.writeInt32(1, listChangeType_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getUserList());
    }
    for (int i = 0; i < linkedUserUiPositions_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, linkedUserUiPositions_.getRaw(i));
    }
    for (int i = 0; i < contentPos_.size(); i++) {
      output.writeMessage(4, contentPos_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (listChangeType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, listChangeType_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getUserList());
    }
    {
      int dataSize = 0;
      for (int i = 0; i < linkedUserUiPositions_.size(); i++) {
        dataSize += computeStringSizeNoTag(linkedUserUiPositions_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getLinkedUserUiPositionsList().size();
    }
    for (int i = 0; i < contentPos_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, contentPos_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ListChangeContent)) {
      return super.equals(obj);
    }
    co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ListChangeContent other = (co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ListChangeContent) obj;

    if (getListChangeType()
        != other.getListChangeType()) return false;
    if (hasUserList() != other.hasUserList()) return false;
    if (hasUserList()) {
      if (!getUserList()
          .equals(other.getUserList())) return false;
    }
    if (!getLinkedUserUiPositionsList()
        .equals(other.getLinkedUserUiPositionsList())) return false;
    if (!getContentPosList()
        .equals(other.getContentPosList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + LIST_CHANGE_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getListChangeType();
    if (hasUserList()) {
      hash = (37 * hash) + USER_LIST_FIELD_NUMBER;
      hash = (53 * hash) + getUserList().hashCode();
    }
    if (getLinkedUserUiPositionsCount() > 0) {
      hash = (37 * hash) + LINKED_USER_UI_POSITIONS_FIELD_NUMBER;
      hash = (53 * hash) + getLinkedUserUiPositionsList().hashCode();
    }
    if (getContentPosCount() > 0) {
      hash = (37 * hash) + CONTENT_POS_FIELD_NUMBER;
      hash = (53 * hash) + getContentPosList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ListChangeContent parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ListChangeContent parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ListChangeContent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ListChangeContent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ListChangeContent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ListChangeContent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ListChangeContent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ListChangeContent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ListChangeContent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ListChangeContent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ListChangeContent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ListChangeContent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ListChangeContent prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code TikTok.ListChangeContent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:TikTok.ListChangeContent)
      co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ListChangeContentOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Data.internal_static_TikTok_ListChangeContent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Data.internal_static_TikTok_ListChangeContent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ListChangeContent.class, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ListChangeContent.Builder.class);
    }

    // Construct using co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ListChangeContent.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetUserListFieldBuilder();
        internalGetContentPosFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      listChangeType_ = 0;
      userList_ = null;
      if (userListBuilder_ != null) {
        userListBuilder_.dispose();
        userListBuilder_ = null;
      }
      linkedUserUiPositions_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      if (contentPosBuilder_ == null) {
        contentPos_ = java.util.Collections.emptyList();
      } else {
        contentPos_ = null;
        contentPosBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Data.internal_static_TikTok_ListChangeContent_descriptor;
    }

    @java.lang.Override
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ListChangeContent getDefaultInstanceForType() {
      return co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ListChangeContent.getDefaultInstance();
    }

    @java.lang.Override
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ListChangeContent build() {
      co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ListChangeContent result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ListChangeContent buildPartial() {
      co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ListChangeContent result = new co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ListChangeContent(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ListChangeContent result) {
      if (contentPosBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          contentPos_ = java.util.Collections.unmodifiableList(contentPos_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.contentPos_ = contentPos_;
      } else {
        result.contentPos_ = contentPosBuilder_.build();
      }
    }

    private void buildPartial0(co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ListChangeContent result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.listChangeType_ = listChangeType_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.userList_ = userListBuilder_ == null
            ? userList_
            : userListBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        linkedUserUiPositions_.makeImmutable();
        result.linkedUserUiPositions_ = linkedUserUiPositions_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ListChangeContent) {
        return mergeFrom((co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ListChangeContent)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ListChangeContent other) {
      if (other == co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ListChangeContent.getDefaultInstance()) return this;
      if (other.getListChangeType() != 0) {
        setListChangeType(other.getListChangeType());
      }
      if (other.hasUserList()) {
        mergeUserList(other.getUserList());
      }
      if (!other.linkedUserUiPositions_.isEmpty()) {
        if (linkedUserUiPositions_.isEmpty()) {
          linkedUserUiPositions_ = other.linkedUserUiPositions_;
          bitField0_ |= 0x00000004;
        } else {
          ensureLinkedUserUiPositionsIsMutable();
          linkedUserUiPositions_.addAll(other.linkedUserUiPositions_);
        }
        onChanged();
      }
      if (contentPosBuilder_ == null) {
        if (!other.contentPos_.isEmpty()) {
          if (contentPos_.isEmpty()) {
            contentPos_ = other.contentPos_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureContentPosIsMutable();
            contentPos_.addAll(other.contentPos_);
          }
          onChanged();
        }
      } else {
        if (!other.contentPos_.isEmpty()) {
          if (contentPosBuilder_.isEmpty()) {
            contentPosBuilder_.dispose();
            contentPosBuilder_ = null;
            contentPos_ = other.contentPos_;
            bitField0_ = (bitField0_ & ~0x00000008);
            contentPosBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetContentPosFieldBuilder() : null;
          } else {
            contentPosBuilder_.addAllMessages(other.contentPos_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              listChangeType_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              input.readMessage(
                  internalGetUserListFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureLinkedUserUiPositionsIsMutable();
              linkedUserUiPositions_.add(s);
              break;
            } // case 26
            case 34: {
              co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ContentPosition m =
                  input.readMessage(
                      co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ContentPosition.parser(),
                      extensionRegistry);
              if (contentPosBuilder_ == null) {
                ensureContentPosIsMutable();
                contentPos_.add(m);
              } else {
                contentPosBuilder_.addMessage(m);
              }
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int listChangeType_ ;
    /**
     * <code>int32 list_change_type = 1;</code>
     * @return The listChangeType.
     */
    @java.lang.Override
    public int getListChangeType() {
      return listChangeType_;
    }
    /**
     * <code>int32 list_change_type = 1;</code>
     * @param value The listChangeType to set.
     * @return This builder for chaining.
     */
    public Builder setListChangeType(int value) {

      listChangeType_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 list_change_type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearListChangeType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      listChangeType_ = 0;
      onChanged();
      return this;
    }

    private co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.AllListUser userList_;
    private com.google.protobuf.SingleFieldBuilder<
        co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.AllListUser, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.AllListUser.Builder, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.AllListUserOrBuilder> userListBuilder_;
    /**
     * <code>.TikTok.AllListUser user_list = 2;</code>
     * @return Whether the userList field is set.
     */
    public boolean hasUserList() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.TikTok.AllListUser user_list = 2;</code>
     * @return The userList.
     */
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.AllListUser getUserList() {
      if (userListBuilder_ == null) {
        return userList_ == null ? co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.AllListUser.getDefaultInstance() : userList_;
      } else {
        return userListBuilder_.getMessage();
      }
    }
    /**
     * <code>.TikTok.AllListUser user_list = 2;</code>
     */
    public Builder setUserList(co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.AllListUser value) {
      if (userListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        userList_ = value;
      } else {
        userListBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.TikTok.AllListUser user_list = 2;</code>
     */
    public Builder setUserList(
        co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.AllListUser.Builder builderForValue) {
      if (userListBuilder_ == null) {
        userList_ = builderForValue.build();
      } else {
        userListBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.TikTok.AllListUser user_list = 2;</code>
     */
    public Builder mergeUserList(co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.AllListUser value) {
      if (userListBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          userList_ != null &&
          userList_ != co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.AllListUser.getDefaultInstance()) {
          getUserListBuilder().mergeFrom(value);
        } else {
          userList_ = value;
        }
      } else {
        userListBuilder_.mergeFrom(value);
      }
      if (userList_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.TikTok.AllListUser user_list = 2;</code>
     */
    public Builder clearUserList() {
      bitField0_ = (bitField0_ & ~0x00000002);
      userList_ = null;
      if (userListBuilder_ != null) {
        userListBuilder_.dispose();
        userListBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.TikTok.AllListUser user_list = 2;</code>
     */
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.AllListUser.Builder getUserListBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return internalGetUserListFieldBuilder().getBuilder();
    }
    /**
     * <code>.TikTok.AllListUser user_list = 2;</code>
     */
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.AllListUserOrBuilder getUserListOrBuilder() {
      if (userListBuilder_ != null) {
        return userListBuilder_.getMessageOrBuilder();
      } else {
        return userList_ == null ?
            co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.AllListUser.getDefaultInstance() : userList_;
      }
    }
    /**
     * <code>.TikTok.AllListUser user_list = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.AllListUser, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.AllListUser.Builder, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.AllListUserOrBuilder> 
        internalGetUserListFieldBuilder() {
      if (userListBuilder_ == null) {
        userListBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.AllListUser, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.AllListUser.Builder, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.AllListUserOrBuilder>(
                getUserList(),
                getParentForChildren(),
                isClean());
        userList_ = null;
      }
      return userListBuilder_;
    }

    private com.google.protobuf.LazyStringArrayList linkedUserUiPositions_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureLinkedUserUiPositionsIsMutable() {
      if (!linkedUserUiPositions_.isModifiable()) {
        linkedUserUiPositions_ = new com.google.protobuf.LazyStringArrayList(linkedUserUiPositions_);
      }
      bitField0_ |= 0x00000004;
    }
    /**
     * <code>repeated string linked_user_ui_positions = 3;</code>
     * @return A list containing the linkedUserUiPositions.
     */
    public com.google.protobuf.ProtocolStringList
        getLinkedUserUiPositionsList() {
      linkedUserUiPositions_.makeImmutable();
      return linkedUserUiPositions_;
    }
    /**
     * <code>repeated string linked_user_ui_positions = 3;</code>
     * @return The count of linkedUserUiPositions.
     */
    public int getLinkedUserUiPositionsCount() {
      return linkedUserUiPositions_.size();
    }
    /**
     * <code>repeated string linked_user_ui_positions = 3;</code>
     * @param index The index of the element to return.
     * @return The linkedUserUiPositions at the given index.
     */
    public java.lang.String getLinkedUserUiPositions(int index) {
      return linkedUserUiPositions_.get(index);
    }
    /**
     * <code>repeated string linked_user_ui_positions = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the linkedUserUiPositions at the given index.
     */
    public com.google.protobuf.ByteString
        getLinkedUserUiPositionsBytes(int index) {
      return linkedUserUiPositions_.getByteString(index);
    }
    /**
     * <code>repeated string linked_user_ui_positions = 3;</code>
     * @param index The index to set the value at.
     * @param value The linkedUserUiPositions to set.
     * @return This builder for chaining.
     */
    public Builder setLinkedUserUiPositions(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureLinkedUserUiPositionsIsMutable();
      linkedUserUiPositions_.set(index, value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string linked_user_ui_positions = 3;</code>
     * @param value The linkedUserUiPositions to add.
     * @return This builder for chaining.
     */
    public Builder addLinkedUserUiPositions(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureLinkedUserUiPositionsIsMutable();
      linkedUserUiPositions_.add(value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string linked_user_ui_positions = 3;</code>
     * @param values The linkedUserUiPositions to add.
     * @return This builder for chaining.
     */
    public Builder addAllLinkedUserUiPositions(
        java.lang.Iterable<java.lang.String> values) {
      ensureLinkedUserUiPositionsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, linkedUserUiPositions_);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string linked_user_ui_positions = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearLinkedUserUiPositions() {
      linkedUserUiPositions_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000004);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string linked_user_ui_positions = 3;</code>
     * @param value The bytes of the linkedUserUiPositions to add.
     * @return This builder for chaining.
     */
    public Builder addLinkedUserUiPositionsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureLinkedUserUiPositionsIsMutable();
      linkedUserUiPositions_.add(value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.util.List<co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ContentPosition> contentPos_ =
      java.util.Collections.emptyList();
    private void ensureContentPosIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        contentPos_ = new java.util.ArrayList<co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ContentPosition>(contentPos_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ContentPosition, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ContentPosition.Builder, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ContentPositionOrBuilder> contentPosBuilder_;

    /**
     * <code>repeated .TikTok.ContentPosition content_pos = 4;</code>
     */
    public java.util.List<co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ContentPosition> getContentPosList() {
      if (contentPosBuilder_ == null) {
        return java.util.Collections.unmodifiableList(contentPos_);
      } else {
        return contentPosBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .TikTok.ContentPosition content_pos = 4;</code>
     */
    public int getContentPosCount() {
      if (contentPosBuilder_ == null) {
        return contentPos_.size();
      } else {
        return contentPosBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .TikTok.ContentPosition content_pos = 4;</code>
     */
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ContentPosition getContentPos(int index) {
      if (contentPosBuilder_ == null) {
        return contentPos_.get(index);
      } else {
        return contentPosBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .TikTok.ContentPosition content_pos = 4;</code>
     */
    public Builder setContentPos(
        int index, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ContentPosition value) {
      if (contentPosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureContentPosIsMutable();
        contentPos_.set(index, value);
        onChanged();
      } else {
        contentPosBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .TikTok.ContentPosition content_pos = 4;</code>
     */
    public Builder setContentPos(
        int index, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ContentPosition.Builder builderForValue) {
      if (contentPosBuilder_ == null) {
        ensureContentPosIsMutable();
        contentPos_.set(index, builderForValue.build());
        onChanged();
      } else {
        contentPosBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .TikTok.ContentPosition content_pos = 4;</code>
     */
    public Builder addContentPos(co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ContentPosition value) {
      if (contentPosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureContentPosIsMutable();
        contentPos_.add(value);
        onChanged();
      } else {
        contentPosBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .TikTok.ContentPosition content_pos = 4;</code>
     */
    public Builder addContentPos(
        int index, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ContentPosition value) {
      if (contentPosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureContentPosIsMutable();
        contentPos_.add(index, value);
        onChanged();
      } else {
        contentPosBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .TikTok.ContentPosition content_pos = 4;</code>
     */
    public Builder addContentPos(
        co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ContentPosition.Builder builderForValue) {
      if (contentPosBuilder_ == null) {
        ensureContentPosIsMutable();
        contentPos_.add(builderForValue.build());
        onChanged();
      } else {
        contentPosBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .TikTok.ContentPosition content_pos = 4;</code>
     */
    public Builder addContentPos(
        int index, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ContentPosition.Builder builderForValue) {
      if (contentPosBuilder_ == null) {
        ensureContentPosIsMutable();
        contentPos_.add(index, builderForValue.build());
        onChanged();
      } else {
        contentPosBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .TikTok.ContentPosition content_pos = 4;</code>
     */
    public Builder addAllContentPos(
        java.lang.Iterable<? extends co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ContentPosition> values) {
      if (contentPosBuilder_ == null) {
        ensureContentPosIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, contentPos_);
        onChanged();
      } else {
        contentPosBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .TikTok.ContentPosition content_pos = 4;</code>
     */
    public Builder clearContentPos() {
      if (contentPosBuilder_ == null) {
        contentPos_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        contentPosBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .TikTok.ContentPosition content_pos = 4;</code>
     */
    public Builder removeContentPos(int index) {
      if (contentPosBuilder_ == null) {
        ensureContentPosIsMutable();
        contentPos_.remove(index);
        onChanged();
      } else {
        contentPosBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .TikTok.ContentPosition content_pos = 4;</code>
     */
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ContentPosition.Builder getContentPosBuilder(
        int index) {
      return internalGetContentPosFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .TikTok.ContentPosition content_pos = 4;</code>
     */
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ContentPositionOrBuilder getContentPosOrBuilder(
        int index) {
      if (contentPosBuilder_ == null) {
        return contentPos_.get(index);  } else {
        return contentPosBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .TikTok.ContentPosition content_pos = 4;</code>
     */
    public java.util.List<? extends co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ContentPositionOrBuilder> 
         getContentPosOrBuilderList() {
      if (contentPosBuilder_ != null) {
        return contentPosBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(contentPos_);
      }
    }
    /**
     * <code>repeated .TikTok.ContentPosition content_pos = 4;</code>
     */
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ContentPosition.Builder addContentPosBuilder() {
      return internalGetContentPosFieldBuilder().addBuilder(
          co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ContentPosition.getDefaultInstance());
    }
    /**
     * <code>repeated .TikTok.ContentPosition content_pos = 4;</code>
     */
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ContentPosition.Builder addContentPosBuilder(
        int index) {
      return internalGetContentPosFieldBuilder().addBuilder(
          index, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ContentPosition.getDefaultInstance());
    }
    /**
     * <code>repeated .TikTok.ContentPosition content_pos = 4;</code>
     */
    public java.util.List<co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ContentPosition.Builder> 
         getContentPosBuilderList() {
      return internalGetContentPosFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ContentPosition, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ContentPosition.Builder, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ContentPositionOrBuilder> 
        internalGetContentPosFieldBuilder() {
      if (contentPosBuilder_ == null) {
        contentPosBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ContentPosition, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ContentPosition.Builder, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ContentPositionOrBuilder>(
                contentPos_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        contentPos_ = null;
      }
      return contentPosBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:TikTok.ListChangeContent)
  }

  // @@protoc_insertion_point(class_scope:TikTok.ListChangeContent)
  private static final co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ListChangeContent DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ListChangeContent();
  }

  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ListChangeContent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListChangeContent>
      PARSER = new com.google.protobuf.AbstractParser<ListChangeContent>() {
    @java.lang.Override
    public ListChangeContent parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ListChangeContent> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListChangeContent> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ListChangeContent getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

