// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: data.proto
// Protobuf Java Version: 4.32.0

package co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data;

/**
 * Protobuf type {@code TikTok.P2PGroupChangeContent}
 */
@com.google.protobuf.Generated
public final class P2PGroupChangeContent extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:TikTok.P2PGroupChangeContent)
    P2PGroupChangeContentOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      P2PGroupChangeContent.class.getName());
  }
  // Use P2PGroupChangeContent.newBuilder() to construct.
  private P2PGroupChangeContent(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private P2PGroupChangeContent() {
    groupExtInfoList_ = java.util.Collections.emptyList();
    contentPos_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Data.internal_static_TikTok_P2PGroupChangeContent_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Data.internal_static_TikTok_P2PGroupChangeContent_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.P2PGroupChangeContent.class, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.P2PGroupChangeContent.Builder.class);
  }

  private int bitField0_;
  public static final int GROUPEXTINFOLIST_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.RTCExtraInfo> groupExtInfoList_;
  /**
   * <code>repeated .TikTok.RTCExtraInfo groupExtInfoList = 1;</code>
   */
  @java.lang.Override
  public java.util.List<co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.RTCExtraInfo> getGroupExtInfoListList() {
    return groupExtInfoList_;
  }
  /**
   * <code>repeated .TikTok.RTCExtraInfo groupExtInfoList = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.RTCExtraInfoOrBuilder> 
      getGroupExtInfoListOrBuilderList() {
    return groupExtInfoList_;
  }
  /**
   * <code>repeated .TikTok.RTCExtraInfo groupExtInfoList = 1;</code>
   */
  @java.lang.Override
  public int getGroupExtInfoListCount() {
    return groupExtInfoList_.size();
  }
  /**
   * <code>repeated .TikTok.RTCExtraInfo groupExtInfoList = 1;</code>
   */
  @java.lang.Override
  public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.RTCExtraInfo getGroupExtInfoList(int index) {
    return groupExtInfoList_.get(index);
  }
  /**
   * <code>repeated .TikTok.RTCExtraInfo groupExtInfoList = 1;</code>
   */
  @java.lang.Override
  public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.RTCExtraInfoOrBuilder getGroupExtInfoListOrBuilder(
      int index) {
    return groupExtInfoList_.get(index);
  }

  public static final int GROUPUSER_FIELD_NUMBER = 2;
  private co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.GroupChannelAllUser groupUser_;
  /**
   * <code>.TikTok.GroupChannelAllUser groupUser = 2;</code>
   * @return Whether the groupUser field is set.
   */
  @java.lang.Override
  public boolean hasGroupUser() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.TikTok.GroupChannelAllUser groupUser = 2;</code>
   * @return The groupUser.
   */
  @java.lang.Override
  public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.GroupChannelAllUser getGroupUser() {
    return groupUser_ == null ? co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.GroupChannelAllUser.getDefaultInstance() : groupUser_;
  }
  /**
   * <code>.TikTok.GroupChannelAllUser groupUser = 2;</code>
   */
  @java.lang.Override
  public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.GroupChannelAllUserOrBuilder getGroupUserOrBuilder() {
    return groupUser_ == null ? co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.GroupChannelAllUser.getDefaultInstance() : groupUser_;
  }

  public static final int MIGRATION_DETAILS_FIELD_NUMBER = 3;
  private co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.MigrationDetails migrationDetails_;
  /**
   * <code>.TikTok.MigrationDetails migration_details = 3;</code>
   * @return Whether the migrationDetails field is set.
   */
  @java.lang.Override
  public boolean hasMigrationDetails() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.TikTok.MigrationDetails migration_details = 3;</code>
   * @return The migrationDetails.
   */
  @java.lang.Override
  public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.MigrationDetails getMigrationDetails() {
    return migrationDetails_ == null ? co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.MigrationDetails.getDefaultInstance() : migrationDetails_;
  }
  /**
   * <code>.TikTok.MigrationDetails migration_details = 3;</code>
   */
  @java.lang.Override
  public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.MigrationDetailsOrBuilder getMigrationDetailsOrBuilder() {
    return migrationDetails_ == null ? co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.MigrationDetails.getDefaultInstance() : migrationDetails_;
  }

  public static final int CONTENT_POS_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private java.util.List<co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ContentPosition> contentPos_;
  /**
   * <code>repeated .TikTok.ContentPosition content_pos = 4;</code>
   */
  @java.lang.Override
  public java.util.List<co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ContentPosition> getContentPosList() {
    return contentPos_;
  }
  /**
   * <code>repeated .TikTok.ContentPosition content_pos = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ContentPositionOrBuilder> 
      getContentPosOrBuilderList() {
    return contentPos_;
  }
  /**
   * <code>repeated .TikTok.ContentPosition content_pos = 4;</code>
   */
  @java.lang.Override
  public int getContentPosCount() {
    return contentPos_.size();
  }
  /**
   * <code>repeated .TikTok.ContentPosition content_pos = 4;</code>
   */
  @java.lang.Override
  public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ContentPosition getContentPos(int index) {
    return contentPos_.get(index);
  }
  /**
   * <code>repeated .TikTok.ContentPosition content_pos = 4;</code>
   */
  @java.lang.Override
  public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ContentPositionOrBuilder getContentPosOrBuilder(
      int index) {
    return contentPos_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < groupExtInfoList_.size(); i++) {
      output.writeMessage(1, groupExtInfoList_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getGroupUser());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(3, getMigrationDetails());
    }
    for (int i = 0; i < contentPos_.size(); i++) {
      output.writeMessage(4, contentPos_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < groupExtInfoList_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, groupExtInfoList_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getGroupUser());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getMigrationDetails());
    }
    for (int i = 0; i < contentPos_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, contentPos_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.P2PGroupChangeContent)) {
      return super.equals(obj);
    }
    co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.P2PGroupChangeContent other = (co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.P2PGroupChangeContent) obj;

    if (!getGroupExtInfoListList()
        .equals(other.getGroupExtInfoListList())) return false;
    if (hasGroupUser() != other.hasGroupUser()) return false;
    if (hasGroupUser()) {
      if (!getGroupUser()
          .equals(other.getGroupUser())) return false;
    }
    if (hasMigrationDetails() != other.hasMigrationDetails()) return false;
    if (hasMigrationDetails()) {
      if (!getMigrationDetails()
          .equals(other.getMigrationDetails())) return false;
    }
    if (!getContentPosList()
        .equals(other.getContentPosList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getGroupExtInfoListCount() > 0) {
      hash = (37 * hash) + GROUPEXTINFOLIST_FIELD_NUMBER;
      hash = (53 * hash) + getGroupExtInfoListList().hashCode();
    }
    if (hasGroupUser()) {
      hash = (37 * hash) + GROUPUSER_FIELD_NUMBER;
      hash = (53 * hash) + getGroupUser().hashCode();
    }
    if (hasMigrationDetails()) {
      hash = (37 * hash) + MIGRATION_DETAILS_FIELD_NUMBER;
      hash = (53 * hash) + getMigrationDetails().hashCode();
    }
    if (getContentPosCount() > 0) {
      hash = (37 * hash) + CONTENT_POS_FIELD_NUMBER;
      hash = (53 * hash) + getContentPosList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.P2PGroupChangeContent parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.P2PGroupChangeContent parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.P2PGroupChangeContent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.P2PGroupChangeContent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.P2PGroupChangeContent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.P2PGroupChangeContent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.P2PGroupChangeContent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.P2PGroupChangeContent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.P2PGroupChangeContent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.P2PGroupChangeContent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.P2PGroupChangeContent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.P2PGroupChangeContent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.P2PGroupChangeContent prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code TikTok.P2PGroupChangeContent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:TikTok.P2PGroupChangeContent)
      co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.P2PGroupChangeContentOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Data.internal_static_TikTok_P2PGroupChangeContent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Data.internal_static_TikTok_P2PGroupChangeContent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.P2PGroupChangeContent.class, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.P2PGroupChangeContent.Builder.class);
    }

    // Construct using co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.P2PGroupChangeContent.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetGroupExtInfoListFieldBuilder();
        internalGetGroupUserFieldBuilder();
        internalGetMigrationDetailsFieldBuilder();
        internalGetContentPosFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (groupExtInfoListBuilder_ == null) {
        groupExtInfoList_ = java.util.Collections.emptyList();
      } else {
        groupExtInfoList_ = null;
        groupExtInfoListBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      groupUser_ = null;
      if (groupUserBuilder_ != null) {
        groupUserBuilder_.dispose();
        groupUserBuilder_ = null;
      }
      migrationDetails_ = null;
      if (migrationDetailsBuilder_ != null) {
        migrationDetailsBuilder_.dispose();
        migrationDetailsBuilder_ = null;
      }
      if (contentPosBuilder_ == null) {
        contentPos_ = java.util.Collections.emptyList();
      } else {
        contentPos_ = null;
        contentPosBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Data.internal_static_TikTok_P2PGroupChangeContent_descriptor;
    }

    @java.lang.Override
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.P2PGroupChangeContent getDefaultInstanceForType() {
      return co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.P2PGroupChangeContent.getDefaultInstance();
    }

    @java.lang.Override
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.P2PGroupChangeContent build() {
      co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.P2PGroupChangeContent result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.P2PGroupChangeContent buildPartial() {
      co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.P2PGroupChangeContent result = new co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.P2PGroupChangeContent(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.P2PGroupChangeContent result) {
      if (groupExtInfoListBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          groupExtInfoList_ = java.util.Collections.unmodifiableList(groupExtInfoList_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.groupExtInfoList_ = groupExtInfoList_;
      } else {
        result.groupExtInfoList_ = groupExtInfoListBuilder_.build();
      }
      if (contentPosBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          contentPos_ = java.util.Collections.unmodifiableList(contentPos_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.contentPos_ = contentPos_;
      } else {
        result.contentPos_ = contentPosBuilder_.build();
      }
    }

    private void buildPartial0(co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.P2PGroupChangeContent result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.groupUser_ = groupUserBuilder_ == null
            ? groupUser_
            : groupUserBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.migrationDetails_ = migrationDetailsBuilder_ == null
            ? migrationDetails_
            : migrationDetailsBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.P2PGroupChangeContent) {
        return mergeFrom((co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.P2PGroupChangeContent)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.P2PGroupChangeContent other) {
      if (other == co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.P2PGroupChangeContent.getDefaultInstance()) return this;
      if (groupExtInfoListBuilder_ == null) {
        if (!other.groupExtInfoList_.isEmpty()) {
          if (groupExtInfoList_.isEmpty()) {
            groupExtInfoList_ = other.groupExtInfoList_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureGroupExtInfoListIsMutable();
            groupExtInfoList_.addAll(other.groupExtInfoList_);
          }
          onChanged();
        }
      } else {
        if (!other.groupExtInfoList_.isEmpty()) {
          if (groupExtInfoListBuilder_.isEmpty()) {
            groupExtInfoListBuilder_.dispose();
            groupExtInfoListBuilder_ = null;
            groupExtInfoList_ = other.groupExtInfoList_;
            bitField0_ = (bitField0_ & ~0x00000001);
            groupExtInfoListBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetGroupExtInfoListFieldBuilder() : null;
          } else {
            groupExtInfoListBuilder_.addAllMessages(other.groupExtInfoList_);
          }
        }
      }
      if (other.hasGroupUser()) {
        mergeGroupUser(other.getGroupUser());
      }
      if (other.hasMigrationDetails()) {
        mergeMigrationDetails(other.getMigrationDetails());
      }
      if (contentPosBuilder_ == null) {
        if (!other.contentPos_.isEmpty()) {
          if (contentPos_.isEmpty()) {
            contentPos_ = other.contentPos_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureContentPosIsMutable();
            contentPos_.addAll(other.contentPos_);
          }
          onChanged();
        }
      } else {
        if (!other.contentPos_.isEmpty()) {
          if (contentPosBuilder_.isEmpty()) {
            contentPosBuilder_.dispose();
            contentPosBuilder_ = null;
            contentPos_ = other.contentPos_;
            bitField0_ = (bitField0_ & ~0x00000008);
            contentPosBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetContentPosFieldBuilder() : null;
          } else {
            contentPosBuilder_.addAllMessages(other.contentPos_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.RTCExtraInfo m =
                  input.readMessage(
                      co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.RTCExtraInfo.parser(),
                      extensionRegistry);
              if (groupExtInfoListBuilder_ == null) {
                ensureGroupExtInfoListIsMutable();
                groupExtInfoList_.add(m);
              } else {
                groupExtInfoListBuilder_.addMessage(m);
              }
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  internalGetGroupUserFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  internalGetMigrationDetailsFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ContentPosition m =
                  input.readMessage(
                      co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ContentPosition.parser(),
                      extensionRegistry);
              if (contentPosBuilder_ == null) {
                ensureContentPosIsMutable();
                contentPos_.add(m);
              } else {
                contentPosBuilder_.addMessage(m);
              }
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.RTCExtraInfo> groupExtInfoList_ =
      java.util.Collections.emptyList();
    private void ensureGroupExtInfoListIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        groupExtInfoList_ = new java.util.ArrayList<co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.RTCExtraInfo>(groupExtInfoList_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.RTCExtraInfo, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.RTCExtraInfo.Builder, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.RTCExtraInfoOrBuilder> groupExtInfoListBuilder_;

    /**
     * <code>repeated .TikTok.RTCExtraInfo groupExtInfoList = 1;</code>
     */
    public java.util.List<co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.RTCExtraInfo> getGroupExtInfoListList() {
      if (groupExtInfoListBuilder_ == null) {
        return java.util.Collections.unmodifiableList(groupExtInfoList_);
      } else {
        return groupExtInfoListBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .TikTok.RTCExtraInfo groupExtInfoList = 1;</code>
     */
    public int getGroupExtInfoListCount() {
      if (groupExtInfoListBuilder_ == null) {
        return groupExtInfoList_.size();
      } else {
        return groupExtInfoListBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .TikTok.RTCExtraInfo groupExtInfoList = 1;</code>
     */
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.RTCExtraInfo getGroupExtInfoList(int index) {
      if (groupExtInfoListBuilder_ == null) {
        return groupExtInfoList_.get(index);
      } else {
        return groupExtInfoListBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .TikTok.RTCExtraInfo groupExtInfoList = 1;</code>
     */
    public Builder setGroupExtInfoList(
        int index, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.RTCExtraInfo value) {
      if (groupExtInfoListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGroupExtInfoListIsMutable();
        groupExtInfoList_.set(index, value);
        onChanged();
      } else {
        groupExtInfoListBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .TikTok.RTCExtraInfo groupExtInfoList = 1;</code>
     */
    public Builder setGroupExtInfoList(
        int index, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.RTCExtraInfo.Builder builderForValue) {
      if (groupExtInfoListBuilder_ == null) {
        ensureGroupExtInfoListIsMutable();
        groupExtInfoList_.set(index, builderForValue.build());
        onChanged();
      } else {
        groupExtInfoListBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .TikTok.RTCExtraInfo groupExtInfoList = 1;</code>
     */
    public Builder addGroupExtInfoList(co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.RTCExtraInfo value) {
      if (groupExtInfoListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGroupExtInfoListIsMutable();
        groupExtInfoList_.add(value);
        onChanged();
      } else {
        groupExtInfoListBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .TikTok.RTCExtraInfo groupExtInfoList = 1;</code>
     */
    public Builder addGroupExtInfoList(
        int index, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.RTCExtraInfo value) {
      if (groupExtInfoListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGroupExtInfoListIsMutable();
        groupExtInfoList_.add(index, value);
        onChanged();
      } else {
        groupExtInfoListBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .TikTok.RTCExtraInfo groupExtInfoList = 1;</code>
     */
    public Builder addGroupExtInfoList(
        co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.RTCExtraInfo.Builder builderForValue) {
      if (groupExtInfoListBuilder_ == null) {
        ensureGroupExtInfoListIsMutable();
        groupExtInfoList_.add(builderForValue.build());
        onChanged();
      } else {
        groupExtInfoListBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .TikTok.RTCExtraInfo groupExtInfoList = 1;</code>
     */
    public Builder addGroupExtInfoList(
        int index, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.RTCExtraInfo.Builder builderForValue) {
      if (groupExtInfoListBuilder_ == null) {
        ensureGroupExtInfoListIsMutable();
        groupExtInfoList_.add(index, builderForValue.build());
        onChanged();
      } else {
        groupExtInfoListBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .TikTok.RTCExtraInfo groupExtInfoList = 1;</code>
     */
    public Builder addAllGroupExtInfoList(
        java.lang.Iterable<? extends co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.RTCExtraInfo> values) {
      if (groupExtInfoListBuilder_ == null) {
        ensureGroupExtInfoListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, groupExtInfoList_);
        onChanged();
      } else {
        groupExtInfoListBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .TikTok.RTCExtraInfo groupExtInfoList = 1;</code>
     */
    public Builder clearGroupExtInfoList() {
      if (groupExtInfoListBuilder_ == null) {
        groupExtInfoList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        groupExtInfoListBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .TikTok.RTCExtraInfo groupExtInfoList = 1;</code>
     */
    public Builder removeGroupExtInfoList(int index) {
      if (groupExtInfoListBuilder_ == null) {
        ensureGroupExtInfoListIsMutable();
        groupExtInfoList_.remove(index);
        onChanged();
      } else {
        groupExtInfoListBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .TikTok.RTCExtraInfo groupExtInfoList = 1;</code>
     */
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.RTCExtraInfo.Builder getGroupExtInfoListBuilder(
        int index) {
      return internalGetGroupExtInfoListFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .TikTok.RTCExtraInfo groupExtInfoList = 1;</code>
     */
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.RTCExtraInfoOrBuilder getGroupExtInfoListOrBuilder(
        int index) {
      if (groupExtInfoListBuilder_ == null) {
        return groupExtInfoList_.get(index);  } else {
        return groupExtInfoListBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .TikTok.RTCExtraInfo groupExtInfoList = 1;</code>
     */
    public java.util.List<? extends co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.RTCExtraInfoOrBuilder> 
         getGroupExtInfoListOrBuilderList() {
      if (groupExtInfoListBuilder_ != null) {
        return groupExtInfoListBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(groupExtInfoList_);
      }
    }
    /**
     * <code>repeated .TikTok.RTCExtraInfo groupExtInfoList = 1;</code>
     */
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.RTCExtraInfo.Builder addGroupExtInfoListBuilder() {
      return internalGetGroupExtInfoListFieldBuilder().addBuilder(
          co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.RTCExtraInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .TikTok.RTCExtraInfo groupExtInfoList = 1;</code>
     */
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.RTCExtraInfo.Builder addGroupExtInfoListBuilder(
        int index) {
      return internalGetGroupExtInfoListFieldBuilder().addBuilder(
          index, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.RTCExtraInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .TikTok.RTCExtraInfo groupExtInfoList = 1;</code>
     */
    public java.util.List<co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.RTCExtraInfo.Builder> 
         getGroupExtInfoListBuilderList() {
      return internalGetGroupExtInfoListFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.RTCExtraInfo, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.RTCExtraInfo.Builder, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.RTCExtraInfoOrBuilder> 
        internalGetGroupExtInfoListFieldBuilder() {
      if (groupExtInfoListBuilder_ == null) {
        groupExtInfoListBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.RTCExtraInfo, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.RTCExtraInfo.Builder, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.RTCExtraInfoOrBuilder>(
                groupExtInfoList_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        groupExtInfoList_ = null;
      }
      return groupExtInfoListBuilder_;
    }

    private co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.GroupChannelAllUser groupUser_;
    private com.google.protobuf.SingleFieldBuilder<
        co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.GroupChannelAllUser, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.GroupChannelAllUser.Builder, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.GroupChannelAllUserOrBuilder> groupUserBuilder_;
    /**
     * <code>.TikTok.GroupChannelAllUser groupUser = 2;</code>
     * @return Whether the groupUser field is set.
     */
    public boolean hasGroupUser() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.TikTok.GroupChannelAllUser groupUser = 2;</code>
     * @return The groupUser.
     */
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.GroupChannelAllUser getGroupUser() {
      if (groupUserBuilder_ == null) {
        return groupUser_ == null ? co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.GroupChannelAllUser.getDefaultInstance() : groupUser_;
      } else {
        return groupUserBuilder_.getMessage();
      }
    }
    /**
     * <code>.TikTok.GroupChannelAllUser groupUser = 2;</code>
     */
    public Builder setGroupUser(co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.GroupChannelAllUser value) {
      if (groupUserBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        groupUser_ = value;
      } else {
        groupUserBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.TikTok.GroupChannelAllUser groupUser = 2;</code>
     */
    public Builder setGroupUser(
        co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.GroupChannelAllUser.Builder builderForValue) {
      if (groupUserBuilder_ == null) {
        groupUser_ = builderForValue.build();
      } else {
        groupUserBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.TikTok.GroupChannelAllUser groupUser = 2;</code>
     */
    public Builder mergeGroupUser(co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.GroupChannelAllUser value) {
      if (groupUserBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          groupUser_ != null &&
          groupUser_ != co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.GroupChannelAllUser.getDefaultInstance()) {
          getGroupUserBuilder().mergeFrom(value);
        } else {
          groupUser_ = value;
        }
      } else {
        groupUserBuilder_.mergeFrom(value);
      }
      if (groupUser_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.TikTok.GroupChannelAllUser groupUser = 2;</code>
     */
    public Builder clearGroupUser() {
      bitField0_ = (bitField0_ & ~0x00000002);
      groupUser_ = null;
      if (groupUserBuilder_ != null) {
        groupUserBuilder_.dispose();
        groupUserBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.TikTok.GroupChannelAllUser groupUser = 2;</code>
     */
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.GroupChannelAllUser.Builder getGroupUserBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return internalGetGroupUserFieldBuilder().getBuilder();
    }
    /**
     * <code>.TikTok.GroupChannelAllUser groupUser = 2;</code>
     */
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.GroupChannelAllUserOrBuilder getGroupUserOrBuilder() {
      if (groupUserBuilder_ != null) {
        return groupUserBuilder_.getMessageOrBuilder();
      } else {
        return groupUser_ == null ?
            co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.GroupChannelAllUser.getDefaultInstance() : groupUser_;
      }
    }
    /**
     * <code>.TikTok.GroupChannelAllUser groupUser = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.GroupChannelAllUser, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.GroupChannelAllUser.Builder, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.GroupChannelAllUserOrBuilder> 
        internalGetGroupUserFieldBuilder() {
      if (groupUserBuilder_ == null) {
        groupUserBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.GroupChannelAllUser, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.GroupChannelAllUser.Builder, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.GroupChannelAllUserOrBuilder>(
                getGroupUser(),
                getParentForChildren(),
                isClean());
        groupUser_ = null;
      }
      return groupUserBuilder_;
    }

    private co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.MigrationDetails migrationDetails_;
    private com.google.protobuf.SingleFieldBuilder<
        co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.MigrationDetails, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.MigrationDetails.Builder, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.MigrationDetailsOrBuilder> migrationDetailsBuilder_;
    /**
     * <code>.TikTok.MigrationDetails migration_details = 3;</code>
     * @return Whether the migrationDetails field is set.
     */
    public boolean hasMigrationDetails() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.TikTok.MigrationDetails migration_details = 3;</code>
     * @return The migrationDetails.
     */
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.MigrationDetails getMigrationDetails() {
      if (migrationDetailsBuilder_ == null) {
        return migrationDetails_ == null ? co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.MigrationDetails.getDefaultInstance() : migrationDetails_;
      } else {
        return migrationDetailsBuilder_.getMessage();
      }
    }
    /**
     * <code>.TikTok.MigrationDetails migration_details = 3;</code>
     */
    public Builder setMigrationDetails(co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.MigrationDetails value) {
      if (migrationDetailsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        migrationDetails_ = value;
      } else {
        migrationDetailsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.TikTok.MigrationDetails migration_details = 3;</code>
     */
    public Builder setMigrationDetails(
        co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.MigrationDetails.Builder builderForValue) {
      if (migrationDetailsBuilder_ == null) {
        migrationDetails_ = builderForValue.build();
      } else {
        migrationDetailsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.TikTok.MigrationDetails migration_details = 3;</code>
     */
    public Builder mergeMigrationDetails(co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.MigrationDetails value) {
      if (migrationDetailsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          migrationDetails_ != null &&
          migrationDetails_ != co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.MigrationDetails.getDefaultInstance()) {
          getMigrationDetailsBuilder().mergeFrom(value);
        } else {
          migrationDetails_ = value;
        }
      } else {
        migrationDetailsBuilder_.mergeFrom(value);
      }
      if (migrationDetails_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.TikTok.MigrationDetails migration_details = 3;</code>
     */
    public Builder clearMigrationDetails() {
      bitField0_ = (bitField0_ & ~0x00000004);
      migrationDetails_ = null;
      if (migrationDetailsBuilder_ != null) {
        migrationDetailsBuilder_.dispose();
        migrationDetailsBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.TikTok.MigrationDetails migration_details = 3;</code>
     */
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.MigrationDetails.Builder getMigrationDetailsBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return internalGetMigrationDetailsFieldBuilder().getBuilder();
    }
    /**
     * <code>.TikTok.MigrationDetails migration_details = 3;</code>
     */
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.MigrationDetailsOrBuilder getMigrationDetailsOrBuilder() {
      if (migrationDetailsBuilder_ != null) {
        return migrationDetailsBuilder_.getMessageOrBuilder();
      } else {
        return migrationDetails_ == null ?
            co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.MigrationDetails.getDefaultInstance() : migrationDetails_;
      }
    }
    /**
     * <code>.TikTok.MigrationDetails migration_details = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.MigrationDetails, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.MigrationDetails.Builder, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.MigrationDetailsOrBuilder> 
        internalGetMigrationDetailsFieldBuilder() {
      if (migrationDetailsBuilder_ == null) {
        migrationDetailsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.MigrationDetails, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.MigrationDetails.Builder, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.MigrationDetailsOrBuilder>(
                getMigrationDetails(),
                getParentForChildren(),
                isClean());
        migrationDetails_ = null;
      }
      return migrationDetailsBuilder_;
    }

    private java.util.List<co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ContentPosition> contentPos_ =
      java.util.Collections.emptyList();
    private void ensureContentPosIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        contentPos_ = new java.util.ArrayList<co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ContentPosition>(contentPos_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ContentPosition, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ContentPosition.Builder, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ContentPositionOrBuilder> contentPosBuilder_;

    /**
     * <code>repeated .TikTok.ContentPosition content_pos = 4;</code>
     */
    public java.util.List<co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ContentPosition> getContentPosList() {
      if (contentPosBuilder_ == null) {
        return java.util.Collections.unmodifiableList(contentPos_);
      } else {
        return contentPosBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .TikTok.ContentPosition content_pos = 4;</code>
     */
    public int getContentPosCount() {
      if (contentPosBuilder_ == null) {
        return contentPos_.size();
      } else {
        return contentPosBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .TikTok.ContentPosition content_pos = 4;</code>
     */
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ContentPosition getContentPos(int index) {
      if (contentPosBuilder_ == null) {
        return contentPos_.get(index);
      } else {
        return contentPosBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .TikTok.ContentPosition content_pos = 4;</code>
     */
    public Builder setContentPos(
        int index, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ContentPosition value) {
      if (contentPosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureContentPosIsMutable();
        contentPos_.set(index, value);
        onChanged();
      } else {
        contentPosBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .TikTok.ContentPosition content_pos = 4;</code>
     */
    public Builder setContentPos(
        int index, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ContentPosition.Builder builderForValue) {
      if (contentPosBuilder_ == null) {
        ensureContentPosIsMutable();
        contentPos_.set(index, builderForValue.build());
        onChanged();
      } else {
        contentPosBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .TikTok.ContentPosition content_pos = 4;</code>
     */
    public Builder addContentPos(co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ContentPosition value) {
      if (contentPosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureContentPosIsMutable();
        contentPos_.add(value);
        onChanged();
      } else {
        contentPosBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .TikTok.ContentPosition content_pos = 4;</code>
     */
    public Builder addContentPos(
        int index, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ContentPosition value) {
      if (contentPosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureContentPosIsMutable();
        contentPos_.add(index, value);
        onChanged();
      } else {
        contentPosBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .TikTok.ContentPosition content_pos = 4;</code>
     */
    public Builder addContentPos(
        co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ContentPosition.Builder builderForValue) {
      if (contentPosBuilder_ == null) {
        ensureContentPosIsMutable();
        contentPos_.add(builderForValue.build());
        onChanged();
      } else {
        contentPosBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .TikTok.ContentPosition content_pos = 4;</code>
     */
    public Builder addContentPos(
        int index, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ContentPosition.Builder builderForValue) {
      if (contentPosBuilder_ == null) {
        ensureContentPosIsMutable();
        contentPos_.add(index, builderForValue.build());
        onChanged();
      } else {
        contentPosBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .TikTok.ContentPosition content_pos = 4;</code>
     */
    public Builder addAllContentPos(
        java.lang.Iterable<? extends co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ContentPosition> values) {
      if (contentPosBuilder_ == null) {
        ensureContentPosIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, contentPos_);
        onChanged();
      } else {
        contentPosBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .TikTok.ContentPosition content_pos = 4;</code>
     */
    public Builder clearContentPos() {
      if (contentPosBuilder_ == null) {
        contentPos_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        contentPosBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .TikTok.ContentPosition content_pos = 4;</code>
     */
    public Builder removeContentPos(int index) {
      if (contentPosBuilder_ == null) {
        ensureContentPosIsMutable();
        contentPos_.remove(index);
        onChanged();
      } else {
        contentPosBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .TikTok.ContentPosition content_pos = 4;</code>
     */
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ContentPosition.Builder getContentPosBuilder(
        int index) {
      return internalGetContentPosFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .TikTok.ContentPosition content_pos = 4;</code>
     */
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ContentPositionOrBuilder getContentPosOrBuilder(
        int index) {
      if (contentPosBuilder_ == null) {
        return contentPos_.get(index);  } else {
        return contentPosBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .TikTok.ContentPosition content_pos = 4;</code>
     */
    public java.util.List<? extends co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ContentPositionOrBuilder> 
         getContentPosOrBuilderList() {
      if (contentPosBuilder_ != null) {
        return contentPosBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(contentPos_);
      }
    }
    /**
     * <code>repeated .TikTok.ContentPosition content_pos = 4;</code>
     */
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ContentPosition.Builder addContentPosBuilder() {
      return internalGetContentPosFieldBuilder().addBuilder(
          co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ContentPosition.getDefaultInstance());
    }
    /**
     * <code>repeated .TikTok.ContentPosition content_pos = 4;</code>
     */
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ContentPosition.Builder addContentPosBuilder(
        int index) {
      return internalGetContentPosFieldBuilder().addBuilder(
          index, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ContentPosition.getDefaultInstance());
    }
    /**
     * <code>repeated .TikTok.ContentPosition content_pos = 4;</code>
     */
    public java.util.List<co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ContentPosition.Builder> 
         getContentPosBuilderList() {
      return internalGetContentPosFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ContentPosition, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ContentPosition.Builder, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ContentPositionOrBuilder> 
        internalGetContentPosFieldBuilder() {
      if (contentPosBuilder_ == null) {
        contentPosBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ContentPosition, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ContentPosition.Builder, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.ContentPositionOrBuilder>(
                contentPos_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        contentPos_ = null;
      }
      return contentPosBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:TikTok.P2PGroupChangeContent)
  }

  // @@protoc_insertion_point(class_scope:TikTok.P2PGroupChangeContent)
  private static final co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.P2PGroupChangeContent DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.P2PGroupChangeContent();
  }

  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.P2PGroupChangeContent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<P2PGroupChangeContent>
      PARSER = new com.google.protobuf.AbstractParser<P2PGroupChangeContent>() {
    @java.lang.Override
    public P2PGroupChangeContent parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<P2PGroupChangeContent> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<P2PGroupChangeContent> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.P2PGroupChangeContent getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

