// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: data.proto
// Protobuf Java Version: 4.32.0

package co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data;

/**
 * <pre>
 * &#64;PermitApplyContent
 * proto.webcast.im
 * C:&#92;Users&#92;ja&#92;RiderProjects&#92;TikTokProBufferGenerator&#92;Application&#92;output&#92;sources&#92;test.js
 * </pre>
 *
 * Protobuf type {@code TikTok.PermitApplyContent}
 */
@com.google.protobuf.Generated
public final class PermitApplyContent extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:TikTok.PermitApplyContent)
    PermitApplyContentOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      PermitApplyContent.class.getName());
  }
  // Use PermitApplyContent.newBuilder() to construct.
  private PermitApplyContent(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private PermitApplyContent() {
    permiterLinkMicId_ = "";
    replyStatus_ = 0;
    applierLinkMicId_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Data.internal_static_TikTok_PermitApplyContent_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Data.internal_static_TikTok_PermitApplyContent_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PermitApplyContent.class, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PermitApplyContent.Builder.class);
  }

  private int bitField0_;
  public static final int PERMITER_FIELD_NUMBER = 1;
  private co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Player permiter_;
  /**
   * <code>.TikTok.Player permiter = 1;</code>
   * @return Whether the permiter field is set.
   */
  @java.lang.Override
  public boolean hasPermiter() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.TikTok.Player permiter = 1;</code>
   * @return The permiter.
   */
  @java.lang.Override
  public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Player getPermiter() {
    return permiter_ == null ? co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Player.getDefaultInstance() : permiter_;
  }
  /**
   * <code>.TikTok.Player permiter = 1;</code>
   */
  @java.lang.Override
  public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PlayerOrBuilder getPermiterOrBuilder() {
    return permiter_ == null ? co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Player.getDefaultInstance() : permiter_;
  }

  public static final int PERMITERLINKMICID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object permiterLinkMicId_ = "";
  /**
   * <code>string permiterLinkMicId = 2;</code>
   * @return The permiterLinkMicId.
   */
  @java.lang.Override
  public java.lang.String getPermiterLinkMicId() {
    java.lang.Object ref = permiterLinkMicId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      permiterLinkMicId_ = s;
      return s;
    }
  }
  /**
   * <code>string permiterLinkMicId = 2;</code>
   * @return The bytes for permiterLinkMicId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPermiterLinkMicIdBytes() {
    java.lang.Object ref = permiterLinkMicId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      permiterLinkMicId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int APPLIERPOS_FIELD_NUMBER = 3;
  private co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Position applierPos_;
  /**
   * <code>.TikTok.Position applierPos = 3;</code>
   * @return Whether the applierPos field is set.
   */
  @java.lang.Override
  public boolean hasApplierPos() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.TikTok.Position applierPos = 3;</code>
   * @return The applierPos.
   */
  @java.lang.Override
  public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Position getApplierPos() {
    return applierPos_ == null ? co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Position.getDefaultInstance() : applierPos_;
  }
  /**
   * <code>.TikTok.Position applierPos = 3;</code>
   */
  @java.lang.Override
  public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PositionOrBuilder getApplierPosOrBuilder() {
    return applierPos_ == null ? co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Position.getDefaultInstance() : applierPos_;
  }

  public static final int REPLYSTATUS_FIELD_NUMBER = 4;
  private int replyStatus_ = 0;
  /**
   * <pre>
   * Enum
   * </pre>
   *
   * <code>.TikTok.ReplyStatus replyStatus = 4;</code>
   * @return The enum numeric value on the wire for replyStatus.
   */
  @java.lang.Override public int getReplyStatusValue() {
    return replyStatus_;
  }
  /**
   * <pre>
   * Enum
   * </pre>
   *
   * <code>.TikTok.ReplyStatus replyStatus = 4;</code>
   * @return The replyStatus.
   */
  @java.lang.Override public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.enums.ReplyStatus getReplyStatus() {
    co.casterlabs.sdk.tiktok.unsupported.types.protobuf.enums.ReplyStatus result = co.casterlabs.sdk.tiktok.unsupported.types.protobuf.enums.ReplyStatus.forNumber(replyStatus_);
    return result == null ? co.casterlabs.sdk.tiktok.unsupported.types.protobuf.enums.ReplyStatus.UNRECOGNIZED : result;
  }

  public static final int DSL_FIELD_NUMBER = 5;
  private co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.DSLConfig dsl_;
  /**
   * <code>.TikTok.DSLConfig dsl = 5;</code>
   * @return Whether the dsl field is set.
   */
  @java.lang.Override
  public boolean hasDsl() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>.TikTok.DSLConfig dsl = 5;</code>
   * @return The dsl.
   */
  @java.lang.Override
  public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.DSLConfig getDsl() {
    return dsl_ == null ? co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.DSLConfig.getDefaultInstance() : dsl_;
  }
  /**
   * <code>.TikTok.DSLConfig dsl = 5;</code>
   */
  @java.lang.Override
  public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.DSLConfigOrBuilder getDslOrBuilder() {
    return dsl_ == null ? co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.DSLConfig.getDefaultInstance() : dsl_;
  }

  public static final int APPLIER_FIELD_NUMBER = 6;
  private co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.User applier_;
  /**
   * <code>.TikTok.User applier = 6;</code>
   * @return Whether the applier field is set.
   */
  @java.lang.Override
  public boolean hasApplier() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>.TikTok.User applier = 6;</code>
   * @return The applier.
   */
  @java.lang.Override
  public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.User getApplier() {
    return applier_ == null ? co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.User.getDefaultInstance() : applier_;
  }
  /**
   * <code>.TikTok.User applier = 6;</code>
   */
  @java.lang.Override
  public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.UserOrBuilder getApplierOrBuilder() {
    return applier_ == null ? co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.User.getDefaultInstance() : applier_;
  }

  public static final int OPERATOR_FIELD_NUMBER = 7;
  private co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.User operator_;
  /**
   * <code>.TikTok.User operator = 7;</code>
   * @return Whether the operator field is set.
   */
  @java.lang.Override
  public boolean hasOperator() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>.TikTok.User operator = 7;</code>
   * @return The operator.
   */
  @java.lang.Override
  public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.User getOperator() {
    return operator_ == null ? co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.User.getDefaultInstance() : operator_;
  }
  /**
   * <code>.TikTok.User operator = 7;</code>
   */
  @java.lang.Override
  public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.UserOrBuilder getOperatorOrBuilder() {
    return operator_ == null ? co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.User.getDefaultInstance() : operator_;
  }

  public static final int APPLIERLINKMICID_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object applierLinkMicId_ = "";
  /**
   * <code>string applierLinkMicId = 8;</code>
   * @return The applierLinkMicId.
   */
  @java.lang.Override
  public java.lang.String getApplierLinkMicId() {
    java.lang.Object ref = applierLinkMicId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      applierLinkMicId_ = s;
      return s;
    }
  }
  /**
   * <code>string applierLinkMicId = 8;</code>
   * @return The bytes for applierLinkMicId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getApplierLinkMicIdBytes() {
    java.lang.Object ref = applierLinkMicId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      applierLinkMicId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getPermiter());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(permiterLinkMicId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, permiterLinkMicId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(3, getApplierPos());
    }
    if (replyStatus_ != co.casterlabs.sdk.tiktok.unsupported.types.protobuf.enums.ReplyStatus.REPLY_STATUS_UNKNOWN.getNumber()) {
      output.writeEnum(4, replyStatus_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(5, getDsl());
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeMessage(6, getApplier());
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeMessage(7, getOperator());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(applierLinkMicId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 8, applierLinkMicId_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getPermiter());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(permiterLinkMicId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, permiterLinkMicId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getApplierPos());
    }
    if (replyStatus_ != co.casterlabs.sdk.tiktok.unsupported.types.protobuf.enums.ReplyStatus.REPLY_STATUS_UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, replyStatus_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getDsl());
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getApplier());
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getOperator());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(applierLinkMicId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(8, applierLinkMicId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PermitApplyContent)) {
      return super.equals(obj);
    }
    co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PermitApplyContent other = (co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PermitApplyContent) obj;

    if (hasPermiter() != other.hasPermiter()) return false;
    if (hasPermiter()) {
      if (!getPermiter()
          .equals(other.getPermiter())) return false;
    }
    if (!getPermiterLinkMicId()
        .equals(other.getPermiterLinkMicId())) return false;
    if (hasApplierPos() != other.hasApplierPos()) return false;
    if (hasApplierPos()) {
      if (!getApplierPos()
          .equals(other.getApplierPos())) return false;
    }
    if (replyStatus_ != other.replyStatus_) return false;
    if (hasDsl() != other.hasDsl()) return false;
    if (hasDsl()) {
      if (!getDsl()
          .equals(other.getDsl())) return false;
    }
    if (hasApplier() != other.hasApplier()) return false;
    if (hasApplier()) {
      if (!getApplier()
          .equals(other.getApplier())) return false;
    }
    if (hasOperator() != other.hasOperator()) return false;
    if (hasOperator()) {
      if (!getOperator()
          .equals(other.getOperator())) return false;
    }
    if (!getApplierLinkMicId()
        .equals(other.getApplierLinkMicId())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasPermiter()) {
      hash = (37 * hash) + PERMITER_FIELD_NUMBER;
      hash = (53 * hash) + getPermiter().hashCode();
    }
    hash = (37 * hash) + PERMITERLINKMICID_FIELD_NUMBER;
    hash = (53 * hash) + getPermiterLinkMicId().hashCode();
    if (hasApplierPos()) {
      hash = (37 * hash) + APPLIERPOS_FIELD_NUMBER;
      hash = (53 * hash) + getApplierPos().hashCode();
    }
    hash = (37 * hash) + REPLYSTATUS_FIELD_NUMBER;
    hash = (53 * hash) + replyStatus_;
    if (hasDsl()) {
      hash = (37 * hash) + DSL_FIELD_NUMBER;
      hash = (53 * hash) + getDsl().hashCode();
    }
    if (hasApplier()) {
      hash = (37 * hash) + APPLIER_FIELD_NUMBER;
      hash = (53 * hash) + getApplier().hashCode();
    }
    if (hasOperator()) {
      hash = (37 * hash) + OPERATOR_FIELD_NUMBER;
      hash = (53 * hash) + getOperator().hashCode();
    }
    hash = (37 * hash) + APPLIERLINKMICID_FIELD_NUMBER;
    hash = (53 * hash) + getApplierLinkMicId().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PermitApplyContent parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PermitApplyContent parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PermitApplyContent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PermitApplyContent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PermitApplyContent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PermitApplyContent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PermitApplyContent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PermitApplyContent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PermitApplyContent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PermitApplyContent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PermitApplyContent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PermitApplyContent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PermitApplyContent prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * &#64;PermitApplyContent
   * proto.webcast.im
   * C:&#92;Users&#92;ja&#92;RiderProjects&#92;TikTokProBufferGenerator&#92;Application&#92;output&#92;sources&#92;test.js
   * </pre>
   *
   * Protobuf type {@code TikTok.PermitApplyContent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:TikTok.PermitApplyContent)
      co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PermitApplyContentOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Data.internal_static_TikTok_PermitApplyContent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Data.internal_static_TikTok_PermitApplyContent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PermitApplyContent.class, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PermitApplyContent.Builder.class);
    }

    // Construct using co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PermitApplyContent.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetPermiterFieldBuilder();
        internalGetApplierPosFieldBuilder();
        internalGetDslFieldBuilder();
        internalGetApplierFieldBuilder();
        internalGetOperatorFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      permiter_ = null;
      if (permiterBuilder_ != null) {
        permiterBuilder_.dispose();
        permiterBuilder_ = null;
      }
      permiterLinkMicId_ = "";
      applierPos_ = null;
      if (applierPosBuilder_ != null) {
        applierPosBuilder_.dispose();
        applierPosBuilder_ = null;
      }
      replyStatus_ = 0;
      dsl_ = null;
      if (dslBuilder_ != null) {
        dslBuilder_.dispose();
        dslBuilder_ = null;
      }
      applier_ = null;
      if (applierBuilder_ != null) {
        applierBuilder_.dispose();
        applierBuilder_ = null;
      }
      operator_ = null;
      if (operatorBuilder_ != null) {
        operatorBuilder_.dispose();
        operatorBuilder_ = null;
      }
      applierLinkMicId_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Data.internal_static_TikTok_PermitApplyContent_descriptor;
    }

    @java.lang.Override
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PermitApplyContent getDefaultInstanceForType() {
      return co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PermitApplyContent.getDefaultInstance();
    }

    @java.lang.Override
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PermitApplyContent build() {
      co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PermitApplyContent result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PermitApplyContent buildPartial() {
      co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PermitApplyContent result = new co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PermitApplyContent(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PermitApplyContent result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.permiter_ = permiterBuilder_ == null
            ? permiter_
            : permiterBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.permiterLinkMicId_ = permiterLinkMicId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.applierPos_ = applierPosBuilder_ == null
            ? applierPos_
            : applierPosBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.replyStatus_ = replyStatus_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.dsl_ = dslBuilder_ == null
            ? dsl_
            : dslBuilder_.build();
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.applier_ = applierBuilder_ == null
            ? applier_
            : applierBuilder_.build();
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.operator_ = operatorBuilder_ == null
            ? operator_
            : operatorBuilder_.build();
        to_bitField0_ |= 0x00000010;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.applierLinkMicId_ = applierLinkMicId_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PermitApplyContent) {
        return mergeFrom((co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PermitApplyContent)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PermitApplyContent other) {
      if (other == co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PermitApplyContent.getDefaultInstance()) return this;
      if (other.hasPermiter()) {
        mergePermiter(other.getPermiter());
      }
      if (!other.getPermiterLinkMicId().isEmpty()) {
        permiterLinkMicId_ = other.permiterLinkMicId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.hasApplierPos()) {
        mergeApplierPos(other.getApplierPos());
      }
      if (other.replyStatus_ != 0) {
        setReplyStatusValue(other.getReplyStatusValue());
      }
      if (other.hasDsl()) {
        mergeDsl(other.getDsl());
      }
      if (other.hasApplier()) {
        mergeApplier(other.getApplier());
      }
      if (other.hasOperator()) {
        mergeOperator(other.getOperator());
      }
      if (!other.getApplierLinkMicId().isEmpty()) {
        applierLinkMicId_ = other.applierLinkMicId_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetPermiterFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              permiterLinkMicId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  internalGetApplierPosFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              replyStatus_ = input.readEnum();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              input.readMessage(
                  internalGetDslFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              input.readMessage(
                  internalGetApplierFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              input.readMessage(
                  internalGetOperatorFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              applierLinkMicId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Player permiter_;
    private com.google.protobuf.SingleFieldBuilder<
        co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Player, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Player.Builder, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PlayerOrBuilder> permiterBuilder_;
    /**
     * <code>.TikTok.Player permiter = 1;</code>
     * @return Whether the permiter field is set.
     */
    public boolean hasPermiter() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.TikTok.Player permiter = 1;</code>
     * @return The permiter.
     */
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Player getPermiter() {
      if (permiterBuilder_ == null) {
        return permiter_ == null ? co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Player.getDefaultInstance() : permiter_;
      } else {
        return permiterBuilder_.getMessage();
      }
    }
    /**
     * <code>.TikTok.Player permiter = 1;</code>
     */
    public Builder setPermiter(co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Player value) {
      if (permiterBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        permiter_ = value;
      } else {
        permiterBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.TikTok.Player permiter = 1;</code>
     */
    public Builder setPermiter(
        co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Player.Builder builderForValue) {
      if (permiterBuilder_ == null) {
        permiter_ = builderForValue.build();
      } else {
        permiterBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.TikTok.Player permiter = 1;</code>
     */
    public Builder mergePermiter(co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Player value) {
      if (permiterBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          permiter_ != null &&
          permiter_ != co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Player.getDefaultInstance()) {
          getPermiterBuilder().mergeFrom(value);
        } else {
          permiter_ = value;
        }
      } else {
        permiterBuilder_.mergeFrom(value);
      }
      if (permiter_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.TikTok.Player permiter = 1;</code>
     */
    public Builder clearPermiter() {
      bitField0_ = (bitField0_ & ~0x00000001);
      permiter_ = null;
      if (permiterBuilder_ != null) {
        permiterBuilder_.dispose();
        permiterBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.TikTok.Player permiter = 1;</code>
     */
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Player.Builder getPermiterBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return internalGetPermiterFieldBuilder().getBuilder();
    }
    /**
     * <code>.TikTok.Player permiter = 1;</code>
     */
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PlayerOrBuilder getPermiterOrBuilder() {
      if (permiterBuilder_ != null) {
        return permiterBuilder_.getMessageOrBuilder();
      } else {
        return permiter_ == null ?
            co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Player.getDefaultInstance() : permiter_;
      }
    }
    /**
     * <code>.TikTok.Player permiter = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Player, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Player.Builder, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PlayerOrBuilder> 
        internalGetPermiterFieldBuilder() {
      if (permiterBuilder_ == null) {
        permiterBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Player, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Player.Builder, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PlayerOrBuilder>(
                getPermiter(),
                getParentForChildren(),
                isClean());
        permiter_ = null;
      }
      return permiterBuilder_;
    }

    private java.lang.Object permiterLinkMicId_ = "";
    /**
     * <code>string permiterLinkMicId = 2;</code>
     * @return The permiterLinkMicId.
     */
    public java.lang.String getPermiterLinkMicId() {
      java.lang.Object ref = permiterLinkMicId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        permiterLinkMicId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string permiterLinkMicId = 2;</code>
     * @return The bytes for permiterLinkMicId.
     */
    public com.google.protobuf.ByteString
        getPermiterLinkMicIdBytes() {
      java.lang.Object ref = permiterLinkMicId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        permiterLinkMicId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string permiterLinkMicId = 2;</code>
     * @param value The permiterLinkMicId to set.
     * @return This builder for chaining.
     */
    public Builder setPermiterLinkMicId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      permiterLinkMicId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string permiterLinkMicId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPermiterLinkMicId() {
      permiterLinkMicId_ = getDefaultInstance().getPermiterLinkMicId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string permiterLinkMicId = 2;</code>
     * @param value The bytes for permiterLinkMicId to set.
     * @return This builder for chaining.
     */
    public Builder setPermiterLinkMicIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      permiterLinkMicId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Position applierPos_;
    private com.google.protobuf.SingleFieldBuilder<
        co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Position, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Position.Builder, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PositionOrBuilder> applierPosBuilder_;
    /**
     * <code>.TikTok.Position applierPos = 3;</code>
     * @return Whether the applierPos field is set.
     */
    public boolean hasApplierPos() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.TikTok.Position applierPos = 3;</code>
     * @return The applierPos.
     */
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Position getApplierPos() {
      if (applierPosBuilder_ == null) {
        return applierPos_ == null ? co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Position.getDefaultInstance() : applierPos_;
      } else {
        return applierPosBuilder_.getMessage();
      }
    }
    /**
     * <code>.TikTok.Position applierPos = 3;</code>
     */
    public Builder setApplierPos(co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Position value) {
      if (applierPosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        applierPos_ = value;
      } else {
        applierPosBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.TikTok.Position applierPos = 3;</code>
     */
    public Builder setApplierPos(
        co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Position.Builder builderForValue) {
      if (applierPosBuilder_ == null) {
        applierPos_ = builderForValue.build();
      } else {
        applierPosBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.TikTok.Position applierPos = 3;</code>
     */
    public Builder mergeApplierPos(co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Position value) {
      if (applierPosBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          applierPos_ != null &&
          applierPos_ != co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Position.getDefaultInstance()) {
          getApplierPosBuilder().mergeFrom(value);
        } else {
          applierPos_ = value;
        }
      } else {
        applierPosBuilder_.mergeFrom(value);
      }
      if (applierPos_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.TikTok.Position applierPos = 3;</code>
     */
    public Builder clearApplierPos() {
      bitField0_ = (bitField0_ & ~0x00000004);
      applierPos_ = null;
      if (applierPosBuilder_ != null) {
        applierPosBuilder_.dispose();
        applierPosBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.TikTok.Position applierPos = 3;</code>
     */
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Position.Builder getApplierPosBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return internalGetApplierPosFieldBuilder().getBuilder();
    }
    /**
     * <code>.TikTok.Position applierPos = 3;</code>
     */
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PositionOrBuilder getApplierPosOrBuilder() {
      if (applierPosBuilder_ != null) {
        return applierPosBuilder_.getMessageOrBuilder();
      } else {
        return applierPos_ == null ?
            co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Position.getDefaultInstance() : applierPos_;
      }
    }
    /**
     * <code>.TikTok.Position applierPos = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Position, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Position.Builder, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PositionOrBuilder> 
        internalGetApplierPosFieldBuilder() {
      if (applierPosBuilder_ == null) {
        applierPosBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Position, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Position.Builder, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PositionOrBuilder>(
                getApplierPos(),
                getParentForChildren(),
                isClean());
        applierPos_ = null;
      }
      return applierPosBuilder_;
    }

    private int replyStatus_ = 0;
    /**
     * <pre>
     * Enum
     * </pre>
     *
     * <code>.TikTok.ReplyStatus replyStatus = 4;</code>
     * @return The enum numeric value on the wire for replyStatus.
     */
    @java.lang.Override public int getReplyStatusValue() {
      return replyStatus_;
    }
    /**
     * <pre>
     * Enum
     * </pre>
     *
     * <code>.TikTok.ReplyStatus replyStatus = 4;</code>
     * @param value The enum numeric value on the wire for replyStatus to set.
     * @return This builder for chaining.
     */
    public Builder setReplyStatusValue(int value) {
      replyStatus_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Enum
     * </pre>
     *
     * <code>.TikTok.ReplyStatus replyStatus = 4;</code>
     * @return The replyStatus.
     */
    @java.lang.Override
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.enums.ReplyStatus getReplyStatus() {
      co.casterlabs.sdk.tiktok.unsupported.types.protobuf.enums.ReplyStatus result = co.casterlabs.sdk.tiktok.unsupported.types.protobuf.enums.ReplyStatus.forNumber(replyStatus_);
      return result == null ? co.casterlabs.sdk.tiktok.unsupported.types.protobuf.enums.ReplyStatus.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Enum
     * </pre>
     *
     * <code>.TikTok.ReplyStatus replyStatus = 4;</code>
     * @param value The replyStatus to set.
     * @return This builder for chaining.
     */
    public Builder setReplyStatus(co.casterlabs.sdk.tiktok.unsupported.types.protobuf.enums.ReplyStatus value) {
      if (value == null) { throw new NullPointerException(); }
      bitField0_ |= 0x00000008;
      replyStatus_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Enum
     * </pre>
     *
     * <code>.TikTok.ReplyStatus replyStatus = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearReplyStatus() {
      bitField0_ = (bitField0_ & ~0x00000008);
      replyStatus_ = 0;
      onChanged();
      return this;
    }

    private co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.DSLConfig dsl_;
    private com.google.protobuf.SingleFieldBuilder<
        co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.DSLConfig, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.DSLConfig.Builder, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.DSLConfigOrBuilder> dslBuilder_;
    /**
     * <code>.TikTok.DSLConfig dsl = 5;</code>
     * @return Whether the dsl field is set.
     */
    public boolean hasDsl() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>.TikTok.DSLConfig dsl = 5;</code>
     * @return The dsl.
     */
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.DSLConfig getDsl() {
      if (dslBuilder_ == null) {
        return dsl_ == null ? co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.DSLConfig.getDefaultInstance() : dsl_;
      } else {
        return dslBuilder_.getMessage();
      }
    }
    /**
     * <code>.TikTok.DSLConfig dsl = 5;</code>
     */
    public Builder setDsl(co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.DSLConfig value) {
      if (dslBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dsl_ = value;
      } else {
        dslBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.TikTok.DSLConfig dsl = 5;</code>
     */
    public Builder setDsl(
        co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.DSLConfig.Builder builderForValue) {
      if (dslBuilder_ == null) {
        dsl_ = builderForValue.build();
      } else {
        dslBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.TikTok.DSLConfig dsl = 5;</code>
     */
    public Builder mergeDsl(co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.DSLConfig value) {
      if (dslBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          dsl_ != null &&
          dsl_ != co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.DSLConfig.getDefaultInstance()) {
          getDslBuilder().mergeFrom(value);
        } else {
          dsl_ = value;
        }
      } else {
        dslBuilder_.mergeFrom(value);
      }
      if (dsl_ != null) {
        bitField0_ |= 0x00000010;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.TikTok.DSLConfig dsl = 5;</code>
     */
    public Builder clearDsl() {
      bitField0_ = (bitField0_ & ~0x00000010);
      dsl_ = null;
      if (dslBuilder_ != null) {
        dslBuilder_.dispose();
        dslBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.TikTok.DSLConfig dsl = 5;</code>
     */
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.DSLConfig.Builder getDslBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return internalGetDslFieldBuilder().getBuilder();
    }
    /**
     * <code>.TikTok.DSLConfig dsl = 5;</code>
     */
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.DSLConfigOrBuilder getDslOrBuilder() {
      if (dslBuilder_ != null) {
        return dslBuilder_.getMessageOrBuilder();
      } else {
        return dsl_ == null ?
            co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.DSLConfig.getDefaultInstance() : dsl_;
      }
    }
    /**
     * <code>.TikTok.DSLConfig dsl = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.DSLConfig, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.DSLConfig.Builder, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.DSLConfigOrBuilder> 
        internalGetDslFieldBuilder() {
      if (dslBuilder_ == null) {
        dslBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.DSLConfig, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.DSLConfig.Builder, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.DSLConfigOrBuilder>(
                getDsl(),
                getParentForChildren(),
                isClean());
        dsl_ = null;
      }
      return dslBuilder_;
    }

    private co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.User applier_;
    private com.google.protobuf.SingleFieldBuilder<
        co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.User, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.User.Builder, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.UserOrBuilder> applierBuilder_;
    /**
     * <code>.TikTok.User applier = 6;</code>
     * @return Whether the applier field is set.
     */
    public boolean hasApplier() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>.TikTok.User applier = 6;</code>
     * @return The applier.
     */
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.User getApplier() {
      if (applierBuilder_ == null) {
        return applier_ == null ? co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.User.getDefaultInstance() : applier_;
      } else {
        return applierBuilder_.getMessage();
      }
    }
    /**
     * <code>.TikTok.User applier = 6;</code>
     */
    public Builder setApplier(co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.User value) {
      if (applierBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        applier_ = value;
      } else {
        applierBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.TikTok.User applier = 6;</code>
     */
    public Builder setApplier(
        co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.User.Builder builderForValue) {
      if (applierBuilder_ == null) {
        applier_ = builderForValue.build();
      } else {
        applierBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.TikTok.User applier = 6;</code>
     */
    public Builder mergeApplier(co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.User value) {
      if (applierBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0) &&
          applier_ != null &&
          applier_ != co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.User.getDefaultInstance()) {
          getApplierBuilder().mergeFrom(value);
        } else {
          applier_ = value;
        }
      } else {
        applierBuilder_.mergeFrom(value);
      }
      if (applier_ != null) {
        bitField0_ |= 0x00000020;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.TikTok.User applier = 6;</code>
     */
    public Builder clearApplier() {
      bitField0_ = (bitField0_ & ~0x00000020);
      applier_ = null;
      if (applierBuilder_ != null) {
        applierBuilder_.dispose();
        applierBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.TikTok.User applier = 6;</code>
     */
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.User.Builder getApplierBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return internalGetApplierFieldBuilder().getBuilder();
    }
    /**
     * <code>.TikTok.User applier = 6;</code>
     */
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.UserOrBuilder getApplierOrBuilder() {
      if (applierBuilder_ != null) {
        return applierBuilder_.getMessageOrBuilder();
      } else {
        return applier_ == null ?
            co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.User.getDefaultInstance() : applier_;
      }
    }
    /**
     * <code>.TikTok.User applier = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.User, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.User.Builder, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.UserOrBuilder> 
        internalGetApplierFieldBuilder() {
      if (applierBuilder_ == null) {
        applierBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.User, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.User.Builder, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.UserOrBuilder>(
                getApplier(),
                getParentForChildren(),
                isClean());
        applier_ = null;
      }
      return applierBuilder_;
    }

    private co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.User operator_;
    private com.google.protobuf.SingleFieldBuilder<
        co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.User, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.User.Builder, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.UserOrBuilder> operatorBuilder_;
    /**
     * <code>.TikTok.User operator = 7;</code>
     * @return Whether the operator field is set.
     */
    public boolean hasOperator() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>.TikTok.User operator = 7;</code>
     * @return The operator.
     */
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.User getOperator() {
      if (operatorBuilder_ == null) {
        return operator_ == null ? co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.User.getDefaultInstance() : operator_;
      } else {
        return operatorBuilder_.getMessage();
      }
    }
    /**
     * <code>.TikTok.User operator = 7;</code>
     */
    public Builder setOperator(co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.User value) {
      if (operatorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        operator_ = value;
      } else {
        operatorBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>.TikTok.User operator = 7;</code>
     */
    public Builder setOperator(
        co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.User.Builder builderForValue) {
      if (operatorBuilder_ == null) {
        operator_ = builderForValue.build();
      } else {
        operatorBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>.TikTok.User operator = 7;</code>
     */
    public Builder mergeOperator(co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.User value) {
      if (operatorBuilder_ == null) {
        if (((bitField0_ & 0x00000040) != 0) &&
          operator_ != null &&
          operator_ != co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.User.getDefaultInstance()) {
          getOperatorBuilder().mergeFrom(value);
        } else {
          operator_ = value;
        }
      } else {
        operatorBuilder_.mergeFrom(value);
      }
      if (operator_ != null) {
        bitField0_ |= 0x00000040;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.TikTok.User operator = 7;</code>
     */
    public Builder clearOperator() {
      bitField0_ = (bitField0_ & ~0x00000040);
      operator_ = null;
      if (operatorBuilder_ != null) {
        operatorBuilder_.dispose();
        operatorBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.TikTok.User operator = 7;</code>
     */
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.User.Builder getOperatorBuilder() {
      bitField0_ |= 0x00000040;
      onChanged();
      return internalGetOperatorFieldBuilder().getBuilder();
    }
    /**
     * <code>.TikTok.User operator = 7;</code>
     */
    public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.UserOrBuilder getOperatorOrBuilder() {
      if (operatorBuilder_ != null) {
        return operatorBuilder_.getMessageOrBuilder();
      } else {
        return operator_ == null ?
            co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.User.getDefaultInstance() : operator_;
      }
    }
    /**
     * <code>.TikTok.User operator = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.User, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.User.Builder, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.UserOrBuilder> 
        internalGetOperatorFieldBuilder() {
      if (operatorBuilder_ == null) {
        operatorBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.User, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.User.Builder, co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.UserOrBuilder>(
                getOperator(),
                getParentForChildren(),
                isClean());
        operator_ = null;
      }
      return operatorBuilder_;
    }

    private java.lang.Object applierLinkMicId_ = "";
    /**
     * <code>string applierLinkMicId = 8;</code>
     * @return The applierLinkMicId.
     */
    public java.lang.String getApplierLinkMicId() {
      java.lang.Object ref = applierLinkMicId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        applierLinkMicId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string applierLinkMicId = 8;</code>
     * @return The bytes for applierLinkMicId.
     */
    public com.google.protobuf.ByteString
        getApplierLinkMicIdBytes() {
      java.lang.Object ref = applierLinkMicId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        applierLinkMicId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string applierLinkMicId = 8;</code>
     * @param value The applierLinkMicId to set.
     * @return This builder for chaining.
     */
    public Builder setApplierLinkMicId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      applierLinkMicId_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>string applierLinkMicId = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearApplierLinkMicId() {
      applierLinkMicId_ = getDefaultInstance().getApplierLinkMicId();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <code>string applierLinkMicId = 8;</code>
     * @param value The bytes for applierLinkMicId to set.
     * @return This builder for chaining.
     */
    public Builder setApplierLinkMicIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      applierLinkMicId_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:TikTok.PermitApplyContent)
  }

  // @@protoc_insertion_point(class_scope:TikTok.PermitApplyContent)
  private static final co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PermitApplyContent DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PermitApplyContent();
  }

  public static co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PermitApplyContent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PermitApplyContent>
      PARSER = new com.google.protobuf.AbstractParser<PermitApplyContent>() {
    @java.lang.Override
    public PermitApplyContent parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PermitApplyContent> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PermitApplyContent> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.PermitApplyContent getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

