// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: data.proto
// Protobuf Java Version: 4.32.0

package co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data;

@com.google.protobuf.Generated
public interface PosIdentityOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TikTok.PosIdentity)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.TikTok.PosIdentityType type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.TikTok.PosIdentityType type = 1;</code>
   * @return The type.
   */
  co.casterlabs.sdk.tiktok.unsupported.types.protobuf.enums.PosIdentityType getType();

  /**
   * <code>string value = 2;</code>
   * @return The value.
   */
  java.lang.String getValue();
  /**
   * <code>string value = 2;</code>
   * @return The bytes for value.
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
