// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: data.proto
// Protobuf Java Version: 4.32.0

package co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data;

@com.google.protobuf.Generated
public interface PositionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TikTok.Position)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 type = 1;</code>
   * @return The type.
   */
  int getType();

  /**
   * <code>.TikTok.LinkPosition link = 2;</code>
   * @return Whether the link field is set.
   */
  boolean hasLink();
  /**
   * <code>.TikTok.LinkPosition link = 2;</code>
   * @return The link.
   */
  co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.LinkPosition getLink();
  /**
   * <code>.TikTok.LinkPosition link = 2;</code>
   */
  co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.LinkPositionOrBuilder getLinkOrBuilder();
}
