// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: data.proto
// Protobuf Java Version: 4.32.0

package co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data;

@com.google.protobuf.Generated
public interface TextOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TikTok.Text)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string displayType = 1;</code>
   * @return The displayType.
   */
  java.lang.String getDisplayType();
  /**
   * <code>string displayType = 1;</code>
   * @return The bytes for displayType.
   */
  com.google.protobuf.ByteString
      getDisplayTypeBytes();

  /**
   * <code>string defaultPattern = 2;</code>
   * @return The defaultPattern.
   */
  java.lang.String getDefaultPattern();
  /**
   * <code>string defaultPattern = 2;</code>
   * @return The bytes for defaultPattern.
   */
  com.google.protobuf.ByteString
      getDefaultPatternBytes();

  /**
   * <code>.TikTok.Text.TextFormat defaultFormat = 3;</code>
   * @return Whether the defaultFormat field is set.
   */
  boolean hasDefaultFormat();
  /**
   * <code>.TikTok.Text.TextFormat defaultFormat = 3;</code>
   * @return The defaultFormat.
   */
  co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Text.TextFormat getDefaultFormat();
  /**
   * <code>.TikTok.Text.TextFormat defaultFormat = 3;</code>
   */
  co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Text.TextFormatOrBuilder getDefaultFormatOrBuilder();

  /**
   * <code>repeated .TikTok.Text.TextPiece piecesList = 4;</code>
   */
  java.util.List<co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Text.TextPiece> 
      getPiecesListList();
  /**
   * <code>repeated .TikTok.Text.TextPiece piecesList = 4;</code>
   */
  co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Text.TextPiece getPiecesList(int index);
  /**
   * <code>repeated .TikTok.Text.TextPiece piecesList = 4;</code>
   */
  int getPiecesListCount();
  /**
   * <code>repeated .TikTok.Text.TextPiece piecesList = 4;</code>
   */
  java.util.List<? extends co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Text.TextPieceOrBuilder> 
      getPiecesListOrBuilderList();
  /**
   * <code>repeated .TikTok.Text.TextPiece piecesList = 4;</code>
   */
  co.casterlabs.sdk.tiktok.unsupported.types.protobuf.data.Text.TextPieceOrBuilder getPiecesListOrBuilder(
      int index);
}
