// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data.proto

package co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data;

public interface EmoteOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TikTok.Emote)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string emoteId = 1;</code>
   * @return The emoteId.
   */
  java.lang.String getEmoteId();
  /**
   * <code>string emoteId = 1;</code>
   * @return The bytes for emoteId.
   */
  com.google.protobuf.ByteString
      getEmoteIdBytes();

  /**
   * <code>.TikTok.Image image = 2;</code>
   * @return Whether the image field is set.
   */
  boolean hasImage();
  /**
   * <code>.TikTok.Image image = 2;</code>
   * @return The image.
   */
  co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.Image getImage();
  /**
   * <code>.TikTok.Image image = 2;</code>
   */
  co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.ImageOrBuilder getImageOrBuilder();

  /**
   * <pre>
   * Enum
   * </pre>
   *
   * <code>.TikTok.AuditStatus auditStatus = 3;</code>
   * @return The enum numeric value on the wire for auditStatus.
   */
  int getAuditStatusValue();
  /**
   * <pre>
   * Enum
   * </pre>
   *
   * <code>.TikTok.AuditStatus auditStatus = 3;</code>
   * @return The auditStatus.
   */
  co.casterlabs.sdk.tiktok.unsupported.webcast.proto.enums.AuditStatus getAuditStatus();

  /**
   * <code>string uuid = 4;</code>
   * @return The uuid.
   */
  java.lang.String getUuid();
  /**
   * <code>string uuid = 4;</code>
   * @return The bytes for uuid.
   */
  com.google.protobuf.ByteString
      getUuidBytes();

  /**
   * <pre>
   * Enum
   * </pre>
   *
   * <code>.TikTok.EmoteType emoteType = 5;</code>
   * @return The enum numeric value on the wire for emoteType.
   */
  int getEmoteTypeValue();
  /**
   * <pre>
   * Enum
   * </pre>
   *
   * <code>.TikTok.EmoteType emoteType = 5;</code>
   * @return The emoteType.
   */
  co.casterlabs.sdk.tiktok.unsupported.webcast.proto.enums.EmoteType getEmoteType();

  /**
   * <pre>
   * Enum
   * </pre>
   *
   * <code>.TikTok.ContentSource contentSource = 6;</code>
   * @return The enum numeric value on the wire for contentSource.
   */
  int getContentSourceValue();
  /**
   * <pre>
   * Enum
   * </pre>
   *
   * <code>.TikTok.ContentSource contentSource = 6;</code>
   * @return The contentSource.
   */
  co.casterlabs.sdk.tiktok.unsupported.webcast.proto.enums.ContentSource getContentSource();

  /**
   * <pre>
   * Enum
   * </pre>
   *
   * <code>.TikTok.EmotePrivateType emotePrivateType = 7;</code>
   * @return The enum numeric value on the wire for emotePrivateType.
   */
  int getEmotePrivateTypeValue();
  /**
   * <pre>
   * Enum
   * </pre>
   *
   * <code>.TikTok.EmotePrivateType emotePrivateType = 7;</code>
   * @return The emotePrivateType.
   */
  co.casterlabs.sdk.tiktok.unsupported.webcast.proto.enums.EmotePrivateType getEmotePrivateType();
}
