// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data.proto

package co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data;

/**
 * Protobuf type {@code TikTok.LinkMicArmiesItems}
 */
public final class LinkMicArmiesItems extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:TikTok.LinkMicArmiesItems)
    LinkMicArmiesItemsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LinkMicArmiesItems.newBuilder() to construct.
  private LinkMicArmiesItems(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LinkMicArmiesItems() {
    battleGroups_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new LinkMicArmiesItems();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.Data.internal_static_TikTok_LinkMicArmiesItems_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.Data.internal_static_TikTok_LinkMicArmiesItems_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.class, co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.Builder.class);
  }

  public interface LinkMicArmiesGroupOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TikTok.LinkMicArmiesItems.LinkMicArmiesGroup)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .TikTok.User users = 1;</code>
     */
    java.util.List<co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.User> 
        getUsersList();
    /**
     * <code>repeated .TikTok.User users = 1;</code>
     */
    co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.User getUsers(int index);
    /**
     * <code>repeated .TikTok.User users = 1;</code>
     */
    int getUsersCount();
    /**
     * <code>repeated .TikTok.User users = 1;</code>
     */
    java.util.List<? extends co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.UserOrBuilder> 
        getUsersOrBuilderList();
    /**
     * <code>repeated .TikTok.User users = 1;</code>
     */
    co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.UserOrBuilder getUsersOrBuilder(
        int index);

    /**
     * <code>uint32 points = 2;</code>
     * @return The points.
     */
    int getPoints();
  }
  /**
   * Protobuf type {@code TikTok.LinkMicArmiesItems.LinkMicArmiesGroup}
   */
  public static final class LinkMicArmiesGroup extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TikTok.LinkMicArmiesItems.LinkMicArmiesGroup)
      LinkMicArmiesGroupOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LinkMicArmiesGroup.newBuilder() to construct.
    private LinkMicArmiesGroup(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LinkMicArmiesGroup() {
      users_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new LinkMicArmiesGroup();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.Data.internal_static_TikTok_LinkMicArmiesItems_LinkMicArmiesGroup_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.Data.internal_static_TikTok_LinkMicArmiesItems_LinkMicArmiesGroup_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroup.class, co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroup.Builder.class);
    }

    public static final int USERS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.User> users_;
    /**
     * <code>repeated .TikTok.User users = 1;</code>
     */
    @java.lang.Override
    public java.util.List<co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.User> getUsersList() {
      return users_;
    }
    /**
     * <code>repeated .TikTok.User users = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.UserOrBuilder> 
        getUsersOrBuilderList() {
      return users_;
    }
    /**
     * <code>repeated .TikTok.User users = 1;</code>
     */
    @java.lang.Override
    public int getUsersCount() {
      return users_.size();
    }
    /**
     * <code>repeated .TikTok.User users = 1;</code>
     */
    @java.lang.Override
    public co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.User getUsers(int index) {
      return users_.get(index);
    }
    /**
     * <code>repeated .TikTok.User users = 1;</code>
     */
    @java.lang.Override
    public co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.UserOrBuilder getUsersOrBuilder(
        int index) {
      return users_.get(index);
    }

    public static final int POINTS_FIELD_NUMBER = 2;
    private int points_ = 0;
    /**
     * <code>uint32 points = 2;</code>
     * @return The points.
     */
    @java.lang.Override
    public int getPoints() {
      return points_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < users_.size(); i++) {
        output.writeMessage(1, users_.get(i));
      }
      if (points_ != 0) {
        output.writeUInt32(2, points_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < users_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, users_.get(i));
      }
      if (points_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, points_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroup)) {
        return super.equals(obj);
      }
      co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroup other = (co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroup) obj;

      if (!getUsersList()
          .equals(other.getUsersList())) return false;
      if (getPoints()
          != other.getPoints()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getUsersCount() > 0) {
        hash = (37 * hash) + USERS_FIELD_NUMBER;
        hash = (53 * hash) + getUsersList().hashCode();
      }
      hash = (37 * hash) + POINTS_FIELD_NUMBER;
      hash = (53 * hash) + getPoints();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroup parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroup parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroup parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroup parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroup parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroup parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroup parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroup parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroup parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroup parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroup parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroup parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroup prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TikTok.LinkMicArmiesItems.LinkMicArmiesGroup}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TikTok.LinkMicArmiesItems.LinkMicArmiesGroup)
        co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroupOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.Data.internal_static_TikTok_LinkMicArmiesItems_LinkMicArmiesGroup_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.Data.internal_static_TikTok_LinkMicArmiesItems_LinkMicArmiesGroup_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroup.class, co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroup.Builder.class);
      }

      // Construct using co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroup.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (usersBuilder_ == null) {
          users_ = java.util.Collections.emptyList();
        } else {
          users_ = null;
          usersBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        points_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.Data.internal_static_TikTok_LinkMicArmiesItems_LinkMicArmiesGroup_descriptor;
      }

      @java.lang.Override
      public co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroup getDefaultInstanceForType() {
        return co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroup.getDefaultInstance();
      }

      @java.lang.Override
      public co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroup build() {
        co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroup result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroup buildPartial() {
        co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroup result = new co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroup(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroup result) {
        if (usersBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            users_ = java.util.Collections.unmodifiableList(users_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.users_ = users_;
        } else {
          result.users_ = usersBuilder_.build();
        }
      }

      private void buildPartial0(co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroup result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.points_ = points_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroup) {
          return mergeFrom((co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroup)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroup other) {
        if (other == co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroup.getDefaultInstance()) return this;
        if (usersBuilder_ == null) {
          if (!other.users_.isEmpty()) {
            if (users_.isEmpty()) {
              users_ = other.users_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureUsersIsMutable();
              users_.addAll(other.users_);
            }
            onChanged();
          }
        } else {
          if (!other.users_.isEmpty()) {
            if (usersBuilder_.isEmpty()) {
              usersBuilder_.dispose();
              usersBuilder_ = null;
              users_ = other.users_;
              bitField0_ = (bitField0_ & ~0x00000001);
              usersBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getUsersFieldBuilder() : null;
            } else {
              usersBuilder_.addAllMessages(other.users_);
            }
          }
        }
        if (other.getPoints() != 0) {
          setPoints(other.getPoints());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.User m =
                    input.readMessage(
                        co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.User.parser(),
                        extensionRegistry);
                if (usersBuilder_ == null) {
                  ensureUsersIsMutable();
                  users_.add(m);
                } else {
                  usersBuilder_.addMessage(m);
                }
                break;
              } // case 10
              case 16: {
                points_ = input.readUInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.User> users_ =
        java.util.Collections.emptyList();
      private void ensureUsersIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          users_ = new java.util.ArrayList<co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.User>(users_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.User, co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.User.Builder, co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.UserOrBuilder> usersBuilder_;

      /**
       * <code>repeated .TikTok.User users = 1;</code>
       */
      public java.util.List<co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.User> getUsersList() {
        if (usersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(users_);
        } else {
          return usersBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .TikTok.User users = 1;</code>
       */
      public int getUsersCount() {
        if (usersBuilder_ == null) {
          return users_.size();
        } else {
          return usersBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .TikTok.User users = 1;</code>
       */
      public co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.User getUsers(int index) {
        if (usersBuilder_ == null) {
          return users_.get(index);
        } else {
          return usersBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .TikTok.User users = 1;</code>
       */
      public Builder setUsers(
          int index, co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.User value) {
        if (usersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUsersIsMutable();
          users_.set(index, value);
          onChanged();
        } else {
          usersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .TikTok.User users = 1;</code>
       */
      public Builder setUsers(
          int index, co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.User.Builder builderForValue) {
        if (usersBuilder_ == null) {
          ensureUsersIsMutable();
          users_.set(index, builderForValue.build());
          onChanged();
        } else {
          usersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .TikTok.User users = 1;</code>
       */
      public Builder addUsers(co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.User value) {
        if (usersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUsersIsMutable();
          users_.add(value);
          onChanged();
        } else {
          usersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .TikTok.User users = 1;</code>
       */
      public Builder addUsers(
          int index, co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.User value) {
        if (usersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUsersIsMutable();
          users_.add(index, value);
          onChanged();
        } else {
          usersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .TikTok.User users = 1;</code>
       */
      public Builder addUsers(
          co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.User.Builder builderForValue) {
        if (usersBuilder_ == null) {
          ensureUsersIsMutable();
          users_.add(builderForValue.build());
          onChanged();
        } else {
          usersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .TikTok.User users = 1;</code>
       */
      public Builder addUsers(
          int index, co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.User.Builder builderForValue) {
        if (usersBuilder_ == null) {
          ensureUsersIsMutable();
          users_.add(index, builderForValue.build());
          onChanged();
        } else {
          usersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .TikTok.User users = 1;</code>
       */
      public Builder addAllUsers(
          java.lang.Iterable<? extends co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.User> values) {
        if (usersBuilder_ == null) {
          ensureUsersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, users_);
          onChanged();
        } else {
          usersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .TikTok.User users = 1;</code>
       */
      public Builder clearUsers() {
        if (usersBuilder_ == null) {
          users_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          usersBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .TikTok.User users = 1;</code>
       */
      public Builder removeUsers(int index) {
        if (usersBuilder_ == null) {
          ensureUsersIsMutable();
          users_.remove(index);
          onChanged();
        } else {
          usersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .TikTok.User users = 1;</code>
       */
      public co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.User.Builder getUsersBuilder(
          int index) {
        return getUsersFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .TikTok.User users = 1;</code>
       */
      public co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.UserOrBuilder getUsersOrBuilder(
          int index) {
        if (usersBuilder_ == null) {
          return users_.get(index);  } else {
          return usersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .TikTok.User users = 1;</code>
       */
      public java.util.List<? extends co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.UserOrBuilder> 
           getUsersOrBuilderList() {
        if (usersBuilder_ != null) {
          return usersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(users_);
        }
      }
      /**
       * <code>repeated .TikTok.User users = 1;</code>
       */
      public co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.User.Builder addUsersBuilder() {
        return getUsersFieldBuilder().addBuilder(
            co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.User.getDefaultInstance());
      }
      /**
       * <code>repeated .TikTok.User users = 1;</code>
       */
      public co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.User.Builder addUsersBuilder(
          int index) {
        return getUsersFieldBuilder().addBuilder(
            index, co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.User.getDefaultInstance());
      }
      /**
       * <code>repeated .TikTok.User users = 1;</code>
       */
      public java.util.List<co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.User.Builder> 
           getUsersBuilderList() {
        return getUsersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.User, co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.User.Builder, co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.UserOrBuilder> 
          getUsersFieldBuilder() {
        if (usersBuilder_ == null) {
          usersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.User, co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.User.Builder, co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.UserOrBuilder>(
                  users_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          users_ = null;
        }
        return usersBuilder_;
      }

      private int points_ ;
      /**
       * <code>uint32 points = 2;</code>
       * @return The points.
       */
      @java.lang.Override
      public int getPoints() {
        return points_;
      }
      /**
       * <code>uint32 points = 2;</code>
       * @param value The points to set.
       * @return This builder for chaining.
       */
      public Builder setPoints(int value) {

        points_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 points = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPoints() {
        bitField0_ = (bitField0_ & ~0x00000002);
        points_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TikTok.LinkMicArmiesItems.LinkMicArmiesGroup)
    }

    // @@protoc_insertion_point(class_scope:TikTok.LinkMicArmiesItems.LinkMicArmiesGroup)
    private static final co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroup DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroup();
    }

    public static co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroup getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LinkMicArmiesGroup>
        PARSER = new com.google.protobuf.AbstractParser<LinkMicArmiesGroup>() {
      @java.lang.Override
      public LinkMicArmiesGroup parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<LinkMicArmiesGroup> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LinkMicArmiesGroup> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroup getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int HOSTUSERID_FIELD_NUMBER = 1;
  private long hostUserId_ = 0L;
  /**
   * <code>uint64 hostUserId = 1;</code>
   * @return The hostUserId.
   */
  @java.lang.Override
  public long getHostUserId() {
    return hostUserId_;
  }

  public static final int BATTLEGROUPS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroup> battleGroups_;
  /**
   * <code>repeated .TikTok.LinkMicArmiesItems.LinkMicArmiesGroup battleGroups = 2;</code>
   */
  @java.lang.Override
  public java.util.List<co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroup> getBattleGroupsList() {
    return battleGroups_;
  }
  /**
   * <code>repeated .TikTok.LinkMicArmiesItems.LinkMicArmiesGroup battleGroups = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroupOrBuilder> 
      getBattleGroupsOrBuilderList() {
    return battleGroups_;
  }
  /**
   * <code>repeated .TikTok.LinkMicArmiesItems.LinkMicArmiesGroup battleGroups = 2;</code>
   */
  @java.lang.Override
  public int getBattleGroupsCount() {
    return battleGroups_.size();
  }
  /**
   * <code>repeated .TikTok.LinkMicArmiesItems.LinkMicArmiesGroup battleGroups = 2;</code>
   */
  @java.lang.Override
  public co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroup getBattleGroups(int index) {
    return battleGroups_.get(index);
  }
  /**
   * <code>repeated .TikTok.LinkMicArmiesItems.LinkMicArmiesGroup battleGroups = 2;</code>
   */
  @java.lang.Override
  public co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroupOrBuilder getBattleGroupsOrBuilder(
      int index) {
    return battleGroups_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (hostUserId_ != 0L) {
      output.writeUInt64(1, hostUserId_);
    }
    for (int i = 0; i < battleGroups_.size(); i++) {
      output.writeMessage(2, battleGroups_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (hostUserId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, hostUserId_);
    }
    for (int i = 0; i < battleGroups_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, battleGroups_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems)) {
      return super.equals(obj);
    }
    co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems other = (co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems) obj;

    if (getHostUserId()
        != other.getHostUserId()) return false;
    if (!getBattleGroupsList()
        .equals(other.getBattleGroupsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + HOSTUSERID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getHostUserId());
    if (getBattleGroupsCount() > 0) {
      hash = (37 * hash) + BATTLEGROUPS_FIELD_NUMBER;
      hash = (53 * hash) + getBattleGroupsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code TikTok.LinkMicArmiesItems}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:TikTok.LinkMicArmiesItems)
      co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItemsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.Data.internal_static_TikTok_LinkMicArmiesItems_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.Data.internal_static_TikTok_LinkMicArmiesItems_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.class, co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.Builder.class);
    }

    // Construct using co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      hostUserId_ = 0L;
      if (battleGroupsBuilder_ == null) {
        battleGroups_ = java.util.Collections.emptyList();
      } else {
        battleGroups_ = null;
        battleGroupsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.Data.internal_static_TikTok_LinkMicArmiesItems_descriptor;
    }

    @java.lang.Override
    public co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems getDefaultInstanceForType() {
      return co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.getDefaultInstance();
    }

    @java.lang.Override
    public co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems build() {
      co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems buildPartial() {
      co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems result = new co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems result) {
      if (battleGroupsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          battleGroups_ = java.util.Collections.unmodifiableList(battleGroups_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.battleGroups_ = battleGroups_;
      } else {
        result.battleGroups_ = battleGroupsBuilder_.build();
      }
    }

    private void buildPartial0(co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.hostUserId_ = hostUserId_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems) {
        return mergeFrom((co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems other) {
      if (other == co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.getDefaultInstance()) return this;
      if (other.getHostUserId() != 0L) {
        setHostUserId(other.getHostUserId());
      }
      if (battleGroupsBuilder_ == null) {
        if (!other.battleGroups_.isEmpty()) {
          if (battleGroups_.isEmpty()) {
            battleGroups_ = other.battleGroups_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureBattleGroupsIsMutable();
            battleGroups_.addAll(other.battleGroups_);
          }
          onChanged();
        }
      } else {
        if (!other.battleGroups_.isEmpty()) {
          if (battleGroupsBuilder_.isEmpty()) {
            battleGroupsBuilder_.dispose();
            battleGroupsBuilder_ = null;
            battleGroups_ = other.battleGroups_;
            bitField0_ = (bitField0_ & ~0x00000002);
            battleGroupsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getBattleGroupsFieldBuilder() : null;
          } else {
            battleGroupsBuilder_.addAllMessages(other.battleGroups_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              hostUserId_ = input.readUInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroup m =
                  input.readMessage(
                      co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroup.parser(),
                      extensionRegistry);
              if (battleGroupsBuilder_ == null) {
                ensureBattleGroupsIsMutable();
                battleGroups_.add(m);
              } else {
                battleGroupsBuilder_.addMessage(m);
              }
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long hostUserId_ ;
    /**
     * <code>uint64 hostUserId = 1;</code>
     * @return The hostUserId.
     */
    @java.lang.Override
    public long getHostUserId() {
      return hostUserId_;
    }
    /**
     * <code>uint64 hostUserId = 1;</code>
     * @param value The hostUserId to set.
     * @return This builder for chaining.
     */
    public Builder setHostUserId(long value) {

      hostUserId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 hostUserId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearHostUserId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      hostUserId_ = 0L;
      onChanged();
      return this;
    }

    private java.util.List<co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroup> battleGroups_ =
      java.util.Collections.emptyList();
    private void ensureBattleGroupsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        battleGroups_ = new java.util.ArrayList<co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroup>(battleGroups_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroup, co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroup.Builder, co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroupOrBuilder> battleGroupsBuilder_;

    /**
     * <code>repeated .TikTok.LinkMicArmiesItems.LinkMicArmiesGroup battleGroups = 2;</code>
     */
    public java.util.List<co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroup> getBattleGroupsList() {
      if (battleGroupsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(battleGroups_);
      } else {
        return battleGroupsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .TikTok.LinkMicArmiesItems.LinkMicArmiesGroup battleGroups = 2;</code>
     */
    public int getBattleGroupsCount() {
      if (battleGroupsBuilder_ == null) {
        return battleGroups_.size();
      } else {
        return battleGroupsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .TikTok.LinkMicArmiesItems.LinkMicArmiesGroup battleGroups = 2;</code>
     */
    public co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroup getBattleGroups(int index) {
      if (battleGroupsBuilder_ == null) {
        return battleGroups_.get(index);
      } else {
        return battleGroupsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .TikTok.LinkMicArmiesItems.LinkMicArmiesGroup battleGroups = 2;</code>
     */
    public Builder setBattleGroups(
        int index, co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroup value) {
      if (battleGroupsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBattleGroupsIsMutable();
        battleGroups_.set(index, value);
        onChanged();
      } else {
        battleGroupsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .TikTok.LinkMicArmiesItems.LinkMicArmiesGroup battleGroups = 2;</code>
     */
    public Builder setBattleGroups(
        int index, co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroup.Builder builderForValue) {
      if (battleGroupsBuilder_ == null) {
        ensureBattleGroupsIsMutable();
        battleGroups_.set(index, builderForValue.build());
        onChanged();
      } else {
        battleGroupsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .TikTok.LinkMicArmiesItems.LinkMicArmiesGroup battleGroups = 2;</code>
     */
    public Builder addBattleGroups(co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroup value) {
      if (battleGroupsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBattleGroupsIsMutable();
        battleGroups_.add(value);
        onChanged();
      } else {
        battleGroupsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .TikTok.LinkMicArmiesItems.LinkMicArmiesGroup battleGroups = 2;</code>
     */
    public Builder addBattleGroups(
        int index, co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroup value) {
      if (battleGroupsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBattleGroupsIsMutable();
        battleGroups_.add(index, value);
        onChanged();
      } else {
        battleGroupsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .TikTok.LinkMicArmiesItems.LinkMicArmiesGroup battleGroups = 2;</code>
     */
    public Builder addBattleGroups(
        co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroup.Builder builderForValue) {
      if (battleGroupsBuilder_ == null) {
        ensureBattleGroupsIsMutable();
        battleGroups_.add(builderForValue.build());
        onChanged();
      } else {
        battleGroupsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .TikTok.LinkMicArmiesItems.LinkMicArmiesGroup battleGroups = 2;</code>
     */
    public Builder addBattleGroups(
        int index, co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroup.Builder builderForValue) {
      if (battleGroupsBuilder_ == null) {
        ensureBattleGroupsIsMutable();
        battleGroups_.add(index, builderForValue.build());
        onChanged();
      } else {
        battleGroupsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .TikTok.LinkMicArmiesItems.LinkMicArmiesGroup battleGroups = 2;</code>
     */
    public Builder addAllBattleGroups(
        java.lang.Iterable<? extends co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroup> values) {
      if (battleGroupsBuilder_ == null) {
        ensureBattleGroupsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, battleGroups_);
        onChanged();
      } else {
        battleGroupsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .TikTok.LinkMicArmiesItems.LinkMicArmiesGroup battleGroups = 2;</code>
     */
    public Builder clearBattleGroups() {
      if (battleGroupsBuilder_ == null) {
        battleGroups_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        battleGroupsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .TikTok.LinkMicArmiesItems.LinkMicArmiesGroup battleGroups = 2;</code>
     */
    public Builder removeBattleGroups(int index) {
      if (battleGroupsBuilder_ == null) {
        ensureBattleGroupsIsMutable();
        battleGroups_.remove(index);
        onChanged();
      } else {
        battleGroupsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .TikTok.LinkMicArmiesItems.LinkMicArmiesGroup battleGroups = 2;</code>
     */
    public co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroup.Builder getBattleGroupsBuilder(
        int index) {
      return getBattleGroupsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .TikTok.LinkMicArmiesItems.LinkMicArmiesGroup battleGroups = 2;</code>
     */
    public co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroupOrBuilder getBattleGroupsOrBuilder(
        int index) {
      if (battleGroupsBuilder_ == null) {
        return battleGroups_.get(index);  } else {
        return battleGroupsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .TikTok.LinkMicArmiesItems.LinkMicArmiesGroup battleGroups = 2;</code>
     */
    public java.util.List<? extends co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroupOrBuilder> 
         getBattleGroupsOrBuilderList() {
      if (battleGroupsBuilder_ != null) {
        return battleGroupsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(battleGroups_);
      }
    }
    /**
     * <code>repeated .TikTok.LinkMicArmiesItems.LinkMicArmiesGroup battleGroups = 2;</code>
     */
    public co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroup.Builder addBattleGroupsBuilder() {
      return getBattleGroupsFieldBuilder().addBuilder(
          co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroup.getDefaultInstance());
    }
    /**
     * <code>repeated .TikTok.LinkMicArmiesItems.LinkMicArmiesGroup battleGroups = 2;</code>
     */
    public co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroup.Builder addBattleGroupsBuilder(
        int index) {
      return getBattleGroupsFieldBuilder().addBuilder(
          index, co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroup.getDefaultInstance());
    }
    /**
     * <code>repeated .TikTok.LinkMicArmiesItems.LinkMicArmiesGroup battleGroups = 2;</code>
     */
    public java.util.List<co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroup.Builder> 
         getBattleGroupsBuilderList() {
      return getBattleGroupsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroup, co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroup.Builder, co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroupOrBuilder> 
        getBattleGroupsFieldBuilder() {
      if (battleGroupsBuilder_ == null) {
        battleGroupsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroup, co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroup.Builder, co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems.LinkMicArmiesGroupOrBuilder>(
                battleGroups_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        battleGroups_ = null;
      }
      return battleGroupsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:TikTok.LinkMicArmiesItems)
  }

  // @@protoc_insertion_point(class_scope:TikTok.LinkMicArmiesItems)
  private static final co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems();
  }

  public static co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LinkMicArmiesItems>
      PARSER = new com.google.protobuf.AbstractParser<LinkMicArmiesItems>() {
    @java.lang.Override
    public LinkMicArmiesItems parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<LinkMicArmiesItems> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LinkMicArmiesItems> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public co.casterlabs.sdk.tiktok.unsupported.webcast.proto.data.LinkMicArmiesItems getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

